// =============================================================================
// compendiumUuidsData - GERADO por `npm run gen:uuids`. NÃO EDITE À MÃO.
// =============================================================================
// Identificadores de documentos dos compêndios do sistema dnd5e (SRD 2024, MIT +
// CC-BY-4.0), extraídos de packs/_source. Apenas ids e nomes - nenhum conteúdo de
// jogo é redistribuído aqui. Consumidos por engine/compendiumUuids.js para montar
// os ItemGrant de níveis FUTUROS (ver o módulo irmão para o porquê).
//
// Cobertura: as 12 classes XPHB (198 features), 12 subclasses SRD
// (58 features), 340 magias, 54 origens,
// 17 talentos e 572 itens de equipamento.
// -----------------------------------------------------------------------------

/** Pacote de compêndio de cada mapa (prefixo do uuid). */
export const PACK_CLASSES = 'Compendium.dnd5e.classes24.Item';
export const PACK_SPELLS = 'Compendium.dnd5e.spells24.Item';
export const PACK_ORIGINS = 'Compendium.dnd5e.origins24.Item';
export const PACK_FEATS = 'Compendium.dnd5e.feats24.Item';
export const PACK_EQUIPMENT = 'Compendium.dnd5e.equipment24.Item';

/** `classId` → _id do documento da CLASSE (pacote classes24). */
export const CLASS_IDS = {
  "barbarian": "phbbrbBarbarian0",
  "bard": "phbbrdBard000000",
  "cleric": "phbclcCleric0000",
  "druid": "phbdrdDruid00000",
  "fighter": "phbftrFighter000",
  "monk": "phbmnkMonk000000",
  "paladin": "phbpdnPaladin000",
  "ranger": "phbrgrRanger0000",
  "rogue": "phbrgeRogue00000",
  "sorcerer": "phbscrSorcerer00",
  "warlock": "phbwlkWarlock000",
  "wizard": "phbwzdWizard0000",
};

/** `classId|nomeDaFeature` → _id (pacote classes24). */
export const CLASS_FEATURE_IDS = {
  "barbarian|brutal strike": "phbbrbBrutalStri",
  "barbarian|danger sense": "phbbrbDangerSens",
  "barbarian|epic boon": "phbbrbEpicBoon00",
  "barbarian|extra attack": "phbbrbExtraAttac",
  "barbarian|fast movement": "phbbrbFastMoveme",
  "barbarian|feral instinct": "phbbrbFeralInsti",
  "barbarian|improved brutal strike": "phbbrbImpBrutalS",
  "barbarian|improved brutal strike (2)": "phbbrbImp2Brutal",
  "barbarian|indomitable might": "phbbrbIndomitabl",
  "barbarian|instinctive pounce": "phbbrbInstinctiv",
  "barbarian|persistent rage": "phbbrbPersistent",
  "barbarian|primal champion": "phbbrbPrimalCham",
  "barbarian|primal knowledge": "phbbrbPrimalKnow",
  "barbarian|rage": "phbbrbRage000000",
  "barbarian|reckless attack": "phbbrbRecklessAt",
  "barbarian|relentless rage": "phbbrbRelentless",
  "barbarian|unarmored defense": "phbbrbUnarmoredD",
  "barbarian|weapon mastery": "phbbrbWeaponMast",
  "bard|bardic inspiration": "phbbrdBardicInsp",
  "bard|countercharm": "phbbrdCountercha",
  "bard|epic boon": "phbbrdEpicBoon00",
  "bard|expertise": "phbbrdExpertise0",
  "bard|font of inspiration": "phbbrdFontOfInsp",
  "bard|jack of all trades": "phbbrdJackOfAllT",
  "bard|magical secrets": "phbbrdMagicalSec",
  "bard|spellcasting": "phbbrdSpellcasti",
  "bard|superior inspiration": "phbbrdSuperiorIn",
  "bard|words of creation": "phbbrdWordsOfCre",
  "cleric|blessed strikes": "phbclcBlessedStr",
  "cleric|blessed strikes: divine strike": "phbDivineStrike0",
  "cleric|blessed strikes: potent spellcasting": "phbClcPotentSpel",
  "cleric|channel divinity": "phbclcChannelDiv",
  "cleric|divine intervention": "phbclcDivineInte",
  "cleric|divine order": "phbclcDivineOrde",
  "cleric|divine order: protector": "phbDivineOrderPr",
  "cleric|divine order: thaumaturge": "phbDivineOrderTh",
  "cleric|epic boon": "phbclcEpicBoon00",
  "cleric|greater divine intervention": "phbclcGreaterDiv",
  "cleric|improved blessed strikes": "phbclcImprovedBl",
  "cleric|sear undead": "phbclcSearUndead",
  "cleric|spellcasting": "phbclcSpellcasti",
  "druid|archdruid": "phbdrdArchdruid0",
  "druid|beast spells": "phbdrdBeastSpell",
  "druid|druidic": "phbdrdDruidic000",
  "druid|elemental fury": "phbdrdElementalF",
  "druid|elemental fury: potent spellcasting": "phbFuryPotentSpe",
  "druid|elemental fury: primal strike": "phbFuryPrimalStr",
  "druid|epic boon": "phbdrdEpicBoon00",
  "druid|improved elemental fury": "phbdrdImprovedEl",
  "druid|primal order": "phbdrdPrimalOrde",
  "druid|primal order: magician": "phbPrimalOrderMa",
  "druid|primal order: warden": "phbPrimalOrderWa",
  "druid|spellcasting": "phbdrdSpellcasti",
  "druid|wild companion": "phbdrdWildCompan",
  "druid|wild resurgence": "phbdrdWildResurg",
  "druid|wild shape": "phbdrdWildShape0",
  "fighter|action surge": "phbftrActionSurg",
  "fighter|epic boon": "phbftrEpicBoon00",
  "fighter|extra attack": "phbftrExtraAttac",
  "fighter|fighting style": "phbftrFightingSt",
  "fighter|indomitable": "phbftrIndomitabl",
  "fighter|second wind": "phbftrSecondWind",
  "fighter|studied attacks": "phbftrStudiedAtt",
  "fighter|tactical master": "phbftrTacticalMa",
  "fighter|tactical mind": "phbftrTacticalMi",
  "fighter|tactical shift": "phbftrTacticalSh",
  "fighter|three extra attacks": "phbftrThreeExtra",
  "fighter|two extra attacks": "phbftrTwoExtraAt",
  "fighter|weapon mastery": "phbftrWeaponMast",
  "monk|acrobatic movement": "phbmnkAcrobaticM",
  "monk|body and mind": "phbmnkBodyAndMin",
  "monk|deflect attacks": "phbmnkDeflectAtt",
  "monk|deflect energy": "phbmnkDeflectEne",
  "monk|disciplined survivor": "phbmnkDiscipline",
  "monk|empowered strikes": "phbmnkEmpoweredS",
  "monk|epic boon": "phbmnkEpicBoon00",
  "monk|evasion": "phbmnkEvasion000",
  "monk|extra attack": "phbmnkExtraAttac",
  "monk|heightened focus": "phbmnkHeightened",
  "monk|martial arts": "phbmnkMartialArt",
  "monk|monk's focus": "phbmnkMonksFocus",
  "monk|perfect focus": "phbmnkPerfectFoc",
  "monk|self-restoration": "phbmnkSelfrestor",
  "monk|slow fall": "phbmnkSlowFall00",
  "monk|stunning strike": "phbmnkStunningSt",
  "monk|superior defense": "phbmnkSuperiorDe",
  "monk|unarmored defense": "phbmnkUnarmoredD",
  "monk|unarmored movement": "phbmnkUnarmoredM",
  "monk|uncanny metabolism": "phbmnkUncannyMet",
  "paladin|abjure foes": "phbpdnAbjureFoes",
  "paladin|aura expansion": "phbpdnAuraExpans",
  "paladin|aura of courage": "phbpdnCourageAur",
  "paladin|aura of protection": "phbpdnProtection",
  "paladin|blessed warrior": "phbfstBlessedWar",
  "paladin|channel divinity": "phbpdnChannelDiv",
  "paladin|epic boon": "phbpdnEpicBoon00",
  "paladin|extra attack": "phbpdnExtraAttac",
  "paladin|faithful steed": "phbpdnFaithfulSt",
  "paladin|fighting style": "phbpdnFightingSt",
  "paladin|lay on hands": "phbpdnLayOnHands",
  "paladin|paladin's smite": "phbpdnPaladinsSm",
  "paladin|radiant strikes": "phbpdnRadiantStr",
  "paladin|restoring touch": "phbpdnRestoringT",
  "paladin|spellcasting": "phbpdnSpellcasti",
  "paladin|weapon mastery": "phbpdnWeaponMast",
  "ranger|deft explorer": "phbrgrDeftExplor",
  "ranger|druidic warrior": "phbfstDruidicWar",
  "ranger|epic boon": "phbrgrEpicBoon00",
  "ranger|expertise": "phbrgrExpertise0",
  "ranger|extra attack": "phbrgrExtraAttac",
  "ranger|favored enemy": "phbrgrFavoredEne",
  "ranger|feral senses": "phbrgrFeralSense",
  "ranger|fighting style": "phbrgrFightingSt",
  "ranger|foe slayer": "phbrgrFoeSlayer0",
  "ranger|nature's veil": "phbrgrNaturesVei",
  "ranger|precise hunter": "phbrgrPreciseHun",
  "ranger|relentless hunter": "phbrgrRelentless",
  "ranger|roving": "phbrgrRoving0000",
  "ranger|spellcasting": "phbrgrSpellcasti",
  "ranger|tireless": "phbrgrTireless00",
  "ranger|weapon mastery": "phbrgrWeaponMast",
  "rogue|cunning action": "phbrgeCunningAct",
  "rogue|cunning strike": "phbrgeCunningStr",
  "rogue|devious strikes": "phbrgeDeviousStr",
  "rogue|elusive": "phbrgeElusive000",
  "rogue|epic boon": "phbrgeEpicBoon00",
  "rogue|evasion": "phbrgeEvasion000",
  "rogue|expertise": "phbrgeExpertise0",
  "rogue|improved cunning strike": "phbrgeImprovedCu",
  "rogue|reliable talent": "phbrgeReliableTa",
  "rogue|slippery mind": "phbrgeSlipperyMi",
  "rogue|sneak attack": "phbrgeSneakAttac",
  "rogue|steady aim": "phbrgeSteadyAim0",
  "rogue|stroke of luck": "phbrgeStrokeOfLu",
  "rogue|thieves' cant": "phbrgeThievesCan",
  "rogue|uncanny dodge": "phbrgeUncannyDod",
  "rogue|weapon mastery": "phbrgeWeaponMast",
  "sorcerer|arcane apotheosis": "phbscrArcaneApot",
  "sorcerer|careful spell": "phbmmoCarefulSpe",
  "sorcerer|distant spell": "phbmmoDistantSpe",
  "sorcerer|empowered spell": "phbmmoEmpoweredS",
  "sorcerer|epic boon": "phbscrEpicBoon00",
  "sorcerer|extended spell": "phbmmoExtendedSp",
  "sorcerer|font of magic": "phbscrFontOfMagi",
  "sorcerer|heightened spell": "phbmmoHeightened",
  "sorcerer|innate sorcery": "phbscrInnateSorc",
  "sorcerer|metamagic": "phbscrMetamagic0",
  "sorcerer|quickened spell": "phbmmoQuickenedS",
  "sorcerer|seeking spell": "phbmmoSeekingSpe",
  "sorcerer|sorcerous restoration": "phbscrSorcerousR",
  "sorcerer|sorcery incarnate": "phbscrSorceryInc",
  "sorcerer|spellcasting": "phbscrSpellcasti",
  "sorcerer|subtle spell": "phbmmoSubtleSpel",
  "sorcerer|transmuted spell": "phbmmoTransmuted",
  "sorcerer|twinned spell": "phbmmoTwinnedSpe",
  "warlock|agonizing blast": "phbinvAgonizingB",
  "warlock|armor of shadows": "phbinvArmorofSha",
  "warlock|ascendant step": "phbinvAscendantS",
  "warlock|contact patron": "phbwlkContactPat",
  "warlock|devil's sight": "phbinvDevilsSigh",
  "warlock|devouring blade": "phbinvDevouringB",
  "warlock|eldritch invocations": "phbwlkEldritchIn",
  "warlock|eldritch master": "phbwlkEldritchMa",
  "warlock|eldritch mind": "phbinvEldritchMi",
  "warlock|eldritch smite": "phbinvEldritchSm",
  "warlock|eldritch spear": "phbinvEldritchSp",
  "warlock|epic boon": "phbwlkEpicBoon00",
  "warlock|fiendish vigor": "phbinvFiendishVi",
  "warlock|gaze of two minds": "phbinvGazeofTwoM",
  "warlock|gift of the depths": "phbinvGiftoftheD",
  "warlock|gift of the protectors": "phbinvGiftoftheP",
  "warlock|investment of the chain master": "phbinvInvestment",
  "warlock|lessons of the first ones": "phbinvLessonsoft",
  "warlock|lifedrinker": "phbinvLifedrinke",
  "warlock|magical cunning": "phbwlkMagicalCun",
  "warlock|mask of many faces": "phbinvMaskofMany",
  "warlock|master of myriad forms": "phbinvMasterofMy",
  "warlock|misty visions": "phbinvMistyVisio",
  "warlock|mystic arcanum": "phbwlkMysticArca",
  "warlock|one with shadows": "phbinvOnewithSha",
  "warlock|otherworldly leap": "phbinvOtherworld",
  "warlock|pact magic": "phbwlkPactMagic0",
  "warlock|pact of the blade": "phbinvPactBlade0",
  "warlock|pact of the chain": "phbinvPactChain0",
  "warlock|pact of the tome": "phbinvPactTome00",
  "warlock|repelling blast": "phbinvRepellingB",
  "warlock|thirsting blade": "phbinvThirstingB",
  "warlock|visions of distant realms": "phbinvVisionsOfD",
  "warlock|whispers of the grave": "phbinvWhispersOf",
  "warlock|witch sight": "phbinvWitchSight",
  "wizard|arcane recovery": "phbwzdArcaneReco",
  "wizard|epic boon": "phbwzdEpicBoon00",
  "wizard|memorize spell": "phbwzdMemorizeSp",
  "wizard|ritual adept": "phbwzdRitualAdep",
  "wizard|scholar": "phbwzdScholar000",
  "wizard|signature spells": "phbwzdSignatureS",
  "wizard|spell mastery": "phbwzdSpellMaste",
  "wizard|spellcasting": "phbwzdSpellcasti",
};

/** `classId|nomeDaSubclasse` → _id (pacote classes24). */
export const SUBCLASS_IDS = {
  "barbarian|path of the berserker": "phbbrbBerserker0",
  "bard|college of lore": "phbbrdLore000000",
  "cleric|life domain": "phbclcLifeDomain",
  "druid|circle of the land": "phbdrdCirland000",
  "fighter|champion": "phbftrChampion00",
  "monk|warrior of the open hand": "phbmnkOpenHandWa",
  "paladin|oath of devotion": "phbpdnOathOfDevo",
  "ranger|hunter": "phbrgrHunter0000",
  "rogue|thief": "phbrgeThief00000",
  "sorcerer|draconic sorcery": "phbscrDraconicSo",
  "warlock|fiend patron": "phbwlkFiendPatro",
  "wizard|evoker": "phbwzdEvoker0000",
};

/** `classId|nomeDaSubclasse` → `system.identifier` do SRD. Não é derivável do
 *  nome ("Warrior of the Open Hand" → `hand`) e é referenciado em FÓRMULA pelo
 *  dnd5e (`@subclasses.hand.levels`), então vale mais que um rótulo (TC-0074). */
export const SUBCLASS_IDENTIFIERS = {
  "barbarian|path of the berserker": "berserker",
  "bard|college of lore": "lore",
  "cleric|life domain": "life",
  "druid|circle of the land": "land",
  "fighter|champion": "champion",
  "monk|warrior of the open hand": "hand",
  "paladin|oath of devotion": "devotion",
  "ranger|hunter": "hunter",
  "rogue|thief": "thief",
  "sorcerer|draconic sorcery": "draconic",
  "warlock|fiend patron": "fiend",
  "wizard|evoker": "evoker",
};

/** `classId|nomeDaSubclasse|nomeDaFeature` → _id (pacote classes24). */
export const SUBCLASS_FEATURE_IDS = {
  "barbarian|path of the berserker|frenzy": "phbbrbFrenzy0000",
  "barbarian|path of the berserker|intimidating presence": "phbbrbIntimidati",
  "barbarian|path of the berserker|mindless rage": "phbbrbMindlessRa",
  "barbarian|path of the berserker|retaliation": "phbbrbRetaliatio",
  "bard|college of lore|bonus proficiencies": "phbbrdBonusProfi",
  "bard|college of lore|cutting words": "phbbrdCuttingWor",
  "bard|college of lore|magical discoveries": "phbbrdMagicalDis",
  "bard|college of lore|peerless skill": "phbbrdPeerlessSk",
  "cleric|life domain|blessed healer": "phbclcBlessedHea",
  "cleric|life domain|disciple of life": "phbclcDiscipleOf",
  "cleric|life domain|life domain spells": "phbclcLifeSpells",
  "cleric|life domain|preserve life": "phbclcPreserveLi",
  "cleric|life domain|supreme healing": "phbclcSupremeHea",
  "druid|circle of the land|circle of the land spells": "phbdrdLandSpells",
  "druid|circle of the land|land's aid": "phbdrdLandsAid00",
  "druid|circle of the land|natural recovery": "phbdrdNaturalRec",
  "druid|circle of the land|nature's sanctuary": "phbdrdNaturesSan",
  "druid|circle of the land|nature's ward": "phbdrdNaturesWar",
  "fighter|champion|additional fighting style": "phbftrAdditional",
  "fighter|champion|heroic warrior": "phbftrHeroicWarr",
  "fighter|champion|improved critical": "phbftrImprovedCr",
  "fighter|champion|remarkable athlete": "phbftrRemarkable",
  "fighter|champion|superior critical": "phbftrSuperiorCr",
  "fighter|champion|survivor": "phbftrSurvivor00",
  "monk|warrior of the open hand|fleet step": "phbmnkFleetStep0",
  "monk|warrior of the open hand|open hand technique": "phbmnkOpenHandTe",
  "monk|warrior of the open hand|quivering palm": "phbmnkQuiveringP",
  "monk|warrior of the open hand|wholeness of body": "phbmnkWholenessO",
  "paladin|oath of devotion|aura of devotion": "phbpdnDevotionAu",
  "paladin|oath of devotion|holy nimbus": "phbpdnHolyNimbus",
  "paladin|oath of devotion|oath of devotion spells": "phbpdnDevotionSp",
  "paladin|oath of devotion|sacred weapon": "phbpdnSacredWeap",
  "paladin|oath of devotion|smite of protection": "phbpdnSmiteOfPro",
  "ranger|hunter|defensive tactics": "phbrgrDefensiveT",
  "ranger|hunter|hunter's lore": "phbrgrHuntersLor",
  "ranger|hunter|hunter's prey": "phbrgrHuntersPre",
  "ranger|hunter|superior hunter's defense": "phbrgrSuperiorDe",
  "ranger|hunter|superior hunter's prey": "phbrgrSuperiorHu",
  "rogue|thief|fast hands": "phbrgeFastHands0",
  "rogue|thief|second-story work": "phbrgeSecondstor",
  "rogue|thief|supreme sneak": "phbrgeSupremeSne",
  "rogue|thief|thief's reflexes": "phbrgeThiefsRefl",
  "rogue|thief|use magic device": "phbrgeUseMagicDe",
  "sorcerer|draconic sorcery|draconic resilience": "phbscrDraconicRe",
  "sorcerer|draconic sorcery|draconic spells": "phbscrDraconicSp",
  "sorcerer|draconic sorcery|dragon companion": "phbscrDragonComp",
  "sorcerer|draconic sorcery|dragon wings": "phbscrDragonWing",
  "sorcerer|draconic sorcery|elemental affinity": "phbscrElementalA",
  "warlock|fiend patron|dark one's blessing": "phbwlkDarkOnesBl",
  "warlock|fiend patron|dark one's own luck": "phbwlkDarkOnesOw",
  "warlock|fiend patron|fiend spells": "phbwlkFiendSpell",
  "warlock|fiend patron|fiendish resilience": "phbwlkFiendishRe",
  "warlock|fiend patron|hurl through hell": "phbwlkHurlThroug",
  "wizard|evoker|empowered evocation": "phbwzdEmpoweredE",
  "wizard|evoker|evocation savant": "phbwzdEvocationS",
  "wizard|evoker|overchannel": "phbwzdOverchanne",
  "wizard|evoker|potent cantrip": "phbwzdPotentCant",
  "wizard|evoker|sculpt spells": "phbwzdSculptSpel",
};

/** `nomeDaMagia` → _id (pacote spells24). */
export const SPELL_IDS = {
  "acid arrow": "phbsplMelfsAcidA",
  "acid splash": "phbsplAcidSplash",
  "aid": "phbsplAid0000000",
  "alarm": "phbsplAlarm00000",
  "alter self": "phbsplAlterSelf0",
  "animal friendship": "phbsplAnimalFrie",
  "animal messenger": "phbsplAnimalMess",
  "animal shapes": "phbsplAnimalShap",
  "animate dead": "phbsplAnimateDea",
  "animate objects": "phbsplAnimateObj",
  "antilife shell": "phbsplAntilifeSh",
  "antimagic field": "phbsplAntimagicF",
  "antipathy/sympathy": "phbsplAntipathyS",
  "arcane eye": "phbsplArcaneEye0",
  "arcane hand": "phbsplBigbysHand",
  "arcane lock": "phbsplArcaneLock",
  "arcane sword": "phbswdMordenkain",
  "arcane vigor": "phbsplArcaneVigo",
  "arcanist's magic aura": "phbsplNystulsMag",
  "astral projection": "phbsplAstralProj",
  "augury": "phbsplAugury0000",
  "aura of life": "phbsplAuraofLife",
  "awaken": "phbsplAwaken0000",
  "bane": "phbsplBane000000",
  "banishment": "phbsplBanishment",
  "barkskin": "phbsplBarkskin00",
  "beacon of hope": "phbsplBeaconofHo",
  "befuddlement": "phbsplBefuddleme",
  "bestow curse": "phbsplBestowCurs",
  "black tentacles": "phbsplEvardsBlac",
  "blade barrier": "phbsplBladeBarri",
  "bless": "phbsplBless00000",
  "blight": "phbsplBlight0000",
  "blindness/deafness": "phbsplBlindnessD",
  "blink": "phbsplBlink00000",
  "blur": "phbsplBlur000000",
  "burning hands": "phbsplBurningHan",
  "call lightning": "phbsplCallLightn",
  "calm emotions": "phbsplCalmEmotio",
  "chain lightning": "phbsplChainLight",
  "charm monster": "phbsplCharmMonst",
  "charm person": "phbsplCharmPerso",
  "chill touch": "phbsplChillTouch",
  "chromatic orb": "phbsplChromaticO",
  "circle of death": "phbsplCircleofDe",
  "clairvoyance": "phbsplClairvoyan",
  "clone": "phbsplClone00000",
  "cloudkill": "phbsplCloudkill0",
  "color spray": "phbsplColorSpray",
  "command": "phbsplCommand000",
  "commune": "phbsplCommune000",
  "commune with nature": "phbsplCommunewit",
  "comprehend languages": "phbsplComprehend",
  "compulsion": "phbsplCompulsion",
  "cone of cold": "phbsplConeofCold",
  "confusion": "phbsplConfusion0",
  "conjure animals": "phbsplConjureAni",
  "conjure celestial": "phbsplConjureCel",
  "conjure elemental": "phbsplConjureEle",
  "conjure fey": "phbsplConjureFey",
  "conjure minor elementals": "phbsplConjureMin",
  "conjure woodland beings": "phbsplConjureWoo",
  "contact other plane": "phbsplContactOth",
  "contagion": "phbsplContagion0",
  "contingency": "phbsplContingenc",
  "continual flame": "phbsplContinualF",
  "control water": "phbsplControlWat",
  "control weather": "phbsplControlWea",
  "counterspell": "phbsplCounterspe",
  "create food and water": "phbsplCreateFood",
  "create or destroy water": "phbsplCreateorDe",
  "create undead": "phbsplCreateUnde",
  "creation": "phbsplCreation00",
  "cure wounds": "phbsplCureWounds",
  "dancing lights": "phbsplDancingLig",
  "darkness": "phbsplDarkness00",
  "darkvision": "phbsplDarkvision",
  "daylight": "phbsplDaylight00",
  "death ward": "phbsplDeathWard0",
  "delayed blast fireball": "phbsplDelayedBla",
  "demiplane": "phbsplDemiplane0",
  "detect evil and good": "phbsplDetectEvil",
  "detect magic": "phbsplDetectMagi",
  "detect poison and disease": "phbsplDetectPois",
  "detect thoughts": "phbsplDetectThou",
  "dimension door": "phbsplDimensionD",
  "disguise self": "phbsplDisguiseSe",
  "disintegrate": "phbsplDisintegra",
  "dispel evil and good": "phbsplDispelEvil",
  "dispel magic": "phbsplDispelMagi",
  "dissonant whispers": "phbsplDissonantW",
  "divination": "phbsplDivination",
  "divine favor": "phbsplDivineFavo",
  "divine smite": "phbsplDivineSmit",
  "divine word": "phbsplDivineWord",
  "dominate beast": "phbsplDominateBe",
  "dominate monster": "phbsplDominateMo",
  "dominate person": "phbsplDominatePe",
  "dragon's breath": "phbsplDragonsBre",
  "dream": "phbsplDream00000",
  "druidcraft": "phbsplDruidcraft",
  "earthquake": "phbsplEarthquake",
  "eldritch blast": "phbsplEldritchBl",
  "elementalism": "phbsplElementali",
  "enhance ability": "phbsplEnhanceAbi",
  "enlarge/reduce": "phbsplEnlargeRed",
  "ensnaring strike": "phbsplEnsnaringS",
  "entangle": "phbsplEntangle00",
  "enthrall": "phbsplEnthrall00",
  "etherealness": "phbsplEtherealne",
  "expeditious retreat": "phbsplExpeditiou",
  "eyebite": "phbsplEyebite000",
  "fabricate": "phbsplFabricate0",
  "faerie fire": "phbsplFaerieFire",
  "faithful hound": "phbFaithfulHound",
  "false life": "phbsplFalseLife0",
  "fear": "phbsplFear000000",
  "feather fall": "phbsplFeatherFal",
  "find familiar": "phbsplFindFamili",
  "find steed": "phbsplFindSteed0",
  "find the path": "phbsplFindthePat",
  "find traps": "phbsplFindTraps0",
  "finger of death": "phbsplFingerofDe",
  "fire bolt": "phbsplFireBolt00",
  "fire shield": "phbsplFireShield",
  "fire storm": "phbsplFireStorm0",
  "fireball": "phbsplFireball00",
  "flame blade": "phbsplFlameBlade",
  "flame strike": "phbsplFlameStrik",
  "flaming sphere": "phbsplFlamingSph",
  "flesh to stone": "phbsplFleshtoSto",
  "floating disk": "phbsplTensersFlo",
  "fly": "phbsplFly0000000",
  "fog cloud": "phbsplFogCloud00",
  "forbiddance": "phbsplForbiddanc",
  "forcecage": "phbsplForcecage0",
  "foresight": "phbsplForesight0",
  "freedom of movement": "phbsplFreedomofM",
  "freezing sphere": "phbsplOtilukesFr",
  "gaseous form": "phbsplGaseousFor",
  "gate": "phbsplGate000000",
  "geas": "phbsplGeas000000",
  "gentle repose": "phbsplGentleRepo",
  "giant insect": "phbsplGiantInsec",
  "glibness": "phbsplGlibness00",
  "globe of invulnerability": "phbsplGlobeofInv",
  "glyph of warding": "phbsplGlyphofWar",
  "goodberry": "phbsplGoodberry0",
  "grease": "phbsplGrease0000",
  "greater invisibility": "phbsplGreaterInv",
  "greater restoration": "phbsplGreaterRes",
  "guardian of faith": "phbsplGuardianof",
  "guards and wards": "phbsplGuardsandW",
  "guidance": "phbsplGuidance00",
  "guiding bolt": "phbsplGuidingBol",
  "gust of wind": "phbsplGustofWind",
  "hallow": "phbsplHallow0000",
  "hallucinatory terrain": "phbsplHallucinat",
  "harm": "phbsplHarm000000",
  "haste": "phbsplHaste00000",
  "heal": "phbsplHeal000000",
  "healing word": "phbsplHealingWor",
  "heat metal": "phbsplHeatMetal0",
  "hellish rebuke": "phbsplHellishReb",
  "heroes' feast": "phbsplHeroesFeas",
  "heroism": "phbsplHeroism000",
  "hex": "phbsplHex0000000",
  "hideous laughter": "phbsplTashasHide",
  "hold monster": "phbsplHoldMonste",
  "hold person": "phbsplHoldPerson",
  "holy aura": "phbsplHolyAura00",
  "hunter's mark": "phbsplHuntersMar",
  "hypnotic pattern": "phbsplHypnoticPa",
  "ice knife": "phbsplIceKnife00",
  "ice storm": "phbsplIceStorm00",
  "identify": "phbsplIdentify00",
  "illusory script": "phbsplIllusorySc",
  "imprisonment": "phbsplImprisonme",
  "incendiary cloud": "phbsplIncendiary",
  "inflict wounds": "phbsplInflictWou",
  "insect plague": "phbsplInsectPlag",
  "instant summons": "phbsplDrawmijsIn",
  "invisibility": "phbsplInvisibili",
  "irresistible dance": "phbsplOttosIrres",
  "jump": "phbsplJump000000",
  "knock": "phbsplKnock00000",
  "legend lore": "phbsplLegendLore",
  "lesser restoration": "phbsplLesserRest",
  "levitate": "phbsplLevitate00",
  "light": "phbsplLight00000",
  "lightning bolt": "phbsplLightningB",
  "locate animals or plants": "phbsplLocateAnim",
  "locate creature": "phbsplLocateCrea",
  "locate object": "phbsplLocateObje",
  "longstrider": "phbsplLongstride",
  "mage armor": "phbsplMageArmor0",
  "mage hand": "phbsplMageHand00",
  "magic circle": "phbsplMagicCircl",
  "magic jar": "phbsplMagicJar00",
  "magic missile": "phbsplMagicMissi",
  "magic mouth": "phbsplMagicMouth",
  "magic weapon": "phbsplMagicWeapo",
  "magnificent mansion": "phbMagnificentMa",
  "major image": "phbsplMajorImage",
  "mass cure wounds": "phbsplMassCureWo",
  "mass heal": "phbsplMassHeal00",
  "mass healing word": "phbsplMassHealin",
  "mass suggestion": "phbsplMassSugges",
  "maze": "phbsplMaze000000",
  "meld into stone": "phbsplMeldintoSt",
  "mending": "phbsplMending000",
  "message": "phbsplMessage000",
  "meteor swarm": "phbsplMeteorSwar",
  "mind blank": "phbsplMindBlank0",
  "mind spike": "phbsplMindSpike0",
  "minor illusion": "phbsplMinorIllus",
  "mirage arcane": "phbsplMirageArca",
  "mirror image": "phbsplMirrorImag",
  "mislead": "phbsplMislead000",
  "misty step": "phbsplMistyStep0",
  "modify memory": "phbsplModifyMemo",
  "moonbeam": "phbsplMoonbeam00",
  "move earth": "phbsplMoveEarth0",
  "nondetection": "phbsplNondetecti",
  "pass without trace": "phbsplPasswithou",
  "passwall": "phbsplPasswall00",
  "phantasmal force": "phbPhantasmalFor",
  "phantasmal killer": "phbsplPhantasmal",
  "phantom steed": "phbsplPhantomSte",
  "planar ally": "phbsplPlanarAlly",
  "planar binding": "phbsplPlanarBind",
  "plane shift": "phbsplPlaneShift",
  "plant growth": "phbsplPlantGrowt",
  "poison spray": "phbsplPoisonSpra",
  "polymorph": "phbsplPolymorph0",
  "power word heal": "phbsplPowerWordH",
  "power word kill": "phbsplPowerWordK",
  "power word stun": "phbsplPowerWordS",
  "prayer of healing": "phbsplPrayerofHe",
  "prestidigitation": "phbsplPrestidigi",
  "prismatic spray": "phbsplPrismaticS",
  "prismatic wall": "phbsplPrismaticW",
  "private sanctum": "phbPrivateSanctu",
  "produce flame": "phbsplProduceFla",
  "programmed illusion": "phbsplProgrammed",
  "project image": "phbsplProjectIma",
  "protection from energy": "phbProtectionFro",
  "protection from evil and good": "phbEvilAndGoodPr",
  "protection from poison": "phbsplProtection",
  "purify food and drink": "phbsplPurifyFood",
  "raise dead": "phbsplRaiseDead0",
  "ray of enfeeblement": "phbsplRayofEnfee",
  "ray of frost": "phbsplRayofFrost",
  "ray of sickness": "phbsplRayofSickn",
  "regenerate": "phbsplRegenerate",
  "reincarnate": "phbsplReincarnat",
  "remove curse": "phbsplRemoveCurs",
  "resilient sphere": "phbsplOtilukesRe",
  "resistance": "phbsplResistance",
  "resurrection": "phbsplResurrecti",
  "reverse gravity": "phbsplReverseGra",
  "revivify": "phbsplRevivify00",
  "rope trick": "phbsplRopeTrick0",
  "sacred flame": "phbsplSacredFlam",
  "sanctuary": "phbSanctuary0000",
  "scorching ray": "phbsplScorchingR",
  "scrying": "phbsplScrying000",
  "searing smite": "phbsplSearingSmi",
  "secret chest": "phbsplLeomundsSe",
  "see invisibility": "phbsplSeeInvisib",
  "seeming": "phbsplSeeming000",
  "sending": "phbsplSending000",
  "sequester": "phbsplSequester0",
  "shapechange": "phbsplShapechang",
  "shatter": "phbsplShatter000",
  "shield": "phbsplShield0000",
  "shield of faith": "phbsplShieldofFa",
  "shillelagh": "phbsplShillelagh",
  "shining smite": "phbsplShiningSmi",
  "shocking grasp": "phbsplShockingGr",
  "silence": "phbsplSilence000",
  "silent image": "phbsplSilentImag",
  "simulacrum": "phbsplSimulacrum",
  "sleep": "phbsplSleep00000",
  "sleet storm": "phbsplSleetStorm",
  "slow": "phbsplSlow000000",
  "sorcerous burst": "phbsplSorcerousB",
  "spare the dying": "phbsplSparetheDy",
  "speak with animals": "phbsplSpeakwithA",
  "speak with dead": "phbsplSpeakwithD",
  "speak with plants": "phbsplSpeakwithP",
  "spider climb": "phbsplSpiderClim",
  "spike growth": "phbsplSpikeGrowt",
  "spirit guardians": "phbsplSpiritGuar",
  "spiritual weapon": "phbsplSpiritualW",
  "starry wisp": "phbsplStarryWisp",
  "stinking cloud": "phbsplStinkingCl",
  "stone shape": "phbsplStoneShape",
  "stoneskin": "phbsplStoneskin0",
  "storm of vengeance": "phbsplStormofVen",
  "suggestion": "phbsplSuggestion",
  "summon dragon": "phbsplSummonDrag",
  "sunbeam": "phbsplSunbeam000",
  "sunburst": "phbsplSunburst00",
  "symbol": "phbsplSymbol0000",
  "telekinesis": "phbsplTelekinesi",
  "telepathic bond": "phbsplRarysTelep",
  "teleport": "phbsplTeleport00",
  "teleportation circle": "phbsplTeleportat",
  "thaumaturgy": "phbsplThaumaturg",
  "thunderwave": "phbsplThunderwav",
  "time stop": "phbsplTimeStop00",
  "tiny hut": "phbsplLeomundsTi",
  "tongues": "phbsplTongues000",
  "transport via plants": "phbsplTransportv",
  "tree stride": "phbsplTreeStride",
  "true polymorph": "phbsplTruePolymo",
  "true resurrection": "phbsplTrueResurr",
  "true seeing": "phbsplTrueSeeing",
  "true strike": "phbsplTrueStrike",
  "tsunami": "phbsplTsunami000",
  "unseen servant": "phbsplUnseenServ",
  "vampiric touch": "phbsplVampiricTo",
  "vicious mockery": "phbsplViciousMoc",
  "vitriolic sphere": "phbsplVitriolicS",
  "wall of fire": "phbsplWallofFire",
  "wall of force": "phbsplWallofForc",
  "wall of ice": "phbsplWallofIce0",
  "wall of stone": "phbsplWallofSton",
  "wall of thorns": "phbsplWallofThor",
  "warding bond": "phbsplWardingBon",
  "water breathing": "phbsplWaterBreat",
  "water walk": "phbsplWaterWalk0",
  "web": "phbsplWeb0000000",
  "weird": "phbsplWeird00000",
  "wind walk": "phbsplWindWalk00",
  "wind wall": "phbsplWindWall00",
  "wish": "phbsplWish000000",
  "word of recall": "phbsplWordofReca",
  "zone of truth": "phbsplZoneofTrut",
};

/** `nome` → _id (pacote origins24: espécies, seus traços e backgrounds). */
export const ORIGIN_IDS = {
  "acolyte": "phbbgAcolyte0000",
  "adrenaline rush": "phbsptAdrenaline",
  "brave": "phbsptBrave00000",
  "breath weapon": "phbsptBreathWeap",
  "cloud's jaunt": "phbsptCloudsJaun",
  "criminal": "phbbgCriminal000",
  "draconic flight": "phbsptDraconicFl",
  "dragonborn": "phbspDragonborn0",
  "dwarf": "phbspDwarf000000",
  "dwarven resilience": "phbsptDwarvenRes",
  "dwarven toughness": "phbsptDwarvenTou",
  "elf, drow": "phbspDrow0000000",
  "elf, high": "phbspHighElf0000",
  "elf, wood": "phbspWoodElf0000",
  "elven lineage, drow": "phbsptDrowElfLin",
  "elven lineage, high elf": "phbsptHighElfLin",
  "elven lineage, wood elf": "phbsptWoodElfLin",
  "fey ancestry": "phbsptFeyAncestr",
  "fiendish legacy, abyssal": "phbsptAbyssalLeg",
  "fiendish legacy, chthonic": "phbsptChthonicLe",
  "fiendish legacy, infernal": "phbsptInfernalLe",
  "fire's burn": "phbsptFiresBurn0",
  "frost's chill": "phbsptFrostsChil",
  "giant ancestry": "phbsptGiantAnces",
  "gnome, forest": "phbspForestGnome",
  "gnome, rock": "phbspRockGnome00",
  "gnomish cunning": "phbsptGnomishCun",
  "gnomish lineage, forest": "phbsptForestGnom",
  "gnomish lineage, rock": "phbsptRockGnomeL",
  "goliath": "phbspGoliath0000",
  "halfling": "phbspHalfling000",
  "halfling nimbleness": "phbsptHalflingNi",
  "hill's tumble": "phbsptHillsTumbl",
  "human": "phbspHuman000000",
  "keen senses": "phbsptKeenSenses",
  "large form": "phbsptLargeForm0",
  "luck": "phbsptLuck000000",
  "naturally stealthy": "phbsptNaturallyS",
  "orc": "phbspOrc00000000",
  "otherworldly presence": "phbsptOtherworld",
  "powerful build": "phbsptPowerfulBu",
  "relentless endurance": "phbsptRelentless",
  "resourceful": "phbsptResourcefu",
  "sage": "phbbgSage0000000",
  "skillful": "phbsptSkillful00",
  "soldier": "phbbgSoldier0000",
  "stone's endurance": "phbsptStonesEndu",
  "stonecunning": "phbsptStonecunni",
  "storm's thunder": "phbsptStormsThun",
  "tiefling, abyssal": "phbspAbyssalTief",
  "tiefling, chthonic": "phbspChthonicTie",
  "tiefling, infernal": "phbspInfernalTie",
  "trance": "phbsptTrance0000",
  "versatile": "phbsptVersatile0",
};

/** Nomes das ESPÉCIES publicadas (documentos `race` do origins24), na grafia do
 *  dnd5e - "Elf, High" onde o 5etools diz "Elf; High Elf Lineage". Ver
 *  engine/compendiumUuids.js `srdSpeciesName`. */
export const SPECIES_NAMES = [
  "Dragonborn",
  "Dwarf",
  "Elf, Drow",
  "Elf, High",
  "Elf, Wood",
  "Gnome, Forest",
  "Gnome, Rock",
  "Goliath",
  "Halfling",
  "Human",
  "Orc",
  "Tiefling, Abyssal",
  "Tiefling, Chthonic",
  "Tiefling, Infernal"
];

/** Espécies cujo documento do SRD guarda a LINHAGEM dentro de si (um passo
 *  `ItemChoice`, ou um `Trait` com pool de escolha): ali "Dragonborn" é a
 *  espécie INTEIRA, ancestralidade inclusa, então uma linhagem nossa pode herdar
 *  o nome e a procedência do documento. Onde o SRD não faz isso, as nossas
 *  linhagens são acréscimo curado (o guarda-chuva do Halfling, DDL-0063) e
 *  apontar para o documento publicado seria um near-match - o Foundry ofereceria
 *  "atualizar do compêndio" e trocaria a linhagem escolhida pela base. */
export const SPECIES_SELF_LINEAGE = [
  "Dragonborn",
  "Goliath"
];

/** Nomes de TODO documento do origins24 (espécies, traços de espécie, origens),
 *  na grafia do dnd5e. Ver engine/compendiumUuids.js `srdOriginName`. */
export const ORIGIN_NAMES = [
  "Acolyte",
  "Adrenaline Rush",
  "Brave",
  "Breath Weapon",
  "Cloud's Jaunt",
  "Criminal",
  "Draconic Flight",
  "Dragonborn",
  "Dwarf",
  "Dwarven Resilience",
  "Dwarven Toughness",
  "Elf, Drow",
  "Elf, High",
  "Elf, Wood",
  "Elven Lineage, Drow",
  "Elven Lineage, High Elf",
  "Elven Lineage, Wood Elf",
  "Fey Ancestry",
  "Fiendish Legacy, Abyssal",
  "Fiendish Legacy, Chthonic",
  "Fiendish Legacy, Infernal",
  "Fire's Burn",
  "Frost's Chill",
  "Giant Ancestry",
  "Gnome, Forest",
  "Gnome, Rock",
  "Gnomish Cunning",
  "Gnomish Lineage, Forest",
  "Gnomish Lineage, Rock",
  "Goliath",
  "Halfling",
  "Halfling Nimbleness",
  "Hill's Tumble",
  "Human",
  "Keen Senses",
  "Large Form",
  "Luck",
  "Naturally Stealthy",
  "Orc",
  "Otherworldly Presence",
  "Powerful Build",
  "Relentless Endurance",
  "Resourceful",
  "Sage",
  "Skillful",
  "Soldier",
  "Stone's Endurance",
  "Stonecunning",
  "Storm's Thunder",
  "Tiefling, Abyssal",
  "Tiefling, Chthonic",
  "Tiefling, Infernal",
  "Trance",
  "Versatile"
];

/** `nomeDoTalento` → _id (pacote feats24). */
export const FEAT_IDS = {
  "ability score improvement": "phbftAbilityScor",
  "alert": "phbftAlert000000",
  "archery": "phbfstArchery000",
  "boon of combat prowess": "phbBoonofCombatP",
  "boon of dimensional travel": "phbBoonofDimensi",
  "boon of fate": "phbBoonofFate000",
  "boon of irresistible offense": "phbBoonofIrresis",
  "boon of spell recall": "phbBoonofSpellRe",
  "boon of the night spirit": "phbBoonoftheNigh",
  "boon of truesight": "phbBoonofTruesig",
  "defense": "phbfstDefense000",
  "grappler": "phbftGrappler000",
  "great weapon fighting": "phbfstGreatWeapo",
  "magic initiate": "phbftMagicInitia",
  "savage attacker": "phbftSavageAttac",
  "skilled": "phbftSkilled0000",
  "two-weapon fighting": "phbfstTwoWeaponF",
};

/** `nomeDoItem` → _id (pacote equipment24). */
export const EQUIPMENT_IDS = {
  "acid": "phbagAcid0000000",
  "activate folding boat": "dmgBoatUtility00",
  "adamantine armor": "dmgAdamantineArm",
  "air ring of elemental command": "dmgAirRingOfElem",
  "alchemist's fire": "phbagAlchemistsF",
  "alchemist's supplies": "phbtulAlchemists",
  "ammunition (varies)": "phbagAmmunitionV",
  "ammunition of slaying": "dmgSlayingAmmuni",
  "ammunition, +1, +2, or +3": "dmgAmmunition12o",
  "amulet": "phbhsyAmuletworn",
  "amulet of health": "dmgAmuletOfHealt",
  "amulet of proof against detection and location": "dmgAmuletOfProof",
  "amulet of the planes": "dmgAmuletOfThePl",
  "animated shield": "dmgAnimatedShiel",
  "antitoxin": "phbagAntitoxin00",
  "apparatus of the crab": "dmgApparatusOfKw",
  "arcane focus (varies)": "phbagArcaneFocus",
  "armor of invulnerability": "dmgArmorOfInvuln",
  "armor of resistance": "dmgArmorOfResist",
  "armor of vulnerability": "dmgArmorOfVulner",
  "armor, +1, +2, or +3": "dmgArmor12or3000",
  "arrow-catching shield": "dmgArrowcatching",
  "arrows": "phbamoArrows0000",
  "assassin's blood": "dmgAssassinsBloo",
  "backpack": "phbagBackpack000",
  "bag of beans": "dmgBagOfBeans000",
  "bag of devouring": "dmgBagOfDevourin",
  "bag of holding": "dmgBagOfHolding0",
  "bagpipes": "phbmusBagpipes00",
  "balance": "dmgDmtBalance000",
  "ball bearings": "phbagBallBearing",
  "barrel": "phbagBarrel00000",
  "basket": "phbagBasket00000",
  "battleaxe": "phbwepBattleaxe0",
  "bead of force": "dmgBeadOfForce00",
  "bead of nourishment": "dmgBeadOfNourish",
  "bedroll": "phbagBedroll0000",
  "bell": "phbagBell0000000",
  "belt of dwarvenkind": "dmgBeltOfDwarven",
  "belt of giant strength": "dmgBeltOfGiantSt",
  "belt of giant strength (cloud)": "dmgcloBeltofGian",
  "belt of giant strength (fire)": "dmgfirBeltofGian",
  "belt of giant strength (frost)": "dmgfroBeltofGian",
  "belt of giant strength (hill)": "dmghilBeltofGian",
  "belt of giant strength (stone)": "dmgstoBeltofGian",
  "belt of giant strength (storm)": "dmgstmBeltofGian",
  "berserker axe": "dmgBerserkerAxe0",
  "blanket": "phbagBlanket0000",
  "block and tackle": "phbagBlockandTac",
  "blowgun": "phbwepBlowgun000",
  "bolts": "phbamoBolts00000",
  "book": "phbagBook0000000",
  "boots of elvenkind": "dmgBootsOfElvenk",
  "boots of levitation": "dmgBootsOfLevita",
  "boots of speed": "dmgBootsOfSpeed0",
  "boots of striding and springing": "dmgBootsOfStridi",
  "boots of the winterlands": "dmgBootsOfTheWin",
  "bottle, glass": "phbagBottleGlass",
  "bowl of commanding water elementals": "dmgBowlOfCommand",
  "bracers of archery": "dmgBracersOfArch",
  "bracers of defense": "dmgBracersOfDefe",
  "brass horn of valhalla": "dmgBrassHornOfVa",
  "brazier of commanding fire elementals": "dmgBrazierOfComm",
  "breastplate": "phbarmBreastplat",
  "brewer's supplies": "phbtulBrewersSup",
  "bronze griffon": "dmgFwpBronzeGrif",
  "bronze horn of valhalla": "dmgBronzeHornOfV",
  "brooch of shielding": "dmgBroochOfShiel",
  "broom of flying": "dmgBroomOfFlying",
  "bucket": "phbagBucket00000",
  "bullets, firearm": "phbamoBulletsFir",
  "bullets, sling": "phbamoBulletsSli",
  "bullseye lantern": "KZUoiZrigDbovEu7",
  "burglar's pack": "phbagBurglarsPac",
  "burnt othur fumes": "dmgBurntOthurFum",
  "calligrapher's supplies": "phbtulCalligraph",
  "caltrops": "phbagCaltrops000",
  "candle": "ts2DfyhdfsR092Td",
  "candle of invocation": "dmgCandleOfInvoc",
  "cape of the mountebank": "dmgCapeOfTheMoun",
  "carpenter's tools": "phbtulCarpenters",
  "carpet of flying": "dmgCarpetOfFlyin",
  "cartographer's tools": "phbtulCartograph",
  "case, crossbow bolt": "phbagCaseCrossbo",
  "case, map or scroll": "phbagCaseMaporSc",
  "censer of controlling air elementals": "dmgCenserOfContr",
  "central pouch": "dmgCentralPouch0",
  "chain": "phbagChain000000",
  "chain mail": "phbarmChainMail0",
  "chain shirt": "phbarmChainShirt",
  "chest": "phbagChest000000",
  "chime of opening": "dmgChimeOfOpenin",
  "circlet of blasting": "dmgCircletOfBlas",
  "clawed gauntlet": "dmgClawedGauntle",
  "climber's kit": "phbagClimbersKit",
  "cloak of arachnida": "dmgCloakOfArachn",
  "cloak of displacement": "dmgCloakOfDispla",
  "cloak of elvenkind": "dmgCloakOfElvenk",
  "cloak of invisibility": "dmgCloakOfInvisi",
  "cloak of protection": "dmgCloakOfProtec",
  "cloak of the bat": "dmgCloakOfTheBat",
  "cloak of the manta ray": "dmgCloakOfTheMan",
  "clothes, fine": "phbagClothesFine",
  "clothes, traveler's": "phbagClothesTrav",
  "club": "phbwepClub000000",
  "cobbler's tools": "phbtulCobblersTo",
  "collapsing roof": "dmgCollapsingRoo",
  "comet": "dmgDmtComet00000",
  "component pouch": "phbagComponentPo",
  "cook's utensils": "phbtulCooksUtens",
  "costume": "phbagCostume0000",
  "crawler mucus": "dmgCarrionCrawle",
  "crowbar": "rvz6gQc3OcOMgIQz",
  "crystal": "phbafcCrystal000",
  "crystal ball": "dmgCrystalBall00",
  "crystal ball of mind reading": "dmgMindReadingCr",
  "crystal ball of telepathy": "dmgTelepathyCrys",
  "crystal ball of true seeing": "dmgTrueSeeingCry",
  "cube of force": "dmgCubeOfForce00",
  "cubic gate": "dmgCubicGate0000",
  "dagger": "phbwepDagger0000",
  "dagger of venom": "dmgDaggerOfVenom",
  "dancing sword": "dmgDancingSword0",
  "dart": "phbwepDart000000",
  "decanter of endless water": "dmgDecanterOfEnd",
  "deck of illusions": "dmgDeckOfIllusio",
  "defender": "dmgDefender00000",
  "demon armor": "dmgDemonArmor000",
  "dice": "phbgstDice000000",
  "dimensional shackles": "dmgDimensionalSh",
  "diplomat's pack": "phbagDiplomatsPa",
  "disguise kit": "phbtulDisguiseKi",
  "donjon": "dmgDmtDonjon0000",
  "dragon orb": "dmgOrbOfDragonki",
  "dragon scale mail": "dmgDragonScaleMa",
  "dragon slayer": "dmgDragonSlayer0",
  "dragonchess": "phbgstDragonches",
  "druidic focus (varies)": "phbagDruidicFocu",
  "drum": "phbmusDrum000000",
  "dulcimer": "phbmusDulcimer00",
  "dungeoneer's pack": "phbagDungeoneers",
  "dust of disappearance": "dmgDustOfDisappe",
  "dust of dryness": "dmgDustOfDryness",
  "dust of sneezing and choking": "dmgDustOfSneezin",
  "dwarven plate": "dmgDwarvenPlate0",
  "dwarven thrower": "dmgDwarvenThrowe",
  "earth ring of elemental command": "dmgEarthRingOfEl",
  "ebony fly": "dmgFwpEbonyFlyRa",
  "efficient quiver": "dmgQuiverOfEhlon",
  "efreeti bottle": "dmgEfreetiBottle",
  "elemental gem": "dmgElementalGem0",
  "elemental gem (blue sapphire)": "dmgBlueElemental",
  "elemental gem (emerald)": "dmgEmeraldElemen",
  "elemental gem (red corundum)": "dmgRedElementalG",
  "elemental gem (yellow diamond)": "dmgYellowElement",
  "elixir of health": "dmgElixirOfHealt",
  "elven chain": "dmgElvenChain000",
  "emblem": "phbhsyEmblemborn",
  "energy bow": "dmgEnergyBow0000",
  "entertainer's pack": "phbagEntertainer",
  "essence of ether": "dmgEssenceOfEthe",
  "euryale": "dmgDmtEuryale000",
  "eversmoking bottle": "dmgEversmokingBo",
  "explorer's pack": "phbagExplorersPa",
  "eyes of charming": "dmgEyesOfCharmin",
  "eyes of minute seeing": "dmgEyesOfMinuteS",
  "eyes of the eagle": "dmgEyesOfTheEagl",
  "falling net": "dmgFallingNet000",
  "fates": "dmgDmtFates00000",
  "feather token": "dmgQuaalsFeather",
  "feather token (anchor)": "dmgAnchorQuaalsF",
  "feather token (bird)": "dmgBirdQuaalsFea",
  "feather token (fan)": "dmgFanQuaalsFeat",
  "feather token (swan boat)": "dmgSwanBoatQuaal",
  "feather token (tree)": "dmgTreeQuaalsFea",
  "feather token (whip)": "dmgWhipQuaalsFea",
  "figurine of wondrous power": "dmgFigurineOfWon",
  "fine clothes": "pjxpIVbJEfOvM240",
  "fire ring of elemental command": "dmgFireRingOfEle",
  "fire-casting statue": "dmgFirecastingSt",
  "flail": "phbwepFlail00000",
  "flame tongue": "dmgFlameTongue00",
  "flames": "dmgDmtFlames0000",
  "flask": "phbagFlask000000",
  "flute": "phbmusFlute00000",
  "folding boat": "dmgFoldingBoat00",
  "fool": "dmgDmtFool000000",
  "forgery kit": "phbtulForgeryKit",
  "frost brand": "dmgFrostBrand000",
  "gauntlets of ogre power": "dmgGauntletsOfOg",
  "gem": "dmgDmtGem0000000",
  "gem of brightness": "dmgGemOfBrightne",
  "gem of seeing": "dmgGemOfSeeing00",
  "giant slayer": "dmgGiantSlayer00",
  "glaive": "phbwepGlaive0000",
  "glamoured studded leather": "dmgGlamouredStud",
  "glassblower's tools": "phbtulGlassblowe",
  "gloves of missile snaring": "dmgGlovesOfMissi",
  "gloves of swimming and climbing": "dmgGlovesOfSwimm",
  "gloves of thievery": "dmgGlovesOfThiev",
  "goggles of night": "dmgGogglesOfNigh",
  "golden lions": "dmgFwpGoldenLion",
  "grappling hook": "phbagGrapplingHo",
  "gray bag of tricks": "dmgBagOfTricks00",
  "greataxe": "phbwepGreataxe00",
  "greatclub": "phbwepGreatclub0",
  "greatsword": "phbwepGreatsword",
  "halberd": "phbwepHalberd000",
  "half plate armor": "phbarmHalfPlateA",
  "hammer of thunderbolts": "dmgHammerOfThund",
  "hand crossbow": "phbwepHandCrossb",
  "handaxe": "phbwepHandaxe000",
  "handy haversack": "dmgHewardsHandyH",
  "hat of disguise": "dmgHatOfDisguise",
  "hat of many spells": "dmgHatOfManySpel",
  "headband of intellect": "dmgHeadbandOfInt",
  "healer's kit": "phbagHealersKit0",
  "heavy crossbow": "phbwepHeavyCross",
  "helm of brilliance": "dmgHelmOfBrillia",
  "helm of comprehending languages": "dmgHelmOfCompreh",
  "helm of telepathy": "dmgHelmOfTelepat",
  "helm of teleportation": "dmgHelmOfTelepor",
  "herbalism kit": "phbtulHerbalismK",
  "hidden pit": "dmgHiddenPit0000",
  "hide armor": "phbarmHideArmor0",
  "holy avenger": "dmgHolyAvenger00",
  "holy symbol (varies)": "phbagHolySymbolV",
  "holy water": "phbagHolyWater00",
  "hooded lantern": "DKYzehYrMUKiFDxt",
  "horn": "phbmusHorn000000",
  "horn of blasting": "dmgHornOfBlastin",
  "horn of valhalla": "dmgHornofValhall",
  "horseshoes of a zephyr": "dmgHorseshoesOfA",
  "horseshoes of speed": "dmgHorseshoesOfS",
  "hunting trap": "phbagHuntingTrap",
  "immovable rod": "dmgImmovableRod0",
  "ink": "vi0j4PYnO596a2L1",
  "ink pen": "uBvsyY44RP4LJLzp",
  "instant fortress": "dmgDaernsInstant",
  "ioun stone": "dmgIounStone0000",
  "ioun stone of absorption": "dmgAbsorptionIou",
  "ioun stone of agility": "dmgAgilityIounSt",
  "ioun stone of awareness": "dmgAwarenessIoun",
  "ioun stone of fortitude": "dmgFortitudeIoun",
  "ioun stone of greater absorption": "dmgGreaterAbsorp",
  "ioun stone of insight": "dmgInsightIounSt",
  "ioun stone of intellect": "dmgIntellectIoun",
  "ioun stone of leadership": "dmgLeadershipIou",
  "ioun stone of mastery": "dmgMasteryIounSt",
  "ioun stone of protection": "dmgProtectionIou",
  "ioun stone of regeneration": "dmgRegnerationIo",
  "ioun stone of reserve": "dmgReserveIounSt",
  "ioun stone of strength": "dmgStrengthIounS",
  "ioun stone of sustenance": "dmgSustenanceIou",
  "iron bands": "dmgIronBandsOfBi",
  "iron flask": "dmgIronFlask0000",
  "iron horn of valhalla": "dmgIronHornOfVal",
  "ivory goats": "dmgFwpIvoryGoats",
  "javelin": "phbwepJavelin000",
  "javelin of lightning": "dmgJavelinOfLigh",
  "jester": "dmgDmtJester0000",
  "jeweler's tools": "phbtulJewelersTo",
  "jug": "phbagJug00000000",
  "key": "dmgDmtKey0000000",
  "knight": "dmgDmtKnight0000",
  "ladder": "phbagLadder00000",
  "lamp": "SMj5QHHkDCdvkx35",
  "lance": "phbwepLance00000",
  "lantern of revealing": "dmgLanternOfReve",
  "lantern, bullseye": "phbagLanternBull",
  "lantern, hooded": "phbagLanternHood",
  "leather armor": "phbarmLeatherArm",
  "leatherworker's tools": "phbtulLeatherwor",
  "left pouch": "dmgLeftPouch0000",
  "light crossbow": "phbwepLightCross",
  "light hammer": "phbwepLightHamme",
  "lock": "phbagLock0000000",
  "long compartment": "dmgLongCompartme",
  "longbow": "phbwepLongbow000",
  "longsword": "phbwepLongsword0",
  "luck blade": "dmgLuckBlade0000",
  "lute": "phbmusLute000000",
  "lyre": "phbmusLyre000000",
  "mace": "phbwepMace000000",
  "mace of disruption": "dmgMaceOfDisrupt",
  "mace of smiting": "dmgMaceOfSmiting",
  "mace of terror": "dmgMaceOfTerror0",
  "magnifying glass": "phbagMagnifyingG",
  "malice": "dmgMalice0000000",
  "manacles": "phbagManacles000",
  "mantle of spell resistance": "dmgMantleOfSpell",
  "manual of bodily health": "dmgManualOfBodil",
  "manual of gainful exercise": "dmgManualOfGainf",
  "manual of golems": "dmgManualOfGolem",
  "manual of quickness of action": "dmgManualOfQuick",
  "map": "phbagMap00000000",
  "map or scroll case": "SKDkrz7KSUIfOnHE",
  "marble elephant": "dmgFwpMarbleElep",
  "marvelous pigments": "dmgNolzursMarvel",
  "mason's tools": "phbtulMasonsTool",
  "maul": "phbwepMaul000000",
  "medallion of thoughts": "dmgMedallionOfTh",
  "midnight tears": "dmgMidnightTears",
  "midsize compartment": "dmgMidsizeCompar",
  "mirror": "SoNpADeVEx2DDZgB",
  "mirror of life trapping": "dmgMirrorOfLifeT",
  "mithral armor": "dmgMithralArmor0",
  "moon": "dmgDmtMoon000000",
  "morningstar": "phbwepMorningsta",
  "musket": "phbwepMusket0000",
  "mysterious deck": "dmgDeckOfManyThi",
  "navigator's tools": "phbtulNavigators",
  "necklace of adaptation": "dmgNecklaceOfAda",
  "necklace of fireballs": "dmgNecklaceOfFir",
  "necklace of prayer beads": "dmgNecklaceOfPra",
  "needles": "phbamoNeedles000",
  "net": "phbagNet00000000",
  "nine lives stealer": "dmgNineLivesStea",
  "oathbow": "dmgOathbow000000",
  "obsidian steed": "dmgFwpObsidianSt",
  "oil": "JpE7eqjwXw95Sai5",
  "oil of etherealness": "dmgOilOfEthereal",
  "oil of sharpness": "dmgOilOfSharpnes",
  "oil of slipperiness": "dmgOilOfSlipperi",
  "oil of taggit": "dmgOilOfTaggit00",
  "onyx dog": "dmgFwpOnyxDogRar",
  "orb": "phbafcOrb0000000",
  "padded armor": "phbarmPaddedArmo",
  "painter's supplies": "phbtulPaintersSu",
  "pale tincture": "dmgPaleTincture0",
  "pan flute": "phbmusPanflute00",
  "paper": "rZATMqE6y9uD3uzz",
  "parchment": "I6wPnS0Z1qcpXjdL",
  "pearl of power": "dmgPearlOfPower0",
  "perfume": "yoRKNd2QddQp1XuX",
  "periapt of health": "dmgPeriaptOfHeal",
  "periapt of proof against poison": "dmgPeriaptOfProo",
  "periapt of wound closure": "dmgPeriaptOfWoun",
  "philter of love": "dmgPhilterOfLove",
  "pike": "phbwepPike000000",
  "pipes of haunting": "dmgPipesOfHaunti",
  "pipes of the sewers": "dmgPipesOfTheSew",
  "pistol": "phbwepPistol0000",
  "plate armor": "phbarmPlateArmor",
  "plate armor of etherealness": "dmgPlateArmorOfE",
  "playing cards": "phbgstPlayingcar",
  "poison, basic": "phbagPoisonBasic",
  "poisoned darts": "dmgPoisonedDarts",
  "poisoned needle": "dmgPoisonedNeedl",
  "poisoner's kit": "phbtulPoisonersK",
  "pole": "phbagPole0000000",
  "portable hole": "dmgPortableHole0",
  "pot, iron": "phbagPotIron0000",
  "potion of animal friendship": "dmgPotionOfAnima",
  "potion of clairvoyance": "dmgPotionOfClair",
  "potion of climbing": "dmgPotionOfClimb",
  "potion of diminution": "dmgPotionOfDimin",
  "potion of flying": "dmgPotionOfFlyin",
  "potion of gaseous form": "dmgPotionOfGaseo",
  "potion of giant strength": "dmgPotionofGiant",
  "potion of giant strength (cloud)": "dmgCloudPotionOf",
  "potion of giant strength (fire)": "dmgFirePotionOfG",
  "potion of giant strength (frost)": "dmgFrostPotionOf",
  "potion of giant strength (hill)": "dmgHillPotionOfG",
  "potion of giant strength (stone)": "dmgStonePotionOf",
  "potion of giant strength (storm)": "dmgStormPotionOf",
  "potion of growth": "dmgPotionOfGrowt",
  "potion of healing": "phbagPotionofHea",
  "potion of healing (greater)": "dmgGreaterPotion",
  "potion of healing (superior)": "dmgSuperiorPotio",
  "potion of healing (supreme)": "dmgSupremePotion",
  "potion of heroism": "dmgPotionOfHeroi",
  "potion of invisibility": "dmgPotionOfInvis",
  "potion of invulnerability": "dmgPotionOfInvul",
  "potion of longevity": "dmgPotionOfLonge",
  "potion of mind reading": "dmgPotionOfMindR",
  "potion of poison": "dmgPotionOfPoiso",
  "potion of resistance": "dmgPotionOfResis",
  "potion of speed": "dmgPotionOfSpeed",
  "potion of vitality": "dmgPotionOfVital",
  "potion of water breathing": "dmgPotionOfWater",
  "potter's tools": "phbtulPottersToo",
  "pouch": "phbagPouch000000",
  "priest's pack": "phbagPriestsPack",
  "purple worm poison": "dmgPurpleWormPoi",
  "puzzle": "dmgDmtPuzzle0000",
  "quarterstaff": "phbwepQuartersta",
  "quarterstaff of the acrobat": "dmgQuarterstaffO",
  "quiver": "phbagQuiver00000",
  "ram, portable": "phbagRamPortable",
  "rapier": "phbwepRapier0000",
  "rations": "llmXULupnKVHUGuE",
  "reliquary": "phbhsyReliquaryh",
  "right pouch": "dmgRightPouch000",
  "ring": "dmgsupRingofResi",
  "ring mail": "phbarmRingMail00",
  "ring of animal influence": "dmgRingOfAnimalI",
  "ring of djinni summoning": "dmgRingOfDjinniS",
  "ring of elemental command": "dmgRingOfElement",
  "ring of evasion": "dmgRingOfEvasion",
  "ring of feather falling": "dmgRingOfFeather",
  "ring of free action": "dmgRingOfFreeAct",
  "ring of invisibility": "dmgRingOfInvisib",
  "ring of jumping": "dmgRingOfJumping",
  "ring of mind shielding": "dmgRingOfMindShi",
  "ring of protection": "dmgRingOfProtect",
  "ring of regeneration": "dmgRingOfRegener",
  "ring of resistance": "dmgRingOfResista",
  "ring of shooting stars": "dmgRingOfShootin",
  "ring of spell storing": "dmgRingOfSpellSt",
  "ring of spell turning": "dmgRingOfSpellTu",
  "ring of swimming": "dmgRingOfSwimmin",
  "ring of telekinesis": "dmgRingOfTelekin",
  "ring of the ram": "dmgRingOfTheRam0",
  "ring of three wishes": "dmgRingOfThreeWi",
  "ring of warmth": "dmgRingOfWarmth0",
  "ring of water walking": "dmgRingOfWaterWa",
  "ring of x-ray vision": "dmgRingOfXrayVis",
  "robe": "jLcAY4Oph8ZEniG2",
  "robe of eyes": "dmgRobeOfEyes000",
  "robe of scintillating colors": "dmgRobeOfScintil",
  "robe of stars": "dmgRobeOfStars00",
  "robe of the archmagi": "dmgRobeOfTheArch",
  "robe of useful items": "dmgRobeOfUsefulI",
  "rod": "phbafcRod0000000",
  "rod of absorption": "dmgRodOfAbsorpti",
  "rod of alertness": "dmgRodOfAlertnes",
  "rod of lordly might": "dmgRodOfLordlyMi",
  "rod of resurrection": "dmgRodOfResurrec",
  "rod of rulership": "dmgRodOfRulershi",
  "rod of security": "dmgRodOfSecurity",
  "rogue": "dmgDmtRogue00000",
  "rolling stone": "dmgRollingStone0",
  "rope": "x8jC9e00t4cUYiKR",
  "rope of climbing": "dmgRopeOfClimbin",
  "rope of entanglement": "dmgRopeOfEntangl",
  "ruin": "dmgDmtRuin000000",
  "rust bag of tricks": "dmgRustBagofTric",
  "sack": "phbagSack0000000",
  "sage": "dmgDmtSage000000",
  "scale mail": "phbarmScaleMail0",
  "scarab of protection": "dmgScarabOfProte",
  "scholar's pack": "phbagScholarsPac",
  "scimitar": "phbwepScimitar00",
  "scimitar of speed": "dmgScimitarOfSpe",
  "scroll": "dmgsupBasicScrol",
  "sending stones": "dmgSendingStones",
  "sentinel shield": "dmgSentinelShiel",
  "serpent venom": "dmgSerpentVenom0",
  "serpentine owl": "dmgFwpSerpentine",
  "shawm": "phbmusShawm00000",
  "shield": "phbarmShield0000",
  "shield of missile attraction": "dmgShieldOfMissi",
  "shield of the cavalier": "dmgShieldOfTheCa",
  "shield, +1, +2, or +3": "dmgShield12or300",
  "short compartment": "dmgShortCompartm",
  "shortbow": "phbwepShortbow00",
  "shortsword": "phbwepShortsword",
  "shovel": "phbagShovel00000",
  "sickle": "phbwepSickle0000",
  "signal whistle": "phbagSignalWhist",
  "silver horn of valhalla": "dmgSilverHornOfV",
  "silver raven": "dmgFwpSilverRave",
  "skull": "dmgDmtSkull00000",
  "sling": "phbwepSling00000",
  "slippers of spider climbing": "dmgSlippersOfSpi",
  "smith's tools": "phbtulSmithsTool",
  "sovereign glue": "dmgSovereignGlue",
  "spear": "phbwepSpear00000",
  "spell scroll": "dmgSpellScroll00",
  "spell scroll, 1st level": "dmgSpellScroll1s",
  "spell scroll, 2nd level": "dmgSpellScroll2n",
  "spell scroll, 3rd level": "dmgSpellScroll3r",
  "spell scroll, 4th level": "dmgSpellScroll4t",
  "spell scroll, 5th level": "dmgSpellScroll5t",
  "spell scroll, 6th level": "dmgSpellScroll6t",
  "spell scroll, 7th level": "dmgSpellScroll7t",
  "spell scroll, 8th level": "dmgSpellScroll8t",
  "spell scroll, 9th level": "dmgSpellScroll9t",
  "spell scroll, cantrip": "phbagCantripScro",
  "spell scroll, level 1": "phbagSpellScroll",
  "spellguard shield": "dmgSpellguardShi",
  "sphere of annihilation": "dmgSphereOfAnnih",
  "spider's sting": "dmgLolthsSting00",
  "spiked pit": "dmgSpikedPit0000",
  "spikes, iron": "phbagSpikesIron0",
  "splint armor": "phbarmSplintArmo",
  "sprig of mistletoe": "phbdfcSprigofmis",
  "spyglass": "phbagSpyglass100",
  "staff": "phbafcStaffalsoa",
  "staff of charming": "dmgStaffOfCharmi",
  "staff of fire": "dmgStaffOfFire00",
  "staff of frost": "dmgStaffOfFrost0",
  "staff of healing": "dmgStaffOfHealin",
  "staff of power": "dmgStaffOfPower0",
  "staff of striking": "dmgStaffOfStriki",
  "staff of swarming insects": "dmgStaffOfSwarmi",
  "staff of the magi": "dmgStaffOfTheMag",
  "staff of the python": "dmgStaffOfThePyt",
  "staff of the woodlands": "dmgStaffOfTheWoo",
  "staff of thunder and lightning": "dmgStaffOfThunde",
  "staff of withering": "dmgStaffOfWither",
  "star": "dmgDmtStar000000",
  "stone of controlling earth elementals": "dmgStoneOfContro",
  "stone of good luck (luckstone)": "dmgStoneOfGoodLu",
  "string": "phbagString00000",
  "studded leather armor": "phbarmStuddedLea",
  "sun": "dmgDmtSun0000000",
  "sun blade": "dmgSunBlade00000",
  "sword of life stealing": "dmgSwordOfLifeSt",
  "sword of sharpness": "dmgSwordOfSharpn",
  "sword of wounding": "dmgSwordOfWoundi",
  "talisman of pure good": "dmgTalismanOfPur",
  "talisman of the sphere": "dmgTalismanOfThe",
  "talisman of ultimate evil": "dmgTalismanOfUlt",
  "talons": "dmgDmtTalons0000",
  "tan bag of tricks": "dmgTanBagofTrick",
  "tent": "phbagTent0000000",
  "thieves' tools": "phbtulThievesToo",
  "three-dragon ante": "phbgstThreedrago",
  "throne": "dmgDmtThrone0000",
  "thunderous greatclub": "dmgThunderousGre",
  "tinderbox": "RqrWyXa9XkriaxTP",
  "tinker's tools": "phbtulTinkersToo",
  "tome of clear thought": "dmgTomeOfClearTh",
  "tome of leadership and influence": "dmgTomeOfLeaders",
  "tome of understanding": "dmgTomeOfUnderst",
  "torch": "gYKSyS7STTresmnS",
  "torpor": "dmgTorpor0000000",
  "trident": "phbwepTrident000",
  "trident of fish command": "dmgTridentOfFish",
  "truth serum": "dmgTruthSerum000",
  "unarmed strike": "dmgUnarmedStrike",
  "universal solvent": "dmgUniversalSolv",
  "vial": "phbagVial0000000",
  "vicious weapon": "dmgViciousWeapon",
  "viol": "phbmusViol000000",
  "void": "dmgDmtVoid000000",
  "vorpal sword": "dmgVorpalSword00",
  "wand": "phbafcWand000000",
  "wand of binding": "dmgWandOfBinding",
  "wand of enemy detection": "dmgWandOfEnemyDe",
  "wand of fear": "dmgWandOfFear000",
  "wand of fireballs": "dmgWandOfFirebal",
  "wand of lightning bolts": "dmgWandOfLightni",
  "wand of magic detection": "dmgWandOfMagicDe",
  "wand of magic missiles": "dmgWandOfMagicMi",
  "wand of paralysis": "dmgWandOfParalys",
  "wand of polymorph": "dmgWandOfPolymor",
  "wand of secrets": "dmgWandOfSecrets",
  "wand of the war mage, +1, +2, or +3": "dmg1WandOfTheWar",
  "wand of web": "dmgWandOfWeb0000",
  "wand of wonder": "dmgWandOfWonder0",
  "war pick": "phbwepWarPick000",
  "warhammer": "phbwepWarhammer0",
  "water (pint)": "67ScUFYRuMU0J2Wt",
  "water ring of elemental command": "dmgWaterRingOfEl",
  "water, fresh (pint)": "dmgspWaterfresh0",
  "water, salt (pint)": "dmgspWatersalt00",
  "waterskin": "X5XgogJLLydoKdrJ",
  "weapon of warning": "dmgWeaponOfWarni",
  "weapon, +1, +2, or +3": "dmgWeapon12or300",
  "weaver's tools": "phbtulWeaversToo",
  "well of many worlds": "dmgWellOfManyWor",
  "whip": "phbwepWhip000000",
  "wind fan": "dmgWindFan000000",
  "winged boots": "dmgWingedBoots00",
  "wings of flying": "dmgWingsOfFlying",
  "woodcarver's tools": "phbtulWoodcarver",
  "wooden staff": "phbdfcWoodenstaf",
  "wyvern poison": "dmgWyvernPoison0",
  "yew wand": "phbdfcYewwand000",
};

/** `nomeDoItem` → "tipo/subtipo" do Item do Foundry ("consumable/food"). É a
 *  classificação de inventário do dnd5e - o que decide se o item pode ser
 *  equipado ou consumido na ficha. Ver engine/compendiumUuids.js. */
export const EQUIPMENT_TYPES = {
  "acid": "consumable/potion",
  "activate folding boat": "equipment/trinket",
  "adamantine armor": "equipment/",
  "air ring of elemental command": "equipment/ring",
  "alchemist's fire": "consumable/potion",
  "alchemist's supplies": "tool/art",
  "ammunition (varies)": "loot/gear",
  "ammunition of slaying": "consumable/ammo",
  "ammunition, +1, +2, or +3": "consumable/ammo",
  "amulet": "equipment/trinket",
  "amulet of health": "equipment/wondrous",
  "amulet of proof against detection and location": "equipment/wondrous",
  "amulet of the planes": "equipment/wondrous",
  "animated shield": "equipment/shield",
  "antitoxin": "consumable/potion",
  "apparatus of the crab": "equipment/wondrous",
  "arcane focus (varies)": "loot/gear",
  "armor of invulnerability": "equipment/heavy",
  "armor of resistance": "equipment/",
  "armor of vulnerability": "equipment/",
  "armor, +1, +2, or +3": "equipment/",
  "arrow-catching shield": "equipment/shield",
  "arrows": "consumable/ammo",
  "assassin's blood": "consumable/poison",
  "backpack": "container/",
  "bag of beans": "equipment/wondrous",
  "bag of devouring": "container/",
  "bag of holding": "container/",
  "bagpipes": "tool/music",
  "balance": "consumable/trinket",
  "ball bearings": "consumable/trinket",
  "barrel": "container/",
  "basket": "container/",
  "battleaxe": "weapon/martialM",
  "bead of force": "consumable/trinket",
  "bead of nourishment": "consumable/trinket",
  "bedroll": "loot/gear",
  "bell": "equipment/trinket",
  "belt of dwarvenkind": "equipment/wondrous",
  "belt of giant strength": "equipment/wondrous",
  "belt of giant strength (cloud)": "equipment/wondrous",
  "belt of giant strength (fire)": "equipment/wondrous",
  "belt of giant strength (frost)": "equipment/wondrous",
  "belt of giant strength (hill)": "equipment/wondrous",
  "belt of giant strength (stone)": "equipment/wondrous",
  "belt of giant strength (storm)": "equipment/wondrous",
  "berserker axe": "weapon/martialM",
  "blanket": "loot/gear",
  "block and tackle": "loot/gear",
  "blowgun": "weapon/martialR",
  "bolts": "consumable/ammo",
  "book": "loot/gear",
  "boots of elvenkind": "equipment/wondrous",
  "boots of levitation": "equipment/wondrous",
  "boots of speed": "equipment/wondrous",
  "boots of striding and springing": "equipment/wondrous",
  "boots of the winterlands": "equipment/wondrous",
  "bottle, glass": "container/",
  "bowl of commanding water elementals": "equipment/wondrous",
  "bracers of archery": "equipment/wondrous",
  "bracers of defense": "equipment/wondrous",
  "brass horn of valhalla": "equipment/wondrous",
  "brazier of commanding fire elementals": "equipment/wondrous",
  "breastplate": "equipment/medium",
  "brewer's supplies": "tool/art",
  "bronze griffon": "equipment/wondrous",
  "bronze horn of valhalla": "equipment/wondrous",
  "brooch of shielding": "equipment/wondrous",
  "broom of flying": "equipment/wondrous",
  "bucket": "container/",
  "bullets, firearm": "consumable/ammo",
  "bullets, sling": "consumable/ammo",
  "bullseye lantern": "consumable/trinket",
  "burglar's pack": "container/",
  "burnt othur fumes": "consumable/poison",
  "calligrapher's supplies": "tool/art",
  "caltrops": "consumable/trinket",
  "candle": "consumable/trinket",
  "candle of invocation": "consumable/trinket",
  "cape of the mountebank": "equipment/wondrous",
  "carpenter's tools": "tool/art",
  "carpet of flying": "equipment/wondrous",
  "cartographer's tools": "tool/art",
  "case, crossbow bolt": "container/",
  "case, map or scroll": "container/",
  "censer of controlling air elementals": "equipment/wondrous",
  "central pouch": "container/",
  "chain": "consumable/trinket",
  "chain mail": "equipment/heavy",
  "chain shirt": "equipment/medium",
  "chest": "container/",
  "chime of opening": "equipment/wondrous",
  "circlet of blasting": "equipment/wondrous",
  "clawed gauntlet": "weapon/melee",
  "climber's kit": "equipment/",
  "cloak of arachnida": "equipment/wondrous",
  "cloak of displacement": "equipment/wondrous",
  "cloak of elvenkind": "equipment/wondrous",
  "cloak of invisibility": "equipment/wondrous",
  "cloak of protection": "equipment/wondrous",
  "cloak of the bat": "equipment/wondrous",
  "cloak of the manta ray": "equipment/wondrous",
  "clothes, fine": "equipment/clothing",
  "clothes, traveler's": "equipment/clothing",
  "club": "weapon/simpleM",
  "cobbler's tools": "tool/art",
  "collapsing roof": "equipment/",
  "comet": "consumable/trinket",
  "component pouch": "container/",
  "cook's utensils": "tool/art",
  "costume": "equipment/clothing",
  "crawler mucus": "consumable/poison",
  "crowbar": "loot/gear",
  "crystal": "equipment/trinket",
  "crystal ball": "equipment/wondrous",
  "crystal ball of mind reading": "equipment/wondrous",
  "crystal ball of telepathy": "equipment/wondrous",
  "crystal ball of true seeing": "equipment/wondrous",
  "cube of force": "equipment/wondrous",
  "cubic gate": "equipment/wondrous",
  "dagger": "weapon/simpleM",
  "dagger of venom": "weapon/simpleM",
  "dancing sword": "weapon/martialM",
  "dart": "weapon/simpleR",
  "decanter of endless water": "equipment/wondrous",
  "deck of illusions": "equipment/wondrous",
  "defender": "weapon/",
  "demon armor": "equipment/",
  "dice": "tool/game",
  "dimensional shackles": "equipment/wondrous",
  "diplomat's pack": "container/",
  "disguise kit": "tool/",
  "donjon": "consumable/trinket",
  "dragon orb": "equipment/wondrous",
  "dragon scale mail": "equipment/medium",
  "dragon slayer": "weapon/",
  "dragonchess": "tool/game",
  "druidic focus (varies)": "loot/gear",
  "drum": "tool/music",
  "dulcimer": "tool/music",
  "dungeoneer's pack": "container/",
  "dust of disappearance": "consumable/",
  "dust of dryness": "consumable/",
  "dust of sneezing and choking": "consumable/",
  "dwarven plate": "equipment/",
  "dwarven thrower": "weapon/",
  "earth ring of elemental command": "equipment/ring",
  "ebony fly": "equipment/wondrous",
  "efficient quiver": "container/",
  "efreeti bottle": "consumable/trinket",
  "elemental gem": "consumable/trinket",
  "elemental gem (blue sapphire)": "consumable/trinket",
  "elemental gem (emerald)": "consumable/trinket",
  "elemental gem (red corundum)": "consumable/trinket",
  "elemental gem (yellow diamond)": "consumable/trinket",
  "elixir of health": "consumable/potion",
  "elven chain": "equipment/",
  "emblem": "equipment/trinket",
  "energy bow": "weapon/",
  "entertainer's pack": "container/",
  "essence of ether": "consumable/poison",
  "euryale": "consumable/trinket",
  "eversmoking bottle": "equipment/wondrous",
  "explorer's pack": "container/",
  "eyes of charming": "equipment/wondrous",
  "eyes of minute seeing": "equipment/wondrous",
  "eyes of the eagle": "equipment/wondrous",
  "falling net": "equipment/",
  "fates": "consumable/trinket",
  "feather token": "consumable/trinket",
  "feather token (anchor)": "consumable/trinket",
  "feather token (bird)": "consumable/trinket",
  "feather token (fan)": "consumable/trinket",
  "feather token (swan boat)": "consumable/trinket",
  "feather token (tree)": "consumable/trinket",
  "feather token (whip)": "consumable/trinket",
  "figurine of wondrous power": "equipment/trinket",
  "fine clothes": "equipment/clothing",
  "fire ring of elemental command": "equipment/ring",
  "fire-casting statue": "equipment/",
  "flail": "weapon/martialM",
  "flame tongue": "weapon/",
  "flames": "consumable/trinket",
  "flask": "container/",
  "flute": "tool/music",
  "folding boat": "container/",
  "fool": "consumable/trinket",
  "forgery kit": "tool/",
  "frost brand": "weapon/martialM",
  "gauntlets of ogre power": "equipment/wondrous",
  "gem": "consumable/trinket",
  "gem of brightness": "equipment/wondrous",
  "gem of seeing": "equipment/wondrous",
  "giant slayer": "weapon/melee",
  "glaive": "weapon/martialM",
  "glamoured studded leather": "equipment/light",
  "glassblower's tools": "tool/art",
  "gloves of missile snaring": "equipment/wondrous",
  "gloves of swimming and climbing": "equipment/wondrous",
  "gloves of thievery": "equipment/wondrous",
  "goggles of night": "equipment/wondrous",
  "golden lions": "equipment/wondrous",
  "grappling hook": "equipment/trinket",
  "gray bag of tricks": "equipment/wondrous",
  "greataxe": "weapon/martialM",
  "greatclub": "weapon/simpleM",
  "greatsword": "weapon/martialM",
  "halberd": "weapon/martialM",
  "half plate armor": "equipment/medium",
  "hammer of thunderbolts": "weapon/ranged",
  "hand crossbow": "weapon/martialR",
  "handaxe": "weapon/simpleM",
  "handy haversack": "container/",
  "hat of disguise": "equipment/wondrous",
  "hat of many spells": "equipment/wondrous",
  "headband of intellect": "equipment/wondrous",
  "healer's kit": "consumable/trinket",
  "heavy crossbow": "weapon/martialR",
  "helm of brilliance": "equipment/light",
  "helm of comprehending languages": "equipment/wondrous",
  "helm of telepathy": "equipment/wondrous",
  "helm of teleportation": "equipment/wondrous",
  "herbalism kit": "tool/",
  "hidden pit": "equipment/",
  "hide armor": "equipment/medium",
  "holy avenger": "weapon/",
  "holy symbol (varies)": "loot/gear",
  "holy water": "consumable/potion",
  "hooded lantern": "consumable/trinket",
  "horn": "tool/music",
  "horn of blasting": "equipment/wondrous",
  "horn of valhalla": "equipment/wondrous",
  "horseshoes of a zephyr": "equipment/wondrous",
  "horseshoes of speed": "equipment/wondrous",
  "hunting trap": "consumable/trinket",
  "immovable rod": "equipment/rod",
  "ink": "consumable/trinket",
  "ink pen": "equipment/trinket",
  "instant fortress": "equipment/wondrous",
  "ioun stone": "equipment/wondrous",
  "ioun stone of absorption": "equipment/wondrous",
  "ioun stone of agility": "equipment/wondrous",
  "ioun stone of awareness": "equipment/wondrous",
  "ioun stone of fortitude": "equipment/wondrous",
  "ioun stone of greater absorption": "equipment/wondrous",
  "ioun stone of insight": "equipment/wondrous",
  "ioun stone of intellect": "equipment/wondrous",
  "ioun stone of leadership": "equipment/wondrous",
  "ioun stone of mastery": "equipment/wondrous",
  "ioun stone of protection": "equipment/wondrous",
  "ioun stone of regeneration": "equipment/wondrous",
  "ioun stone of reserve": "equipment/wondrous",
  "ioun stone of strength": "equipment/wondrous",
  "ioun stone of sustenance": "equipment/wondrous",
  "iron bands": "equipment/ranged",
  "iron flask": "equipment/wondrous",
  "iron horn of valhalla": "equipment/wondrous",
  "ivory goats": "equipment/wondrous",
  "javelin": "weapon/simpleM",
  "javelin of lightning": "weapon/simpleM",
  "jester": "consumable/trinket",
  "jeweler's tools": "tool/art",
  "jug": "container/",
  "key": "consumable/trinket",
  "knight": "consumable/trinket",
  "ladder": "loot/gear",
  "lamp": "equipment/trinket",
  "lance": "weapon/martialM",
  "lantern of revealing": "equipment/wondrous",
  "lantern, bullseye": "equipment/trinket",
  "lantern, hooded": "equipment/trinket",
  "leather armor": "equipment/light",
  "leatherworker's tools": "tool/art",
  "left pouch": "container/",
  "light crossbow": "weapon/simpleR",
  "light hammer": "weapon/simpleM",
  "lock": "loot/gear",
  "long compartment": "container/",
  "longbow": "weapon/martialR",
  "longsword": "weapon/martialM",
  "luck blade": "weapon/",
  "lute": "tool/music",
  "lyre": "tool/music",
  "mace": "weapon/simpleM",
  "mace of disruption": "weapon/",
  "mace of smiting": "weapon/",
  "mace of terror": "weapon/simpleM",
  "magnifying glass": "loot/gear",
  "malice": "consumable/poison",
  "manacles": "consumable/trinket",
  "mantle of spell resistance": "equipment/wondrous",
  "manual of bodily health": "equipment/wondrous",
  "manual of gainful exercise": "equipment/wondrous",
  "manual of golems": "equipment/wondrous",
  "manual of quickness of action": "equipment/wondrous",
  "map": "loot/gear",
  "map or scroll case": "container/",
  "marble elephant": "equipment/wondrous",
  "marvelous pigments": "equipment/wondrous",
  "mason's tools": "tool/art",
  "maul": "weapon/martialM",
  "medallion of thoughts": "equipment/wondrous",
  "midnight tears": "consumable/poison",
  "midsize compartment": "container/",
  "mirror": "loot/gear",
  "mirror of life trapping": "equipment/wondrous",
  "mithral armor": "equipment/",
  "moon": "consumable/trinket",
  "morningstar": "weapon/martialM",
  "musket": "weapon/martialR",
  "mysterious deck": "equipment/wondrous",
  "navigator's tools": "tool/",
  "necklace of adaptation": "equipment/wondrous",
  "necklace of fireballs": "equipment/wondrous",
  "necklace of prayer beads": "equipment/wondrous",
  "needles": "consumable/ammo",
  "net": "equipment/trinket",
  "nine lives stealer": "weapon/",
  "oathbow": "weapon/ranged",
  "obsidian steed": "equipment/wondrous",
  "oil": "consumable/potion",
  "oil of etherealness": "consumable/potion",
  "oil of sharpness": "consumable/potion",
  "oil of slipperiness": "consumable/potion",
  "oil of taggit": "consumable/poison",
  "onyx dog": "equipment/wondrous",
  "orb": "equipment/trinket",
  "padded armor": "equipment/light",
  "painter's supplies": "tool/art",
  "pale tincture": "consumable/poison",
  "pan flute": "tool/music",
  "paper": "loot/gear",
  "parchment": "loot/gear",
  "pearl of power": "equipment/wondrous",
  "perfume": "loot/gear",
  "periapt of health": "equipment/wondrous",
  "periapt of proof against poison": "equipment/wondrous",
  "periapt of wound closure": "equipment/wondrous",
  "philter of love": "consumable/potion",
  "pike": "weapon/martialM",
  "pipes of haunting": "equipment/wondrous",
  "pipes of the sewers": "equipment/wondrous",
  "pistol": "weapon/martialR",
  "plate armor": "equipment/heavy",
  "plate armor of etherealness": "equipment/",
  "playing cards": "tool/game",
  "poison, basic": "consumable/potion",
  "poisoned darts": "equipment/",
  "poisoned needle": "equipment/",
  "poisoner's kit": "tool/",
  "pole": "loot/gear",
  "portable hole": "equipment/wondrous",
  "pot, iron": "container/",
  "potion of animal friendship": "consumable/potion",
  "potion of clairvoyance": "consumable/potion",
  "potion of climbing": "consumable/potion",
  "potion of diminution": "consumable/potion",
  "potion of flying": "consumable/potion",
  "potion of gaseous form": "consumable/potion",
  "potion of giant strength": "consumable/potion",
  "potion of giant strength (cloud)": "consumable/potion",
  "potion of giant strength (fire)": "consumable/potion",
  "potion of giant strength (frost)": "consumable/potion",
  "potion of giant strength (hill)": "consumable/potion",
  "potion of giant strength (stone)": "consumable/potion",
  "potion of giant strength (storm)": "consumable/potion",
  "potion of growth": "consumable/potion",
  "potion of healing": "consumable/potion",
  "potion of healing (greater)": "consumable/potion",
  "potion of healing (superior)": "consumable/potion",
  "potion of healing (supreme)": "consumable/potion",
  "potion of heroism": "consumable/potion",
  "potion of invisibility": "consumable/potion",
  "potion of invulnerability": "consumable/potion",
  "potion of longevity": "consumable/potion",
  "potion of mind reading": "consumable/potion",
  "potion of poison": "consumable/potion",
  "potion of resistance": "consumable/potion",
  "potion of speed": "consumable/potion",
  "potion of vitality": "consumable/potion",
  "potion of water breathing": "consumable/potion",
  "potter's tools": "tool/art",
  "pouch": "container/",
  "priest's pack": "container/",
  "purple worm poison": "consumable/poison",
  "puzzle": "consumable/trinket",
  "quarterstaff": "weapon/simpleM",
  "quarterstaff of the acrobat": "weapon/simpleM",
  "quiver": "container/",
  "ram, portable": "loot/gear",
  "rapier": "weapon/martialM",
  "rations": "consumable/food",
  "reliquary": "equipment/trinket",
  "right pouch": "container/",
  "ring": "equipment/ring",
  "ring mail": "equipment/heavy",
  "ring of animal influence": "equipment/ring",
  "ring of djinni summoning": "equipment/ring",
  "ring of elemental command": "equipment/ring",
  "ring of evasion": "equipment/ring",
  "ring of feather falling": "equipment/ring",
  "ring of free action": "equipment/ring",
  "ring of invisibility": "equipment/ring",
  "ring of jumping": "equipment/ring",
  "ring of mind shielding": "equipment/ring",
  "ring of protection": "equipment/ring",
  "ring of regeneration": "equipment/ring",
  "ring of resistance": "equipment/ring",
  "ring of shooting stars": "equipment/ring",
  "ring of spell storing": "equipment/ring",
  "ring of spell turning": "equipment/ring",
  "ring of swimming": "equipment/ring",
  "ring of telekinesis": "equipment/ring",
  "ring of the ram": "equipment/ranged",
  "ring of three wishes": "equipment/ring",
  "ring of warmth": "equipment/ring",
  "ring of water walking": "equipment/ring",
  "ring of x-ray vision": "equipment/ring",
  "robe": "equipment/clothing",
  "robe of eyes": "equipment/wondrous",
  "robe of scintillating colors": "equipment/wondrous",
  "robe of stars": "equipment/wondrous",
  "robe of the archmagi": "equipment/wondrous",
  "robe of useful items": "equipment/wondrous",
  "rod": "equipment/trinket",
  "rod of absorption": "equipment/rod",
  "rod of alertness": "equipment/rod",
  "rod of lordly might": "weapon/melee",
  "rod of resurrection": "equipment/rod",
  "rod of rulership": "equipment/rod",
  "rod of security": "equipment/rod",
  "rogue": "consumable/trinket",
  "rolling stone": "equipment/",
  "rope": "consumable/trinket",
  "rope of climbing": "equipment/wondrous",
  "rope of entanglement": "equipment/wondrous",
  "ruin": "consumable/trinket",
  "rust bag of tricks": "equipment/trinket",
  "sack": "container/",
  "sage": "consumable/trinket",
  "scale mail": "equipment/medium",
  "scarab of protection": "equipment/wondrous",
  "scholar's pack": "container/",
  "scimitar": "weapon/martialM",
  "scimitar of speed": "weapon/",
  "scroll": "consumable/scroll",
  "sending stones": "equipment/wondrous",
  "sentinel shield": "equipment/shield",
  "serpent venom": "consumable/poison",
  "serpentine owl": "equipment/wondrous",
  "shawm": "tool/music",
  "shield": "equipment/shield",
  "shield of missile attraction": "equipment/shield",
  "shield of the cavalier": "equipment/melee",
  "shield, +1, +2, or +3": "equipment/shield",
  "short compartment": "container/",
  "shortbow": "weapon/simpleR",
  "shortsword": "weapon/martialM",
  "shovel": "loot/gear",
  "sickle": "weapon/simpleM",
  "signal whistle": "equipment/trinket",
  "silver horn of valhalla": "equipment/wondrous",
  "silver raven": "equipment/wondrous",
  "skull": "consumable/trinket",
  "sling": "weapon/simpleR",
  "slippers of spider climbing": "equipment/wondrous",
  "smith's tools": "tool/art",
  "sovereign glue": "equipment/wondrous",
  "spear": "weapon/simpleM",
  "spell scroll": "consumable/scroll",
  "spell scroll, 1st level": "consumable/scroll",
  "spell scroll, 2nd level": "consumable/scroll",
  "spell scroll, 3rd level": "consumable/scroll",
  "spell scroll, 4th level": "consumable/scroll",
  "spell scroll, 5th level": "consumable/scroll",
  "spell scroll, 6th level": "consumable/scroll",
  "spell scroll, 7th level": "consumable/scroll",
  "spell scroll, 8th level": "consumable/scroll",
  "spell scroll, 9th level": "consumable/scroll",
  "spell scroll, cantrip": "consumable/scroll",
  "spell scroll, level 1": "consumable/scroll",
  "spellguard shield": "equipment/shield",
  "sphere of annihilation": "equipment/wondrous",
  "spider's sting": "consumable/poison",
  "spiked pit": "equipment/",
  "spikes, iron": "loot/gear",
  "splint armor": "equipment/heavy",
  "sprig of mistletoe": "equipment/trinket",
  "spyglass": "loot/gear",
  "staff": "weapon/simpleM",
  "staff of charming": "weapon/simpleM",
  "staff of fire": "weapon/simpleM",
  "staff of frost": "weapon/simpleM",
  "staff of healing": "weapon/simpleM",
  "staff of power": "weapon/simpleM",
  "staff of striking": "weapon/",
  "staff of swarming insects": "weapon/simpleM",
  "staff of the magi": "weapon/simpleM",
  "staff of the python": "weapon/simpleM",
  "staff of the woodlands": "weapon/simpleM",
  "staff of thunder and lightning": "weapon/",
  "staff of withering": "weapon/simpleM",
  "star": "consumable/trinket",
  "stone of controlling earth elementals": "equipment/wondrous",
  "stone of good luck (luckstone)": "equipment/wondrous",
  "string": "loot/gear",
  "studded leather armor": "equipment/light",
  "sun": "consumable/trinket",
  "sun blade": "weapon/",
  "sword of life stealing": "weapon/martialM",
  "sword of sharpness": "weapon/martialM",
  "sword of wounding": "weapon/",
  "talisman of pure good": "equipment/wondrous",
  "talisman of the sphere": "equipment/wondrous",
  "talisman of ultimate evil": "equipment/wondrous",
  "talons": "consumable/trinket",
  "tan bag of tricks": "equipment/trinket",
  "tent": "loot/gear",
  "thieves' tools": "tool/",
  "three-dragon ante": "tool/game",
  "throne": "consumable/trinket",
  "thunderous greatclub": "weapon/",
  "tinderbox": "equipment/trinket",
  "tinker's tools": "tool/art",
  "tome of clear thought": "equipment/wondrous",
  "tome of leadership and influence": "equipment/wondrous",
  "tome of understanding": "equipment/wondrous",
  "torch": "consumable/trinket",
  "torpor": "consumable/poison",
  "trident": "weapon/martialM",
  "trident of fish command": "weapon/martialM",
  "truth serum": "consumable/potion",
  "unarmed strike": "weapon/melee",
  "universal solvent": "equipment/wondrous",
  "vial": "container/",
  "vicious weapon": "weapon/",
  "viol": "tool/music",
  "void": "consumable/trinket",
  "vorpal sword": "weapon/",
  "wand": "equipment/trinket",
  "wand of binding": "equipment/wand",
  "wand of enemy detection": "equipment/wand",
  "wand of fear": "equipment/wand",
  "wand of fireballs": "equipment/wand",
  "wand of lightning bolts": "equipment/wand",
  "wand of magic detection": "equipment/wand",
  "wand of magic missiles": "equipment/wand",
  "wand of paralysis": "equipment/wand",
  "wand of polymorph": "equipment/wand",
  "wand of secrets": "equipment/wand",
  "wand of the war mage, +1, +2, or +3": "equipment/wand",
  "wand of web": "equipment/wand",
  "wand of wonder": "equipment/wand",
  "war pick": "weapon/martialM",
  "warhammer": "weapon/martialM",
  "water (pint)": "consumable/food",
  "water ring of elemental command": "equipment/ring",
  "water, fresh (pint)": "consumable/food",
  "water, salt (pint)": "consumable/food",
  "waterskin": "container/",
  "weapon of warning": "weapon/simpleM",
  "weapon, +1, +2, or +3": "weapon/",
  "weaver's tools": "tool/art",
  "well of many worlds": "equipment/wondrous",
  "whip": "weapon/martialM",
  "wind fan": "equipment/wondrous",
  "winged boots": "equipment/wondrous",
  "wings of flying": "equipment/wondrous",
  "woodcarver's tools": "tool/art",
  "wooden staff": "weapon/simpleM",
  "wyvern poison": "consumable/poison",
  "yew wand": "equipment/trinket",
};

/** `nomeDoItem` → `{weightless, capacity}` dos itens de tipo `container`.
 *  Nenhum dos dois é derivável do 5etools: que a Bag of Holding pesa o mesmo
 *  "regardless of its contents" está só na PROSA. O peso carregado segue o RAW -
 *  o conteúdo de um contêiner `weightless` não conta. Ver engine/containers.js. */
export const CONTAINER_PROPS = {
  "backpack": {"weightless":false,"capacity":{"type":"weight","value":30}},
  "bag of devouring": {"weightless":true,"capacity":null},
  "bag of holding": {"weightless":true,"capacity":{"type":"weight","value":500}},
  "barrel": {"weightless":false,"capacity":{"type":"weight","value":333.6}},
  "basket": {"weightless":false,"capacity":{"type":"weight","value":40}},
  "bottle, glass": {"weightless":false,"capacity":null},
  "bucket": {"weightless":false,"capacity":null},
  "burglar's pack": {"weightless":false,"capacity":{"type":"weight","value":30}},
  "case, crossbow bolt": {"weightless":false,"capacity":null},
  "case, map or scroll": {"weightless":false,"capacity":null},
  "central pouch": {"weightless":true,"capacity":null},
  "chest": {"weightless":false,"capacity":{"type":"weight","value":360}},
  "component pouch": {"weightless":false,"capacity":null},
  "diplomat's pack": {"weightless":false,"capacity":{"type":"weight","value":360}},
  "dungeoneer's pack": {"weightless":false,"capacity":{"type":"weight","value":30}},
  "efficient quiver": {"weightless":true,"capacity":{"type":"items","value":3}},
  "entertainer's pack": {"weightless":false,"capacity":{"type":"weight","value":30}},
  "explorer's pack": {"weightless":false,"capacity":{"type":"weight","value":30}},
  "flask": {"weightless":false,"capacity":null},
  "folding boat": {"weightless":false,"capacity":null},
  "handy haversack": {"weightless":true,"capacity":null},
  "jug": {"weightless":false,"capacity":{"type":"weight","value":8.4}},
  "left pouch": {"weightless":true,"capacity":null},
  "long compartment": {"weightless":true,"capacity":null},
  "map or scroll case": {"weightless":false,"capacity":null},
  "midsize compartment": {"weightless":true,"capacity":null},
  "pot, iron": {"weightless":false,"capacity":{"type":"weight","value":8.4}},
  "pouch": {"weightless":false,"capacity":{"type":"weight","value":6}},
  "priest's pack": {"weightless":false,"capacity":{"type":"weight","value":30}},
  "quiver": {"weightless":false,"capacity":null},
  "right pouch": {"weightless":true,"capacity":null},
  "sack": {"weightless":false,"capacity":{"type":"weight","value":30}},
  "scholar's pack": {"weightless":false,"capacity":{"type":"weight","value":30}},
  "short compartment": {"weightless":true,"capacity":null},
  "vial": {"weightless":false,"capacity":{"type":"weight","value":0.25}},
  "waterskin": {"weightless":false,"capacity":{"type":"weight","value":4}},
};

/** `classId|feature` → `system.uses` ({max, recovery}) do SRD. O POOL de um
 *  recurso não é derivável do texto do 5etools; sem ele a ficha do Foundry não
 *  tem o que gastar (TC-0068). Keyed por classe porque o nome colide
 *  ("Channel Divinity" tem escala própria no Clérigo e no Paladino). */
export const FEATURE_USES_BY_CLASS = {
  "barbarian|intimidating presence": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "barbarian|persistent rage": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "barbarian|rage": {"max":"@scale.barbarian.rages","recovery":[{"period":"lr","type":"recoverAll"},{"period":"sr","type":"formula","formula":"1"}]},
  "barbarian|relentless rage": {"max":"20","recovery":[{"period":"sr","type":"recoverAll"}]},
  "bard|bardic inspiration": {"max":"max(1, @abilities.cha.mod)","recovery":[{"period":"lr","type":"recoverAll"}]},
  "cleric|channel divinity": {"max":"@scale.cleric.channel-divinity","recovery":[{"period":"lr","type":"recoverAll"},{"period":"sr","type":"formula","formula":"1"}]},
  "cleric|divine intervention": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "druid|archdruid": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "druid|wild resurgence": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "druid|wild shape": {"max":"@scale.druid.wild-shape-uses","recovery":[{"period":"lr","type":"recoverAll"},{"period":"sr","type":"formula","formula":"1"}]},
  "fighter|action surge": {"max":"@scale.fighter.action-surge","recovery":[{"period":"sr","type":"recoverAll"}]},
  "fighter|indomitable": {"max":"@scale.fighter.indomitable","recovery":[{"period":"lr","type":"recoverAll"}]},
  "fighter|second wind": {"max":"@scale.fighter.second-wind","recovery":[{"period":"lr","type":"recoverAll"},{"period":"sr","type":"formula","formula":"1"}]},
  "monk|monk's focus": {"max":"@scale.monk.focus","recovery":[{"period":"sr","type":"recoverAll"}]},
  "monk|uncanny metabolism": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "monk|wholeness of body": {"max":"max(1,@abilities.wis.mod)","recovery":[{"period":"lr","type":"recoverAll"}]},
  "paladin|channel divinity": {"max":"@scale.paladin.channel-divinity","recovery":[{"period":"lr","type":"recoverAll"},{"period":"sr","type":"formula","formula":"1"}]},
  "paladin|holy nimbus": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "paladin|lay on hands": {"max":"5 * @classes.paladin.levels","recovery":[{"period":"lr","type":"recoverAll"}]},
  "ranger|favored enemy": {"max":"@scale.ranger.favored-enemy","recovery":[{"period":"lr","type":"recoverAll"}]},
  "ranger|nature's veil": {"max":"(max(1,@abilities.wis.mod))","recovery":[{"period":"lr","type":"recoverAll"}]},
  "rogue|stroke of luck": {"max":"1","recovery":[{"period":"sr","type":"recoverAll"}]},
  "sorcerer|dragon companion": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "sorcerer|dragon wings": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "sorcerer|font of magic": {"max":"@scale.sorcerer.points","recovery":[{"period":"lr","type":"recoverAll"}]},
  "sorcerer|innate sorcery": {"max":"2","recovery":[{"period":"lr","type":"recoverAll"}]},
  "sorcerer|sorcerous restoration": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "warlock|dark one's own luck": {"max":"(max(1,@abilities.cha.mod))","recovery":[{"period":"lr","type":"recoverAll"}]},
  "warlock|gift of the depths": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "warlock|gift of the protectors": {"max":"(max(1,@abilities.cha.mod))","recovery":[]},
  "warlock|hurl through hell": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "warlock|magical cunning": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "wizard|arcane recovery": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "wizard|overchannel": {"max":"20","recovery":[{"period":"lr","type":"recoverAll"}]},
};

/** `traço de espécie ou talento` → `system.uses` do SRD (pacotes origins24 e
 *  feats24, onde o nome não colide com o de uma classe). */
export const FEATURE_USES_FLAT = {
  "adrenaline rush": {"max":"@prof","recovery":[{"period":"sr","type":"recoverAll"}]},
  "boon of fate": {"max":"1","recovery":[{"period":"sr","type":"recoverAll"},{"period":"initiative","type":"recoverAll"}]},
  "breath weapon": {"max":"@prof","recovery":[{"period":"lr","type":"recoverAll"}]},
  "cloud's jaunt": {"max":"@prof","recovery":[{"period":"lr","type":"recoverAll"}]},
  "draconic flight": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "fire's burn": {"max":"@prof","recovery":[{"period":"lr","type":"recoverAll"}]},
  "frost's chill": {"max":"@prof","recovery":[{"period":"lr","type":"recoverAll"}]},
  "hill's tumble": {"max":"@prof","recovery":[{"period":"lr","type":"recoverAll"}]},
  "large form": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "relentless endurance": {"max":"1","recovery":[{"period":"lr","type":"recoverAll"}]},
  "stone's endurance": {"max":"@prof","recovery":[{"period":"lr","type":"recoverAll"}]},
  "stonecunning": {"max":"@prof","recovery":[{"period":"lr","type":"recoverAll"}]},
  "storm's thunder": {"max":"@prof","recovery":[{"period":"lr","type":"recoverAll"}]},
};
