// =============================================================================
// compendiumUuidsData - GERADO por `npm run gen:uuids`. NÃO EDITE À MÃO.
// =============================================================================
// Identificadores de documentos dos compêndios do sistema dnd5e (SRD 2024, MIT +
// CC-BY-4.0), extraídos de packs/_source. Apenas ids e nomes - nenhum conteúdo de
// jogo é redistribuído aqui. Consumidos por engine/compendiumUuids.js para montar
// os ItemGrant de níveis FUTUROS (ver o módulo irmão para o porquê).
//
// Cobertura: as 12 classes XPHB (159 features), 12 subclasses SRD
// (58 features) e 340 magias.
// -----------------------------------------------------------------------------

/** Pacote de compêndio de cada mapa (prefixo do uuid). */
export const PACK_CLASSES = 'Compendium.dnd5e.classes24.Item';
export const PACK_SPELLS = 'Compendium.dnd5e.spells24.Item';

/** `classId|nomeDaFeature` → _id (pacote classes24). */
export const CLASS_FEATURE_IDS = {
  "barbarian|brutal strike": "phbbrbBrutalStri",
  "barbarian|danger sense": "phbbrbDangerSens",
  "barbarian|epic boon": "phbbrbEpicBoon00",
  "barbarian|extra attack": "phbbrbExtraAttac",
  "barbarian|fast movement": "phbbrbFastMoveme",
  "barbarian|feral instinct": "phbbrbFeralInsti",
  "barbarian|improved brutal strike": "phbbrbImpBrutalS",
  "barbarian|improved brutal strike (2)": "phbbrbImp2Brutal",
  "barbarian|indomitable might": "phbbrbIndomitabl",
  "barbarian|instinctive pounce": "phbbrbInstinctiv",
  "barbarian|persistent rage": "phbbrbPersistent",
  "barbarian|primal champion": "phbbrbPrimalCham",
  "barbarian|primal knowledge": "phbbrbPrimalKnow",
  "barbarian|rage": "phbbrbRage000000",
  "barbarian|reckless attack": "phbbrbRecklessAt",
  "barbarian|relentless rage": "phbbrbRelentless",
  "barbarian|unarmored defense": "phbbrbUnarmoredD",
  "barbarian|weapon mastery": "phbbrbWeaponMast",
  "bard|bardic inspiration": "phbbrdBardicInsp",
  "bard|countercharm": "phbbrdCountercha",
  "bard|epic boon": "phbbrdEpicBoon00",
  "bard|expertise": "phbbrdExpertise0",
  "bard|font of inspiration": "phbbrdFontOfInsp",
  "bard|jack of all trades": "phbbrdJackOfAllT",
  "bard|magical secrets": "phbbrdMagicalSec",
  "bard|spellcasting": "phbbrdSpellcasti",
  "bard|superior inspiration": "phbbrdSuperiorIn",
  "bard|words of creation": "phbbrdWordsOfCre",
  "cleric|blessed strikes": "phbclcBlessedStr",
  "cleric|blessed strikes: divine strike": "phbDivineStrike0",
  "cleric|blessed strikes: potent spellcasting": "phbClcPotentSpel",
  "cleric|channel divinity": "phbclcChannelDiv",
  "cleric|divine intervention": "phbclcDivineInte",
  "cleric|divine order": "phbclcDivineOrde",
  "cleric|divine order: protector": "phbDivineOrderPr",
  "cleric|divine order: thaumaturge": "phbDivineOrderTh",
  "cleric|epic boon": "phbclcEpicBoon00",
  "cleric|greater divine intervention": "phbclcGreaterDiv",
  "cleric|improved blessed strikes": "phbclcImprovedBl",
  "cleric|sear undead": "phbclcSearUndead",
  "cleric|spellcasting": "phbclcSpellcasti",
  "druid|archdruid": "phbdrdArchdruid0",
  "druid|beast spells": "phbdrdBeastSpell",
  "druid|druidic": "phbdrdDruidic000",
  "druid|elemental fury": "phbdrdElementalF",
  "druid|elemental fury: potent spellcasting": "phbFuryPotentSpe",
  "druid|elemental fury: primal strike": "phbFuryPrimalStr",
  "druid|epic boon": "phbdrdEpicBoon00",
  "druid|improved elemental fury": "phbdrdImprovedEl",
  "druid|primal order": "phbdrdPrimalOrde",
  "druid|primal order: magician": "phbPrimalOrderMa",
  "druid|primal order: warden": "phbPrimalOrderWa",
  "druid|spellcasting": "phbdrdSpellcasti",
  "druid|wild companion": "phbdrdWildCompan",
  "druid|wild resurgence": "phbdrdWildResurg",
  "druid|wild shape": "phbdrdWildShape0",
  "fighter|action surge": "phbftrActionSurg",
  "fighter|epic boon": "phbftrEpicBoon00",
  "fighter|extra attack": "phbftrExtraAttac",
  "fighter|fighting style": "phbftrFightingSt",
  "fighter|indomitable": "phbftrIndomitabl",
  "fighter|second wind": "phbftrSecondWind",
  "fighter|studied attacks": "phbftrStudiedAtt",
  "fighter|tactical master": "phbftrTacticalMa",
  "fighter|tactical mind": "phbftrTacticalMi",
  "fighter|tactical shift": "phbftrTacticalSh",
  "fighter|three extra attacks": "phbftrThreeExtra",
  "fighter|two extra attacks": "phbftrTwoExtraAt",
  "fighter|weapon mastery": "phbftrWeaponMast",
  "monk|acrobatic movement": "phbmnkAcrobaticM",
  "monk|body and mind": "phbmnkBodyAndMin",
  "monk|deflect attacks": "phbmnkDeflectAtt",
  "monk|deflect energy": "phbmnkDeflectEne",
  "monk|disciplined survivor": "phbmnkDiscipline",
  "monk|empowered strikes": "phbmnkEmpoweredS",
  "monk|epic boon": "phbmnkEpicBoon00",
  "monk|evasion": "phbmnkEvasion000",
  "monk|extra attack": "phbmnkExtraAttac",
  "monk|heightened focus": "phbmnkHeightened",
  "monk|martial arts": "phbmnkMartialArt",
  "monk|monk's focus": "phbmnkMonksFocus",
  "monk|perfect focus": "phbmnkPerfectFoc",
  "monk|slow fall": "phbmnkSlowFall00",
  "monk|stunning strike": "phbmnkStunningSt",
  "monk|superior defense": "phbmnkSuperiorDe",
  "monk|unarmored defense": "phbmnkUnarmoredD",
  "monk|unarmored movement": "phbmnkUnarmoredM",
  "monk|uncanny metabolism": "phbmnkUncannyMet",
  "paladin|abjure foes": "phbpdnAbjureFoes",
  "paladin|aura expansion": "phbpdnAuraExpans",
  "paladin|aura of courage": "phbpdnCourageAur",
  "paladin|aura of protection": "phbpdnProtection",
  "paladin|blessed warrior": "phbfstBlessedWar",
  "paladin|channel divinity": "phbpdnChannelDiv",
  "paladin|epic boon": "phbpdnEpicBoon00",
  "paladin|extra attack": "phbpdnExtraAttac",
  "paladin|faithful steed": "phbpdnFaithfulSt",
  "paladin|fighting style": "phbpdnFightingSt",
  "paladin|lay on hands": "phbpdnLayOnHands",
  "paladin|paladin's smite": "phbpdnPaladinsSm",
  "paladin|radiant strikes": "phbpdnRadiantStr",
  "paladin|restoring touch": "phbpdnRestoringT",
  "paladin|spellcasting": "phbpdnSpellcasti",
  "paladin|weapon mastery": "phbpdnWeaponMast",
  "ranger|deft explorer": "phbrgrDeftExplor",
  "ranger|druidic warrior": "phbfstDruidicWar",
  "ranger|epic boon": "phbrgrEpicBoon00",
  "ranger|expertise": "phbrgrExpertise0",
  "ranger|extra attack": "phbrgrExtraAttac",
  "ranger|favored enemy": "phbrgrFavoredEne",
  "ranger|feral senses": "phbrgrFeralSense",
  "ranger|fighting style": "phbrgrFightingSt",
  "ranger|foe slayer": "phbrgrFoeSlayer0",
  "ranger|nature's veil": "phbrgrNaturesVei",
  "ranger|precise hunter": "phbrgrPreciseHun",
  "ranger|relentless hunter": "phbrgrRelentless",
  "ranger|roving": "phbrgrRoving0000",
  "ranger|spellcasting": "phbrgrSpellcasti",
  "ranger|tireless": "phbrgrTireless00",
  "ranger|weapon mastery": "phbrgrWeaponMast",
  "rogue|cunning action": "phbrgeCunningAct",
  "rogue|cunning strike": "phbrgeCunningStr",
  "rogue|devious strikes": "phbrgeDeviousStr",
  "rogue|elusive": "phbrgeElusive000",
  "rogue|epic boon": "phbrgeEpicBoon00",
  "rogue|evasion": "phbrgeEvasion000",
  "rogue|expertise": "phbrgeExpertise0",
  "rogue|improved cunning strike": "phbrgeImprovedCu",
  "rogue|reliable talent": "phbrgeReliableTa",
  "rogue|slippery mind": "phbrgeSlipperyMi",
  "rogue|sneak attack": "phbrgeSneakAttac",
  "rogue|steady aim": "phbrgeSteadyAim0",
  "rogue|stroke of luck": "phbrgeStrokeOfLu",
  "rogue|thieves' cant": "phbrgeThievesCan",
  "rogue|uncanny dodge": "phbrgeUncannyDod",
  "rogue|weapon mastery": "phbrgeWeaponMast",
  "sorcerer|arcane apotheosis": "phbscrArcaneApot",
  "sorcerer|epic boon": "phbscrEpicBoon00",
  "sorcerer|font of magic": "phbscrFontOfMagi",
  "sorcerer|innate sorcery": "phbscrInnateSorc",
  "sorcerer|metamagic": "phbscrMetamagic0",
  "sorcerer|sorcerous restoration": "phbscrSorcerousR",
  "sorcerer|sorcery incarnate": "phbscrSorceryInc",
  "sorcerer|spellcasting": "phbscrSpellcasti",
  "warlock|contact patron": "phbwlkContactPat",
  "warlock|eldritch invocations": "phbwlkEldritchIn",
  "warlock|eldritch master": "phbwlkEldritchMa",
  "warlock|epic boon": "phbwlkEpicBoon00",
  "warlock|magical cunning": "phbwlkMagicalCun",
  "warlock|mystic arcanum": "phbwlkMysticArca",
  "warlock|pact magic": "phbwlkPactMagic0",
  "wizard|arcane recovery": "phbwzdArcaneReco",
  "wizard|epic boon": "phbwzdEpicBoon00",
  "wizard|memorize spell": "phbwzdMemorizeSp",
  "wizard|ritual adept": "phbwzdRitualAdep",
  "wizard|scholar": "phbwzdScholar000",
  "wizard|signature spells": "phbwzdSignatureS",
  "wizard|spell mastery": "phbwzdSpellMaste",
  "wizard|spellcasting": "phbwzdSpellcasti",
};

/** `classId|nomeDaSubclasse` → _id (pacote classes24). */
export const SUBCLASS_IDS = {
  "barbarian|path of the berserker": "phbbrbBerserker0",
  "bard|college of lore": "phbbrdLore000000",
  "cleric|life domain": "phbclcLifeDomain",
  "druid|circle of the land": "phbdrdCirland000",
  "fighter|champion": "phbftrChampion00",
  "monk|warrior of the open hand": "phbmnkOpenHandWa",
  "paladin|oath of devotion": "phbpdnOathOfDevo",
  "ranger|hunter": "phbrgrHunter0000",
  "rogue|thief": "phbrgeThief00000",
  "sorcerer|draconic sorcery": "phbscrDraconicSo",
  "warlock|fiend patron": "phbwlkFiendPatro",
  "wizard|evoker": "phbwzdEvoker0000",
};

/** `classId|nomeDaSubclasse|nomeDaFeature` → _id (pacote classes24). */
export const SUBCLASS_FEATURE_IDS = {
  "barbarian|path of the berserker|frenzy": "phbbrbFrenzy0000",
  "barbarian|path of the berserker|intimidating presence": "phbbrbIntimidati",
  "barbarian|path of the berserker|mindless rage": "phbbrbMindlessRa",
  "barbarian|path of the berserker|retaliation": "phbbrbRetaliatio",
  "bard|college of lore|bonus proficiencies": "phbbrdBonusProfi",
  "bard|college of lore|cutting words": "phbbrdCuttingWor",
  "bard|college of lore|magical discoveries": "phbbrdMagicalDis",
  "bard|college of lore|peerless skill": "phbbrdPeerlessSk",
  "cleric|life domain|blessed healer": "phbclcBlessedHea",
  "cleric|life domain|disciple of life": "phbclcDiscipleOf",
  "cleric|life domain|life domain spells": "phbclcLifeSpells",
  "cleric|life domain|preserve life": "phbclcPreserveLi",
  "cleric|life domain|supreme healing": "phbclcSupremeHea",
  "druid|circle of the land|circle of the land spells": "phbdrdLandSpells",
  "druid|circle of the land|land's aid": "phbdrdLandsAid00",
  "druid|circle of the land|natural recovery": "phbdrdNaturalRec",
  "druid|circle of the land|nature's sanctuary": "phbdrdNaturesSan",
  "druid|circle of the land|nature's ward": "phbdrdNaturesWar",
  "fighter|champion|additional fighting style": "phbftrAdditional",
  "fighter|champion|heroic warrior": "phbftrHeroicWarr",
  "fighter|champion|improved critical": "phbftrImprovedCr",
  "fighter|champion|remarkable athlete": "phbftrRemarkable",
  "fighter|champion|superior critical": "phbftrSuperiorCr",
  "fighter|champion|survivor": "phbftrSurvivor00",
  "monk|warrior of the open hand|fleet step": "phbmnkFleetStep0",
  "monk|warrior of the open hand|open hand technique": "phbmnkOpenHandTe",
  "monk|warrior of the open hand|quivering palm": "phbmnkQuiveringP",
  "monk|warrior of the open hand|wholeness of body": "phbmnkWholenessO",
  "paladin|oath of devotion|aura of devotion": "phbpdnDevotionAu",
  "paladin|oath of devotion|holy nimbus": "phbpdnHolyNimbus",
  "paladin|oath of devotion|oath of devotion spells": "phbpdnDevotionSp",
  "paladin|oath of devotion|sacred weapon": "phbpdnSacredWeap",
  "paladin|oath of devotion|smite of protection": "phbpdnSmiteOfPro",
  "ranger|hunter|defensive tactics": "phbrgrDefensiveT",
  "ranger|hunter|hunter's lore": "phbrgrHuntersLor",
  "ranger|hunter|hunter's prey": "phbrgrHuntersPre",
  "ranger|hunter|superior hunter's defense": "phbrgrSuperiorDe",
  "ranger|hunter|superior hunter's prey": "phbrgrSuperiorHu",
  "rogue|thief|fast hands": "phbrgeFastHands0",
  "rogue|thief|second-story work": "phbrgeSecondstor",
  "rogue|thief|supreme sneak": "phbrgeSupremeSne",
  "rogue|thief|thief's reflexes": "phbrgeThiefsRefl",
  "rogue|thief|use magic device": "phbrgeUseMagicDe",
  "sorcerer|draconic sorcery|draconic resilience": "phbscrDraconicRe",
  "sorcerer|draconic sorcery|draconic spells": "phbscrDraconicSp",
  "sorcerer|draconic sorcery|dragon companion": "phbscrDragonComp",
  "sorcerer|draconic sorcery|dragon wings": "phbscrDragonWing",
  "sorcerer|draconic sorcery|elemental affinity": "phbscrElementalA",
  "warlock|fiend patron|dark one's blessing": "phbwlkDarkOnesBl",
  "warlock|fiend patron|dark one's own luck": "phbwlkDarkOnesOw",
  "warlock|fiend patron|fiend spells": "phbwlkFiendSpell",
  "warlock|fiend patron|fiendish resilience": "phbwlkFiendishRe",
  "warlock|fiend patron|hurl through hell": "phbwlkHurlThroug",
  "wizard|evoker|empowered evocation": "phbwzdEmpoweredE",
  "wizard|evoker|evocation savant": "phbwzdEvocationS",
  "wizard|evoker|overchannel": "phbwzdOverchanne",
  "wizard|evoker|potent cantrip": "phbwzdPotentCant",
  "wizard|evoker|sculpt spells": "phbwzdSculptSpel",
};

/** `nomeDaMagia` → _id (pacote spells24). */
export const SPELL_IDS = {
  "acid arrow": "phbsplMelfsAcidA",
  "acid splash": "phbsplAcidSplash",
  "aid": "phbsplAid0000000",
  "alarm": "phbsplAlarm00000",
  "alter self": "phbsplAlterSelf0",
  "animal friendship": "phbsplAnimalFrie",
  "animal messenger": "phbsplAnimalMess",
  "animal shapes": "phbsplAnimalShap",
  "animate dead": "phbsplAnimateDea",
  "animate objects": "phbsplAnimateObj",
  "antilife shell": "phbsplAntilifeSh",
  "antimagic field": "phbsplAntimagicF",
  "antipathy/sympathy": "phbsplAntipathyS",
  "arcane eye": "phbsplArcaneEye0",
  "arcane hand": "phbsplBigbysHand",
  "arcane lock": "phbsplArcaneLock",
  "arcane sword": "phbswdMordenkain",
  "arcane vigor": "phbsplArcaneVigo",
  "arcanist's magic aura": "phbsplNystulsMag",
  "astral projection": "phbsplAstralProj",
  "augury": "phbsplAugury0000",
  "aura of life": "phbsplAuraofLife",
  "awaken": "phbsplAwaken0000",
  "bane": "phbsplBane000000",
  "banishment": "phbsplBanishment",
  "barkskin": "phbsplBarkskin00",
  "beacon of hope": "phbsplBeaconofHo",
  "befuddlement": "phbsplBefuddleme",
  "bestow curse": "phbsplBestowCurs",
  "black tentacles": "phbsplEvardsBlac",
  "blade barrier": "phbsplBladeBarri",
  "bless": "phbsplBless00000",
  "blight": "phbsplBlight0000",
  "blindness/deafness": "phbsplBlindnessD",
  "blink": "phbsplBlink00000",
  "blur": "phbsplBlur000000",
  "burning hands": "phbsplBurningHan",
  "call lightning": "phbsplCallLightn",
  "calm emotions": "phbsplCalmEmotio",
  "chain lightning": "phbsplChainLight",
  "charm monster": "phbsplCharmMonst",
  "charm person": "phbsplCharmPerso",
  "chill touch": "phbsplChillTouch",
  "chromatic orb": "phbsplChromaticO",
  "circle of death": "phbsplCircleofDe",
  "clairvoyance": "phbsplClairvoyan",
  "clone": "phbsplClone00000",
  "cloudkill": "phbsplCloudkill0",
  "color spray": "phbsplColorSpray",
  "command": "phbsplCommand000",
  "commune": "phbsplCommune000",
  "commune with nature": "phbsplCommunewit",
  "comprehend languages": "phbsplComprehend",
  "compulsion": "phbsplCompulsion",
  "cone of cold": "phbsplConeofCold",
  "confusion": "phbsplConfusion0",
  "conjure animals": "phbsplConjureAni",
  "conjure celestial": "phbsplConjureCel",
  "conjure elemental": "phbsplConjureEle",
  "conjure fey": "phbsplConjureFey",
  "conjure minor elementals": "phbsplConjureMin",
  "conjure woodland beings": "phbsplConjureWoo",
  "contact other plane": "phbsplContactOth",
  "contagion": "phbsplContagion0",
  "contingency": "phbsplContingenc",
  "continual flame": "phbsplContinualF",
  "control water": "phbsplControlWat",
  "control weather": "phbsplControlWea",
  "counterspell": "phbsplCounterspe",
  "create food and water": "phbsplCreateFood",
  "create or destroy water": "phbsplCreateorDe",
  "create undead": "phbsplCreateUnde",
  "creation": "phbsplCreation00",
  "cure wounds": "phbsplCureWounds",
  "dancing lights": "phbsplDancingLig",
  "darkness": "phbsplDarkness00",
  "darkvision": "phbsplDarkvision",
  "daylight": "phbsplDaylight00",
  "death ward": "phbsplDeathWard0",
  "delayed blast fireball": "phbsplDelayedBla",
  "demiplane": "phbsplDemiplane0",
  "detect evil and good": "phbsplDetectEvil",
  "detect magic": "phbsplDetectMagi",
  "detect poison and disease": "phbsplDetectPois",
  "detect thoughts": "phbsplDetectThou",
  "dimension door": "phbsplDimensionD",
  "disguise self": "phbsplDisguiseSe",
  "disintegrate": "phbsplDisintegra",
  "dispel evil and good": "phbsplDispelEvil",
  "dispel magic": "phbsplDispelMagi",
  "dissonant whispers": "phbsplDissonantW",
  "divination": "phbsplDivination",
  "divine favor": "phbsplDivineFavo",
  "divine smite": "phbsplDivineSmit",
  "divine word": "phbsplDivineWord",
  "dominate beast": "phbsplDominateBe",
  "dominate monster": "phbsplDominateMo",
  "dominate person": "phbsplDominatePe",
  "dragon's breath": "phbsplDragonsBre",
  "dream": "phbsplDream00000",
  "druidcraft": "phbsplDruidcraft",
  "earthquake": "phbsplEarthquake",
  "eldritch blast": "phbsplEldritchBl",
  "elementalism": "phbsplElementali",
  "enhance ability": "phbsplEnhanceAbi",
  "enlarge/reduce": "phbsplEnlargeRed",
  "ensnaring strike": "phbsplEnsnaringS",
  "entangle": "phbsplEntangle00",
  "enthrall": "phbsplEnthrall00",
  "etherealness": "phbsplEtherealne",
  "expeditious retreat": "phbsplExpeditiou",
  "eyebite": "phbsplEyebite000",
  "fabricate": "phbsplFabricate0",
  "faerie fire": "phbsplFaerieFire",
  "faithful hound": "phbFaithfulHound",
  "false life": "phbsplFalseLife0",
  "fear": "phbsplFear000000",
  "feather fall": "phbsplFeatherFal",
  "find familiar": "phbsplFindFamili",
  "find steed": "phbsplFindSteed0",
  "find the path": "phbsplFindthePat",
  "find traps": "phbsplFindTraps0",
  "finger of death": "phbsplFingerofDe",
  "fire bolt": "phbsplFireBolt00",
  "fire shield": "phbsplFireShield",
  "fire storm": "phbsplFireStorm0",
  "fireball": "phbsplFireball00",
  "flame blade": "phbsplFlameBlade",
  "flame strike": "phbsplFlameStrik",
  "flaming sphere": "phbsplFlamingSph",
  "flesh to stone": "phbsplFleshtoSto",
  "floating disk": "phbsplTensersFlo",
  "fly": "phbsplFly0000000",
  "fog cloud": "phbsplFogCloud00",
  "forbiddance": "phbsplForbiddanc",
  "forcecage": "phbsplForcecage0",
  "foresight": "phbsplForesight0",
  "freedom of movement": "phbsplFreedomofM",
  "freezing sphere": "phbsplOtilukesFr",
  "gaseous form": "phbsplGaseousFor",
  "gate": "phbsplGate000000",
  "geas": "phbsplGeas000000",
  "gentle repose": "phbsplGentleRepo",
  "giant insect": "phbsplGiantInsec",
  "glibness": "phbsplGlibness00",
  "globe of invulnerability": "phbsplGlobeofInv",
  "glyph of warding": "phbsplGlyphofWar",
  "goodberry": "phbsplGoodberry0",
  "grease": "phbsplGrease0000",
  "greater invisibility": "phbsplGreaterInv",
  "greater restoration": "phbsplGreaterRes",
  "guardian of faith": "phbsplGuardianof",
  "guards and wards": "phbsplGuardsandW",
  "guidance": "phbsplGuidance00",
  "guiding bolt": "phbsplGuidingBol",
  "gust of wind": "phbsplGustofWind",
  "hallow": "phbsplHallow0000",
  "hallucinatory terrain": "phbsplHallucinat",
  "harm": "phbsplHarm000000",
  "haste": "phbsplHaste00000",
  "heal": "phbsplHeal000000",
  "healing word": "phbsplHealingWor",
  "heat metal": "phbsplHeatMetal0",
  "hellish rebuke": "phbsplHellishReb",
  "heroes' feast": "phbsplHeroesFeas",
  "heroism": "phbsplHeroism000",
  "hex": "phbsplHex0000000",
  "hideous laughter": "phbsplTashasHide",
  "hold monster": "phbsplHoldMonste",
  "hold person": "phbsplHoldPerson",
  "holy aura": "phbsplHolyAura00",
  "hunter's mark": "phbsplHuntersMar",
  "hypnotic pattern": "phbsplHypnoticPa",
  "ice knife": "phbsplIceKnife00",
  "ice storm": "phbsplIceStorm00",
  "identify": "phbsplIdentify00",
  "illusory script": "phbsplIllusorySc",
  "imprisonment": "phbsplImprisonme",
  "incendiary cloud": "phbsplIncendiary",
  "inflict wounds": "phbsplInflictWou",
  "insect plague": "phbsplInsectPlag",
  "instant summons": "phbsplDrawmijsIn",
  "invisibility": "phbsplInvisibili",
  "irresistible dance": "phbsplOttosIrres",
  "jump": "phbsplJump000000",
  "knock": "phbsplKnock00000",
  "legend lore": "phbsplLegendLore",
  "lesser restoration": "phbsplLesserRest",
  "levitate": "phbsplLevitate00",
  "light": "phbsplLight00000",
  "lightning bolt": "phbsplLightningB",
  "locate animals or plants": "phbsplLocateAnim",
  "locate creature": "phbsplLocateCrea",
  "locate object": "phbsplLocateObje",
  "longstrider": "phbsplLongstride",
  "mage armor": "phbsplMageArmor0",
  "mage hand": "phbsplMageHand00",
  "magic circle": "phbsplMagicCircl",
  "magic jar": "phbsplMagicJar00",
  "magic missile": "phbsplMagicMissi",
  "magic mouth": "phbsplMagicMouth",
  "magic weapon": "phbsplMagicWeapo",
  "magnificent mansion": "phbMagnificentMa",
  "major image": "phbsplMajorImage",
  "mass cure wounds": "phbsplMassCureWo",
  "mass heal": "phbsplMassHeal00",
  "mass healing word": "phbsplMassHealin",
  "mass suggestion": "phbsplMassSugges",
  "maze": "phbsplMaze000000",
  "meld into stone": "phbsplMeldintoSt",
  "mending": "phbsplMending000",
  "message": "phbsplMessage000",
  "meteor swarm": "phbsplMeteorSwar",
  "mind blank": "phbsplMindBlank0",
  "mind spike": "phbsplMindSpike0",
  "minor illusion": "phbsplMinorIllus",
  "mirage arcane": "phbsplMirageArca",
  "mirror image": "phbsplMirrorImag",
  "mislead": "phbsplMislead000",
  "misty step": "phbsplMistyStep0",
  "modify memory": "phbsplModifyMemo",
  "moonbeam": "phbsplMoonbeam00",
  "move earth": "phbsplMoveEarth0",
  "nondetection": "phbsplNondetecti",
  "pass without trace": "phbsplPasswithou",
  "passwall": "phbsplPasswall00",
  "phantasmal force": "phbPhantasmalFor",
  "phantasmal killer": "phbsplPhantasmal",
  "phantom steed": "phbsplPhantomSte",
  "planar ally": "phbsplPlanarAlly",
  "planar binding": "phbsplPlanarBind",
  "plane shift": "phbsplPlaneShift",
  "plant growth": "phbsplPlantGrowt",
  "poison spray": "phbsplPoisonSpra",
  "polymorph": "phbsplPolymorph0",
  "power word heal": "phbsplPowerWordH",
  "power word kill": "phbsplPowerWordK",
  "power word stun": "phbsplPowerWordS",
  "prayer of healing": "phbsplPrayerofHe",
  "prestidigitation": "phbsplPrestidigi",
  "prismatic spray": "phbsplPrismaticS",
  "prismatic wall": "phbsplPrismaticW",
  "private sanctum": "phbPrivateSanctu",
  "produce flame": "phbsplProduceFla",
  "programmed illusion": "phbsplProgrammed",
  "project image": "phbsplProjectIma",
  "protection from energy": "phbProtectionFro",
  "protection from evil and good": "phbEvilAndGoodPr",
  "protection from poison": "phbsplProtection",
  "purify food and drink": "phbsplPurifyFood",
  "raise dead": "phbsplRaiseDead0",
  "ray of enfeeblement": "phbsplRayofEnfee",
  "ray of frost": "phbsplRayofFrost",
  "ray of sickness": "phbsplRayofSickn",
  "regenerate": "phbsplRegenerate",
  "reincarnate": "phbsplReincarnat",
  "remove curse": "phbsplRemoveCurs",
  "resilient sphere": "phbsplOtilukesRe",
  "resistance": "phbsplResistance",
  "resurrection": "phbsplResurrecti",
  "reverse gravity": "phbsplReverseGra",
  "revivify": "phbsplRevivify00",
  "rope trick": "phbsplRopeTrick0",
  "sacred flame": "phbsplSacredFlam",
  "sanctuary": "phbSanctuary0000",
  "scorching ray": "phbsplScorchingR",
  "scrying": "phbsplScrying000",
  "searing smite": "phbsplSearingSmi",
  "secret chest": "phbsplLeomundsSe",
  "see invisibility": "phbsplSeeInvisib",
  "seeming": "phbsplSeeming000",
  "sending": "phbsplSending000",
  "sequester": "phbsplSequester0",
  "shapechange": "phbsplShapechang",
  "shatter": "phbsplShatter000",
  "shield": "phbsplShield0000",
  "shield of faith": "phbsplShieldofFa",
  "shillelagh": "phbsplShillelagh",
  "shining smite": "phbsplShiningSmi",
  "shocking grasp": "phbsplShockingGr",
  "silence": "phbsplSilence000",
  "silent image": "phbsplSilentImag",
  "simulacrum": "phbsplSimulacrum",
  "sleep": "phbsplSleep00000",
  "sleet storm": "phbsplSleetStorm",
  "slow": "phbsplSlow000000",
  "sorcerous burst": "phbsplSorcerousB",
  "spare the dying": "phbsplSparetheDy",
  "speak with animals": "phbsplSpeakwithA",
  "speak with dead": "phbsplSpeakwithD",
  "speak with plants": "phbsplSpeakwithP",
  "spider climb": "phbsplSpiderClim",
  "spike growth": "phbsplSpikeGrowt",
  "spirit guardians": "phbsplSpiritGuar",
  "spiritual weapon": "phbsplSpiritualW",
  "starry wisp": "phbsplStarryWisp",
  "stinking cloud": "phbsplStinkingCl",
  "stone shape": "phbsplStoneShape",
  "stoneskin": "phbsplStoneskin0",
  "storm of vengeance": "phbsplStormofVen",
  "suggestion": "phbsplSuggestion",
  "summon dragon": "phbsplSummonDrag",
  "sunbeam": "phbsplSunbeam000",
  "sunburst": "phbsplSunburst00",
  "symbol": "phbsplSymbol0000",
  "telekinesis": "phbsplTelekinesi",
  "telepathic bond": "phbsplRarysTelep",
  "teleport": "phbsplTeleport00",
  "teleportation circle": "phbsplTeleportat",
  "thaumaturgy": "phbsplThaumaturg",
  "thunderwave": "phbsplThunderwav",
  "time stop": "phbsplTimeStop00",
  "tiny hut": "phbsplLeomundsTi",
  "tongues": "phbsplTongues000",
  "transport via plants": "phbsplTransportv",
  "tree stride": "phbsplTreeStride",
  "true polymorph": "phbsplTruePolymo",
  "true resurrection": "phbsplTrueResurr",
  "true seeing": "phbsplTrueSeeing",
  "true strike": "phbsplTrueStrike",
  "tsunami": "phbsplTsunami000",
  "unseen servant": "phbsplUnseenServ",
  "vampiric touch": "phbsplVampiricTo",
  "vicious mockery": "phbsplViciousMoc",
  "vitriolic sphere": "phbsplVitriolicS",
  "wall of fire": "phbsplWallofFire",
  "wall of force": "phbsplWallofForc",
  "wall of ice": "phbsplWallofIce0",
  "wall of stone": "phbsplWallofSton",
  "wall of thorns": "phbsplWallofThor",
  "warding bond": "phbsplWardingBon",
  "water breathing": "phbsplWaterBreat",
  "water walk": "phbsplWaterWalk0",
  "web": "phbsplWeb0000000",
  "weird": "phbsplWeird00000",
  "wind walk": "phbsplWindWalk00",
  "wind wall": "phbsplWindWall00",
  "wish": "phbsplWish000000",
  "word of recall": "phbsplWordofReca",
  "zone of truth": "phbsplZoneofTrut",
};
