// =============================================================================
// compendiumUuidsData - GERADO por `npm run gen:uuids`. NÃO EDITE À MÃO.
// =============================================================================
// Identificadores de documentos dos compêndios do sistema dnd5e (SRD 2024, MIT +
// CC-BY-4.0), extraídos de packs/_source. Apenas ids e nomes - nenhum conteúdo de
// jogo é redistribuído aqui. Consumidos por engine/compendiumUuids.js para montar
// os ItemGrant de níveis FUTUROS (ver o módulo irmão para o porquê).
//
// Cobertura: as 12 classes XPHB (159 features), 12 subclasses SRD
// (58 features), 340 magias, 54 origens,
// 17 talentos e 572 itens de equipamento.
// -----------------------------------------------------------------------------

/** Pacote de compêndio de cada mapa (prefixo do uuid). */
export const PACK_CLASSES = 'Compendium.dnd5e.classes24.Item';
export const PACK_SPELLS = 'Compendium.dnd5e.spells24.Item';
export const PACK_ORIGINS = 'Compendium.dnd5e.origins24.Item';
export const PACK_FEATS = 'Compendium.dnd5e.feats24.Item';
export const PACK_EQUIPMENT = 'Compendium.dnd5e.equipment24.Item';

/** `classId` → _id do documento da CLASSE (pacote classes24). */
export const CLASS_IDS = {
  "barbarian": "phbbrbBarbarian0",
  "bard": "phbbrdBard000000",
  "cleric": "phbclcCleric0000",
  "druid": "phbdrdDruid00000",
  "fighter": "phbftrFighter000",
  "monk": "phbmnkMonk000000",
  "paladin": "phbpdnPaladin000",
  "ranger": "phbrgrRanger0000",
  "rogue": "phbrgeRogue00000",
  "sorcerer": "phbscrSorcerer00",
  "warlock": "phbwlkWarlock000",
  "wizard": "phbwzdWizard0000",
};

/** `classId|nomeDaFeature` → _id (pacote classes24). */
export const CLASS_FEATURE_IDS = {
  "barbarian|brutal strike": "phbbrbBrutalStri",
  "barbarian|danger sense": "phbbrbDangerSens",
  "barbarian|epic boon": "phbbrbEpicBoon00",
  "barbarian|extra attack": "phbbrbExtraAttac",
  "barbarian|fast movement": "phbbrbFastMoveme",
  "barbarian|feral instinct": "phbbrbFeralInsti",
  "barbarian|improved brutal strike": "phbbrbImpBrutalS",
  "barbarian|improved brutal strike (2)": "phbbrbImp2Brutal",
  "barbarian|indomitable might": "phbbrbIndomitabl",
  "barbarian|instinctive pounce": "phbbrbInstinctiv",
  "barbarian|persistent rage": "phbbrbPersistent",
  "barbarian|primal champion": "phbbrbPrimalCham",
  "barbarian|primal knowledge": "phbbrbPrimalKnow",
  "barbarian|rage": "phbbrbRage000000",
  "barbarian|reckless attack": "phbbrbRecklessAt",
  "barbarian|relentless rage": "phbbrbRelentless",
  "barbarian|unarmored defense": "phbbrbUnarmoredD",
  "barbarian|weapon mastery": "phbbrbWeaponMast",
  "bard|bardic inspiration": "phbbrdBardicInsp",
  "bard|countercharm": "phbbrdCountercha",
  "bard|epic boon": "phbbrdEpicBoon00",
  "bard|expertise": "phbbrdExpertise0",
  "bard|font of inspiration": "phbbrdFontOfInsp",
  "bard|jack of all trades": "phbbrdJackOfAllT",
  "bard|magical secrets": "phbbrdMagicalSec",
  "bard|spellcasting": "phbbrdSpellcasti",
  "bard|superior inspiration": "phbbrdSuperiorIn",
  "bard|words of creation": "phbbrdWordsOfCre",
  "cleric|blessed strikes": "phbclcBlessedStr",
  "cleric|blessed strikes: divine strike": "phbDivineStrike0",
  "cleric|blessed strikes: potent spellcasting": "phbClcPotentSpel",
  "cleric|channel divinity": "phbclcChannelDiv",
  "cleric|divine intervention": "phbclcDivineInte",
  "cleric|divine order": "phbclcDivineOrde",
  "cleric|divine order: protector": "phbDivineOrderPr",
  "cleric|divine order: thaumaturge": "phbDivineOrderTh",
  "cleric|epic boon": "phbclcEpicBoon00",
  "cleric|greater divine intervention": "phbclcGreaterDiv",
  "cleric|improved blessed strikes": "phbclcImprovedBl",
  "cleric|sear undead": "phbclcSearUndead",
  "cleric|spellcasting": "phbclcSpellcasti",
  "druid|archdruid": "phbdrdArchdruid0",
  "druid|beast spells": "phbdrdBeastSpell",
  "druid|druidic": "phbdrdDruidic000",
  "druid|elemental fury": "phbdrdElementalF",
  "druid|elemental fury: potent spellcasting": "phbFuryPotentSpe",
  "druid|elemental fury: primal strike": "phbFuryPrimalStr",
  "druid|epic boon": "phbdrdEpicBoon00",
  "druid|improved elemental fury": "phbdrdImprovedEl",
  "druid|primal order": "phbdrdPrimalOrde",
  "druid|primal order: magician": "phbPrimalOrderMa",
  "druid|primal order: warden": "phbPrimalOrderWa",
  "druid|spellcasting": "phbdrdSpellcasti",
  "druid|wild companion": "phbdrdWildCompan",
  "druid|wild resurgence": "phbdrdWildResurg",
  "druid|wild shape": "phbdrdWildShape0",
  "fighter|action surge": "phbftrActionSurg",
  "fighter|epic boon": "phbftrEpicBoon00",
  "fighter|extra attack": "phbftrExtraAttac",
  "fighter|fighting style": "phbftrFightingSt",
  "fighter|indomitable": "phbftrIndomitabl",
  "fighter|second wind": "phbftrSecondWind",
  "fighter|studied attacks": "phbftrStudiedAtt",
  "fighter|tactical master": "phbftrTacticalMa",
  "fighter|tactical mind": "phbftrTacticalMi",
  "fighter|tactical shift": "phbftrTacticalSh",
  "fighter|three extra attacks": "phbftrThreeExtra",
  "fighter|two extra attacks": "phbftrTwoExtraAt",
  "fighter|weapon mastery": "phbftrWeaponMast",
  "monk|acrobatic movement": "phbmnkAcrobaticM",
  "monk|body and mind": "phbmnkBodyAndMin",
  "monk|deflect attacks": "phbmnkDeflectAtt",
  "monk|deflect energy": "phbmnkDeflectEne",
  "monk|disciplined survivor": "phbmnkDiscipline",
  "monk|empowered strikes": "phbmnkEmpoweredS",
  "monk|epic boon": "phbmnkEpicBoon00",
  "monk|evasion": "phbmnkEvasion000",
  "monk|extra attack": "phbmnkExtraAttac",
  "monk|heightened focus": "phbmnkHeightened",
  "monk|martial arts": "phbmnkMartialArt",
  "monk|monk's focus": "phbmnkMonksFocus",
  "monk|perfect focus": "phbmnkPerfectFoc",
  "monk|slow fall": "phbmnkSlowFall00",
  "monk|stunning strike": "phbmnkStunningSt",
  "monk|superior defense": "phbmnkSuperiorDe",
  "monk|unarmored defense": "phbmnkUnarmoredD",
  "monk|unarmored movement": "phbmnkUnarmoredM",
  "monk|uncanny metabolism": "phbmnkUncannyMet",
  "paladin|abjure foes": "phbpdnAbjureFoes",
  "paladin|aura expansion": "phbpdnAuraExpans",
  "paladin|aura of courage": "phbpdnCourageAur",
  "paladin|aura of protection": "phbpdnProtection",
  "paladin|blessed warrior": "phbfstBlessedWar",
  "paladin|channel divinity": "phbpdnChannelDiv",
  "paladin|epic boon": "phbpdnEpicBoon00",
  "paladin|extra attack": "phbpdnExtraAttac",
  "paladin|faithful steed": "phbpdnFaithfulSt",
  "paladin|fighting style": "phbpdnFightingSt",
  "paladin|lay on hands": "phbpdnLayOnHands",
  "paladin|paladin's smite": "phbpdnPaladinsSm",
  "paladin|radiant strikes": "phbpdnRadiantStr",
  "paladin|restoring touch": "phbpdnRestoringT",
  "paladin|spellcasting": "phbpdnSpellcasti",
  "paladin|weapon mastery": "phbpdnWeaponMast",
  "ranger|deft explorer": "phbrgrDeftExplor",
  "ranger|druidic warrior": "phbfstDruidicWar",
  "ranger|epic boon": "phbrgrEpicBoon00",
  "ranger|expertise": "phbrgrExpertise0",
  "ranger|extra attack": "phbrgrExtraAttac",
  "ranger|favored enemy": "phbrgrFavoredEne",
  "ranger|feral senses": "phbrgrFeralSense",
  "ranger|fighting style": "phbrgrFightingSt",
  "ranger|foe slayer": "phbrgrFoeSlayer0",
  "ranger|nature's veil": "phbrgrNaturesVei",
  "ranger|precise hunter": "phbrgrPreciseHun",
  "ranger|relentless hunter": "phbrgrRelentless",
  "ranger|roving": "phbrgrRoving0000",
  "ranger|spellcasting": "phbrgrSpellcasti",
  "ranger|tireless": "phbrgrTireless00",
  "ranger|weapon mastery": "phbrgrWeaponMast",
  "rogue|cunning action": "phbrgeCunningAct",
  "rogue|cunning strike": "phbrgeCunningStr",
  "rogue|devious strikes": "phbrgeDeviousStr",
  "rogue|elusive": "phbrgeElusive000",
  "rogue|epic boon": "phbrgeEpicBoon00",
  "rogue|evasion": "phbrgeEvasion000",
  "rogue|expertise": "phbrgeExpertise0",
  "rogue|improved cunning strike": "phbrgeImprovedCu",
  "rogue|reliable talent": "phbrgeReliableTa",
  "rogue|slippery mind": "phbrgeSlipperyMi",
  "rogue|sneak attack": "phbrgeSneakAttac",
  "rogue|steady aim": "phbrgeSteadyAim0",
  "rogue|stroke of luck": "phbrgeStrokeOfLu",
  "rogue|thieves' cant": "phbrgeThievesCan",
  "rogue|uncanny dodge": "phbrgeUncannyDod",
  "rogue|weapon mastery": "phbrgeWeaponMast",
  "sorcerer|arcane apotheosis": "phbscrArcaneApot",
  "sorcerer|epic boon": "phbscrEpicBoon00",
  "sorcerer|font of magic": "phbscrFontOfMagi",
  "sorcerer|innate sorcery": "phbscrInnateSorc",
  "sorcerer|metamagic": "phbscrMetamagic0",
  "sorcerer|sorcerous restoration": "phbscrSorcerousR",
  "sorcerer|sorcery incarnate": "phbscrSorceryInc",
  "sorcerer|spellcasting": "phbscrSpellcasti",
  "warlock|contact patron": "phbwlkContactPat",
  "warlock|eldritch invocations": "phbwlkEldritchIn",
  "warlock|eldritch master": "phbwlkEldritchMa",
  "warlock|epic boon": "phbwlkEpicBoon00",
  "warlock|magical cunning": "phbwlkMagicalCun",
  "warlock|mystic arcanum": "phbwlkMysticArca",
  "warlock|pact magic": "phbwlkPactMagic0",
  "wizard|arcane recovery": "phbwzdArcaneReco",
  "wizard|epic boon": "phbwzdEpicBoon00",
  "wizard|memorize spell": "phbwzdMemorizeSp",
  "wizard|ritual adept": "phbwzdRitualAdep",
  "wizard|scholar": "phbwzdScholar000",
  "wizard|signature spells": "phbwzdSignatureS",
  "wizard|spell mastery": "phbwzdSpellMaste",
  "wizard|spellcasting": "phbwzdSpellcasti",
};

/** `classId|nomeDaSubclasse` → _id (pacote classes24). */
export const SUBCLASS_IDS = {
  "barbarian|path of the berserker": "phbbrbBerserker0",
  "bard|college of lore": "phbbrdLore000000",
  "cleric|life domain": "phbclcLifeDomain",
  "druid|circle of the land": "phbdrdCirland000",
  "fighter|champion": "phbftrChampion00",
  "monk|warrior of the open hand": "phbmnkOpenHandWa",
  "paladin|oath of devotion": "phbpdnOathOfDevo",
  "ranger|hunter": "phbrgrHunter0000",
  "rogue|thief": "phbrgeThief00000",
  "sorcerer|draconic sorcery": "phbscrDraconicSo",
  "warlock|fiend patron": "phbwlkFiendPatro",
  "wizard|evoker": "phbwzdEvoker0000",
};

/** `classId|nomeDaSubclasse|nomeDaFeature` → _id (pacote classes24). */
export const SUBCLASS_FEATURE_IDS = {
  "barbarian|path of the berserker|frenzy": "phbbrbFrenzy0000",
  "barbarian|path of the berserker|intimidating presence": "phbbrbIntimidati",
  "barbarian|path of the berserker|mindless rage": "phbbrbMindlessRa",
  "barbarian|path of the berserker|retaliation": "phbbrbRetaliatio",
  "bard|college of lore|bonus proficiencies": "phbbrdBonusProfi",
  "bard|college of lore|cutting words": "phbbrdCuttingWor",
  "bard|college of lore|magical discoveries": "phbbrdMagicalDis",
  "bard|college of lore|peerless skill": "phbbrdPeerlessSk",
  "cleric|life domain|blessed healer": "phbclcBlessedHea",
  "cleric|life domain|disciple of life": "phbclcDiscipleOf",
  "cleric|life domain|life domain spells": "phbclcLifeSpells",
  "cleric|life domain|preserve life": "phbclcPreserveLi",
  "cleric|life domain|supreme healing": "phbclcSupremeHea",
  "druid|circle of the land|circle of the land spells": "phbdrdLandSpells",
  "druid|circle of the land|land's aid": "phbdrdLandsAid00",
  "druid|circle of the land|natural recovery": "phbdrdNaturalRec",
  "druid|circle of the land|nature's sanctuary": "phbdrdNaturesSan",
  "druid|circle of the land|nature's ward": "phbdrdNaturesWar",
  "fighter|champion|additional fighting style": "phbftrAdditional",
  "fighter|champion|heroic warrior": "phbftrHeroicWarr",
  "fighter|champion|improved critical": "phbftrImprovedCr",
  "fighter|champion|remarkable athlete": "phbftrRemarkable",
  "fighter|champion|superior critical": "phbftrSuperiorCr",
  "fighter|champion|survivor": "phbftrSurvivor00",
  "monk|warrior of the open hand|fleet step": "phbmnkFleetStep0",
  "monk|warrior of the open hand|open hand technique": "phbmnkOpenHandTe",
  "monk|warrior of the open hand|quivering palm": "phbmnkQuiveringP",
  "monk|warrior of the open hand|wholeness of body": "phbmnkWholenessO",
  "paladin|oath of devotion|aura of devotion": "phbpdnDevotionAu",
  "paladin|oath of devotion|holy nimbus": "phbpdnHolyNimbus",
  "paladin|oath of devotion|oath of devotion spells": "phbpdnDevotionSp",
  "paladin|oath of devotion|sacred weapon": "phbpdnSacredWeap",
  "paladin|oath of devotion|smite of protection": "phbpdnSmiteOfPro",
  "ranger|hunter|defensive tactics": "phbrgrDefensiveT",
  "ranger|hunter|hunter's lore": "phbrgrHuntersLor",
  "ranger|hunter|hunter's prey": "phbrgrHuntersPre",
  "ranger|hunter|superior hunter's defense": "phbrgrSuperiorDe",
  "ranger|hunter|superior hunter's prey": "phbrgrSuperiorHu",
  "rogue|thief|fast hands": "phbrgeFastHands0",
  "rogue|thief|second-story work": "phbrgeSecondstor",
  "rogue|thief|supreme sneak": "phbrgeSupremeSne",
  "rogue|thief|thief's reflexes": "phbrgeThiefsRefl",
  "rogue|thief|use magic device": "phbrgeUseMagicDe",
  "sorcerer|draconic sorcery|draconic resilience": "phbscrDraconicRe",
  "sorcerer|draconic sorcery|draconic spells": "phbscrDraconicSp",
  "sorcerer|draconic sorcery|dragon companion": "phbscrDragonComp",
  "sorcerer|draconic sorcery|dragon wings": "phbscrDragonWing",
  "sorcerer|draconic sorcery|elemental affinity": "phbscrElementalA",
  "warlock|fiend patron|dark one's blessing": "phbwlkDarkOnesBl",
  "warlock|fiend patron|dark one's own luck": "phbwlkDarkOnesOw",
  "warlock|fiend patron|fiend spells": "phbwlkFiendSpell",
  "warlock|fiend patron|fiendish resilience": "phbwlkFiendishRe",
  "warlock|fiend patron|hurl through hell": "phbwlkHurlThroug",
  "wizard|evoker|empowered evocation": "phbwzdEmpoweredE",
  "wizard|evoker|evocation savant": "phbwzdEvocationS",
  "wizard|evoker|overchannel": "phbwzdOverchanne",
  "wizard|evoker|potent cantrip": "phbwzdPotentCant",
  "wizard|evoker|sculpt spells": "phbwzdSculptSpel",
};

/** `nomeDaMagia` → _id (pacote spells24). */
export const SPELL_IDS = {
  "acid arrow": "phbsplMelfsAcidA",
  "acid splash": "phbsplAcidSplash",
  "aid": "phbsplAid0000000",
  "alarm": "phbsplAlarm00000",
  "alter self": "phbsplAlterSelf0",
  "animal friendship": "phbsplAnimalFrie",
  "animal messenger": "phbsplAnimalMess",
  "animal shapes": "phbsplAnimalShap",
  "animate dead": "phbsplAnimateDea",
  "animate objects": "phbsplAnimateObj",
  "antilife shell": "phbsplAntilifeSh",
  "antimagic field": "phbsplAntimagicF",
  "antipathy/sympathy": "phbsplAntipathyS",
  "arcane eye": "phbsplArcaneEye0",
  "arcane hand": "phbsplBigbysHand",
  "arcane lock": "phbsplArcaneLock",
  "arcane sword": "phbswdMordenkain",
  "arcane vigor": "phbsplArcaneVigo",
  "arcanist's magic aura": "phbsplNystulsMag",
  "astral projection": "phbsplAstralProj",
  "augury": "phbsplAugury0000",
  "aura of life": "phbsplAuraofLife",
  "awaken": "phbsplAwaken0000",
  "bane": "phbsplBane000000",
  "banishment": "phbsplBanishment",
  "barkskin": "phbsplBarkskin00",
  "beacon of hope": "phbsplBeaconofHo",
  "befuddlement": "phbsplBefuddleme",
  "bestow curse": "phbsplBestowCurs",
  "black tentacles": "phbsplEvardsBlac",
  "blade barrier": "phbsplBladeBarri",
  "bless": "phbsplBless00000",
  "blight": "phbsplBlight0000",
  "blindness/deafness": "phbsplBlindnessD",
  "blink": "phbsplBlink00000",
  "blur": "phbsplBlur000000",
  "burning hands": "phbsplBurningHan",
  "call lightning": "phbsplCallLightn",
  "calm emotions": "phbsplCalmEmotio",
  "chain lightning": "phbsplChainLight",
  "charm monster": "phbsplCharmMonst",
  "charm person": "phbsplCharmPerso",
  "chill touch": "phbsplChillTouch",
  "chromatic orb": "phbsplChromaticO",
  "circle of death": "phbsplCircleofDe",
  "clairvoyance": "phbsplClairvoyan",
  "clone": "phbsplClone00000",
  "cloudkill": "phbsplCloudkill0",
  "color spray": "phbsplColorSpray",
  "command": "phbsplCommand000",
  "commune": "phbsplCommune000",
  "commune with nature": "phbsplCommunewit",
  "comprehend languages": "phbsplComprehend",
  "compulsion": "phbsplCompulsion",
  "cone of cold": "phbsplConeofCold",
  "confusion": "phbsplConfusion0",
  "conjure animals": "phbsplConjureAni",
  "conjure celestial": "phbsplConjureCel",
  "conjure elemental": "phbsplConjureEle",
  "conjure fey": "phbsplConjureFey",
  "conjure minor elementals": "phbsplConjureMin",
  "conjure woodland beings": "phbsplConjureWoo",
  "contact other plane": "phbsplContactOth",
  "contagion": "phbsplContagion0",
  "contingency": "phbsplContingenc",
  "continual flame": "phbsplContinualF",
  "control water": "phbsplControlWat",
  "control weather": "phbsplControlWea",
  "counterspell": "phbsplCounterspe",
  "create food and water": "phbsplCreateFood",
  "create or destroy water": "phbsplCreateorDe",
  "create undead": "phbsplCreateUnde",
  "creation": "phbsplCreation00",
  "cure wounds": "phbsplCureWounds",
  "dancing lights": "phbsplDancingLig",
  "darkness": "phbsplDarkness00",
  "darkvision": "phbsplDarkvision",
  "daylight": "phbsplDaylight00",
  "death ward": "phbsplDeathWard0",
  "delayed blast fireball": "phbsplDelayedBla",
  "demiplane": "phbsplDemiplane0",
  "detect evil and good": "phbsplDetectEvil",
  "detect magic": "phbsplDetectMagi",
  "detect poison and disease": "phbsplDetectPois",
  "detect thoughts": "phbsplDetectThou",
  "dimension door": "phbsplDimensionD",
  "disguise self": "phbsplDisguiseSe",
  "disintegrate": "phbsplDisintegra",
  "dispel evil and good": "phbsplDispelEvil",
  "dispel magic": "phbsplDispelMagi",
  "dissonant whispers": "phbsplDissonantW",
  "divination": "phbsplDivination",
  "divine favor": "phbsplDivineFavo",
  "divine smite": "phbsplDivineSmit",
  "divine word": "phbsplDivineWord",
  "dominate beast": "phbsplDominateBe",
  "dominate monster": "phbsplDominateMo",
  "dominate person": "phbsplDominatePe",
  "dragon's breath": "phbsplDragonsBre",
  "dream": "phbsplDream00000",
  "druidcraft": "phbsplDruidcraft",
  "earthquake": "phbsplEarthquake",
  "eldritch blast": "phbsplEldritchBl",
  "elementalism": "phbsplElementali",
  "enhance ability": "phbsplEnhanceAbi",
  "enlarge/reduce": "phbsplEnlargeRed",
  "ensnaring strike": "phbsplEnsnaringS",
  "entangle": "phbsplEntangle00",
  "enthrall": "phbsplEnthrall00",
  "etherealness": "phbsplEtherealne",
  "expeditious retreat": "phbsplExpeditiou",
  "eyebite": "phbsplEyebite000",
  "fabricate": "phbsplFabricate0",
  "faerie fire": "phbsplFaerieFire",
  "faithful hound": "phbFaithfulHound",
  "false life": "phbsplFalseLife0",
  "fear": "phbsplFear000000",
  "feather fall": "phbsplFeatherFal",
  "find familiar": "phbsplFindFamili",
  "find steed": "phbsplFindSteed0",
  "find the path": "phbsplFindthePat",
  "find traps": "phbsplFindTraps0",
  "finger of death": "phbsplFingerofDe",
  "fire bolt": "phbsplFireBolt00",
  "fire shield": "phbsplFireShield",
  "fire storm": "phbsplFireStorm0",
  "fireball": "phbsplFireball00",
  "flame blade": "phbsplFlameBlade",
  "flame strike": "phbsplFlameStrik",
  "flaming sphere": "phbsplFlamingSph",
  "flesh to stone": "phbsplFleshtoSto",
  "floating disk": "phbsplTensersFlo",
  "fly": "phbsplFly0000000",
  "fog cloud": "phbsplFogCloud00",
  "forbiddance": "phbsplForbiddanc",
  "forcecage": "phbsplForcecage0",
  "foresight": "phbsplForesight0",
  "freedom of movement": "phbsplFreedomofM",
  "freezing sphere": "phbsplOtilukesFr",
  "gaseous form": "phbsplGaseousFor",
  "gate": "phbsplGate000000",
  "geas": "phbsplGeas000000",
  "gentle repose": "phbsplGentleRepo",
  "giant insect": "phbsplGiantInsec",
  "glibness": "phbsplGlibness00",
  "globe of invulnerability": "phbsplGlobeofInv",
  "glyph of warding": "phbsplGlyphofWar",
  "goodberry": "phbsplGoodberry0",
  "grease": "phbsplGrease0000",
  "greater invisibility": "phbsplGreaterInv",
  "greater restoration": "phbsplGreaterRes",
  "guardian of faith": "phbsplGuardianof",
  "guards and wards": "phbsplGuardsandW",
  "guidance": "phbsplGuidance00",
  "guiding bolt": "phbsplGuidingBol",
  "gust of wind": "phbsplGustofWind",
  "hallow": "phbsplHallow0000",
  "hallucinatory terrain": "phbsplHallucinat",
  "harm": "phbsplHarm000000",
  "haste": "phbsplHaste00000",
  "heal": "phbsplHeal000000",
  "healing word": "phbsplHealingWor",
  "heat metal": "phbsplHeatMetal0",
  "hellish rebuke": "phbsplHellishReb",
  "heroes' feast": "phbsplHeroesFeas",
  "heroism": "phbsplHeroism000",
  "hex": "phbsplHex0000000",
  "hideous laughter": "phbsplTashasHide",
  "hold monster": "phbsplHoldMonste",
  "hold person": "phbsplHoldPerson",
  "holy aura": "phbsplHolyAura00",
  "hunter's mark": "phbsplHuntersMar",
  "hypnotic pattern": "phbsplHypnoticPa",
  "ice knife": "phbsplIceKnife00",
  "ice storm": "phbsplIceStorm00",
  "identify": "phbsplIdentify00",
  "illusory script": "phbsplIllusorySc",
  "imprisonment": "phbsplImprisonme",
  "incendiary cloud": "phbsplIncendiary",
  "inflict wounds": "phbsplInflictWou",
  "insect plague": "phbsplInsectPlag",
  "instant summons": "phbsplDrawmijsIn",
  "invisibility": "phbsplInvisibili",
  "irresistible dance": "phbsplOttosIrres",
  "jump": "phbsplJump000000",
  "knock": "phbsplKnock00000",
  "legend lore": "phbsplLegendLore",
  "lesser restoration": "phbsplLesserRest",
  "levitate": "phbsplLevitate00",
  "light": "phbsplLight00000",
  "lightning bolt": "phbsplLightningB",
  "locate animals or plants": "phbsplLocateAnim",
  "locate creature": "phbsplLocateCrea",
  "locate object": "phbsplLocateObje",
  "longstrider": "phbsplLongstride",
  "mage armor": "phbsplMageArmor0",
  "mage hand": "phbsplMageHand00",
  "magic circle": "phbsplMagicCircl",
  "magic jar": "phbsplMagicJar00",
  "magic missile": "phbsplMagicMissi",
  "magic mouth": "phbsplMagicMouth",
  "magic weapon": "phbsplMagicWeapo",
  "magnificent mansion": "phbMagnificentMa",
  "major image": "phbsplMajorImage",
  "mass cure wounds": "phbsplMassCureWo",
  "mass heal": "phbsplMassHeal00",
  "mass healing word": "phbsplMassHealin",
  "mass suggestion": "phbsplMassSugges",
  "maze": "phbsplMaze000000",
  "meld into stone": "phbsplMeldintoSt",
  "mending": "phbsplMending000",
  "message": "phbsplMessage000",
  "meteor swarm": "phbsplMeteorSwar",
  "mind blank": "phbsplMindBlank0",
  "mind spike": "phbsplMindSpike0",
  "minor illusion": "phbsplMinorIllus",
  "mirage arcane": "phbsplMirageArca",
  "mirror image": "phbsplMirrorImag",
  "mislead": "phbsplMislead000",
  "misty step": "phbsplMistyStep0",
  "modify memory": "phbsplModifyMemo",
  "moonbeam": "phbsplMoonbeam00",
  "move earth": "phbsplMoveEarth0",
  "nondetection": "phbsplNondetecti",
  "pass without trace": "phbsplPasswithou",
  "passwall": "phbsplPasswall00",
  "phantasmal force": "phbPhantasmalFor",
  "phantasmal killer": "phbsplPhantasmal",
  "phantom steed": "phbsplPhantomSte",
  "planar ally": "phbsplPlanarAlly",
  "planar binding": "phbsplPlanarBind",
  "plane shift": "phbsplPlaneShift",
  "plant growth": "phbsplPlantGrowt",
  "poison spray": "phbsplPoisonSpra",
  "polymorph": "phbsplPolymorph0",
  "power word heal": "phbsplPowerWordH",
  "power word kill": "phbsplPowerWordK",
  "power word stun": "phbsplPowerWordS",
  "prayer of healing": "phbsplPrayerofHe",
  "prestidigitation": "phbsplPrestidigi",
  "prismatic spray": "phbsplPrismaticS",
  "prismatic wall": "phbsplPrismaticW",
  "private sanctum": "phbPrivateSanctu",
  "produce flame": "phbsplProduceFla",
  "programmed illusion": "phbsplProgrammed",
  "project image": "phbsplProjectIma",
  "protection from energy": "phbProtectionFro",
  "protection from evil and good": "phbEvilAndGoodPr",
  "protection from poison": "phbsplProtection",
  "purify food and drink": "phbsplPurifyFood",
  "raise dead": "phbsplRaiseDead0",
  "ray of enfeeblement": "phbsplRayofEnfee",
  "ray of frost": "phbsplRayofFrost",
  "ray of sickness": "phbsplRayofSickn",
  "regenerate": "phbsplRegenerate",
  "reincarnate": "phbsplReincarnat",
  "remove curse": "phbsplRemoveCurs",
  "resilient sphere": "phbsplOtilukesRe",
  "resistance": "phbsplResistance",
  "resurrection": "phbsplResurrecti",
  "reverse gravity": "phbsplReverseGra",
  "revivify": "phbsplRevivify00",
  "rope trick": "phbsplRopeTrick0",
  "sacred flame": "phbsplSacredFlam",
  "sanctuary": "phbSanctuary0000",
  "scorching ray": "phbsplScorchingR",
  "scrying": "phbsplScrying000",
  "searing smite": "phbsplSearingSmi",
  "secret chest": "phbsplLeomundsSe",
  "see invisibility": "phbsplSeeInvisib",
  "seeming": "phbsplSeeming000",
  "sending": "phbsplSending000",
  "sequester": "phbsplSequester0",
  "shapechange": "phbsplShapechang",
  "shatter": "phbsplShatter000",
  "shield": "phbsplShield0000",
  "shield of faith": "phbsplShieldofFa",
  "shillelagh": "phbsplShillelagh",
  "shining smite": "phbsplShiningSmi",
  "shocking grasp": "phbsplShockingGr",
  "silence": "phbsplSilence000",
  "silent image": "phbsplSilentImag",
  "simulacrum": "phbsplSimulacrum",
  "sleep": "phbsplSleep00000",
  "sleet storm": "phbsplSleetStorm",
  "slow": "phbsplSlow000000",
  "sorcerous burst": "phbsplSorcerousB",
  "spare the dying": "phbsplSparetheDy",
  "speak with animals": "phbsplSpeakwithA",
  "speak with dead": "phbsplSpeakwithD",
  "speak with plants": "phbsplSpeakwithP",
  "spider climb": "phbsplSpiderClim",
  "spike growth": "phbsplSpikeGrowt",
  "spirit guardians": "phbsplSpiritGuar",
  "spiritual weapon": "phbsplSpiritualW",
  "starry wisp": "phbsplStarryWisp",
  "stinking cloud": "phbsplStinkingCl",
  "stone shape": "phbsplStoneShape",
  "stoneskin": "phbsplStoneskin0",
  "storm of vengeance": "phbsplStormofVen",
  "suggestion": "phbsplSuggestion",
  "summon dragon": "phbsplSummonDrag",
  "sunbeam": "phbsplSunbeam000",
  "sunburst": "phbsplSunburst00",
  "symbol": "phbsplSymbol0000",
  "telekinesis": "phbsplTelekinesi",
  "telepathic bond": "phbsplRarysTelep",
  "teleport": "phbsplTeleport00",
  "teleportation circle": "phbsplTeleportat",
  "thaumaturgy": "phbsplThaumaturg",
  "thunderwave": "phbsplThunderwav",
  "time stop": "phbsplTimeStop00",
  "tiny hut": "phbsplLeomundsTi",
  "tongues": "phbsplTongues000",
  "transport via plants": "phbsplTransportv",
  "tree stride": "phbsplTreeStride",
  "true polymorph": "phbsplTruePolymo",
  "true resurrection": "phbsplTrueResurr",
  "true seeing": "phbsplTrueSeeing",
  "true strike": "phbsplTrueStrike",
  "tsunami": "phbsplTsunami000",
  "unseen servant": "phbsplUnseenServ",
  "vampiric touch": "phbsplVampiricTo",
  "vicious mockery": "phbsplViciousMoc",
  "vitriolic sphere": "phbsplVitriolicS",
  "wall of fire": "phbsplWallofFire",
  "wall of force": "phbsplWallofForc",
  "wall of ice": "phbsplWallofIce0",
  "wall of stone": "phbsplWallofSton",
  "wall of thorns": "phbsplWallofThor",
  "warding bond": "phbsplWardingBon",
  "water breathing": "phbsplWaterBreat",
  "water walk": "phbsplWaterWalk0",
  "web": "phbsplWeb0000000",
  "weird": "phbsplWeird00000",
  "wind walk": "phbsplWindWalk00",
  "wind wall": "phbsplWindWall00",
  "wish": "phbsplWish000000",
  "word of recall": "phbsplWordofReca",
  "zone of truth": "phbsplZoneofTrut",
};

/** `nome` → _id (pacote origins24: espécies, seus traços e backgrounds). */
export const ORIGIN_IDS = {
  "acolyte": "phbbgAcolyte0000",
  "adrenaline rush": "phbsptAdrenaline",
  "brave": "phbsptBrave00000",
  "breath weapon": "phbsptBreathWeap",
  "cloud's jaunt": "phbsptCloudsJaun",
  "criminal": "phbbgCriminal000",
  "draconic flight": "phbsptDraconicFl",
  "dragonborn": "phbspDragonborn0",
  "dwarf": "phbspDwarf000000",
  "dwarven resilience": "phbsptDwarvenRes",
  "dwarven toughness": "phbsptDwarvenTou",
  "elf, drow": "phbspDrow0000000",
  "elf, high": "phbspHighElf0000",
  "elf, wood": "phbspWoodElf0000",
  "elven lineage, drow": "phbsptDrowElfLin",
  "elven lineage, high elf": "phbsptHighElfLin",
  "elven lineage, wood elf": "phbsptWoodElfLin",
  "fey ancestry": "phbsptFeyAncestr",
  "fiendish legacy, abyssal": "phbsptAbyssalLeg",
  "fiendish legacy, chthonic": "phbsptChthonicLe",
  "fiendish legacy, infernal": "phbsptInfernalLe",
  "fire's burn": "phbsptFiresBurn0",
  "frost's chill": "phbsptFrostsChil",
  "giant ancestry": "phbsptGiantAnces",
  "gnome, forest": "phbspForestGnome",
  "gnome, rock": "phbspRockGnome00",
  "gnomish cunning": "phbsptGnomishCun",
  "gnomish lineage, forest": "phbsptForestGnom",
  "gnomish lineage, rock": "phbsptRockGnomeL",
  "goliath": "phbspGoliath0000",
  "halfling": "phbspHalfling000",
  "halfling nimbleness": "phbsptHalflingNi",
  "hill's tumble": "phbsptHillsTumbl",
  "human": "phbspHuman000000",
  "keen senses": "phbsptKeenSenses",
  "large form": "phbsptLargeForm0",
  "luck": "phbsptLuck000000",
  "naturally stealthy": "phbsptNaturallyS",
  "orc": "phbspOrc00000000",
  "otherworldly presence": "phbsptOtherworld",
  "powerful build": "phbsptPowerfulBu",
  "relentless endurance": "phbsptRelentless",
  "resourceful": "phbsptResourcefu",
  "sage": "phbbgSage0000000",
  "skillful": "phbsptSkillful00",
  "soldier": "phbbgSoldier0000",
  "stone's endurance": "phbsptStonesEndu",
  "stonecunning": "phbsptStonecunni",
  "storm's thunder": "phbsptStormsThun",
  "tiefling, abyssal": "phbspAbyssalTief",
  "tiefling, chthonic": "phbspChthonicTie",
  "tiefling, infernal": "phbspInfernalTie",
  "trance": "phbsptTrance0000",
  "versatile": "phbsptVersatile0",
};

/** `nomeDoTalento` → _id (pacote feats24). */
export const FEAT_IDS = {
  "ability score improvement": "phbftAbilityScor",
  "alert": "phbftAlert000000",
  "archery": "phbfstArchery000",
  "boon of combat prowess": "phbBoonofCombatP",
  "boon of dimensional travel": "phbBoonofDimensi",
  "boon of fate": "phbBoonofFate000",
  "boon of irresistible offense": "phbBoonofIrresis",
  "boon of spell recall": "phbBoonofSpellRe",
  "boon of the night spirit": "phbBoonoftheNigh",
  "boon of truesight": "phbBoonofTruesig",
  "defense": "phbfstDefense000",
  "grappler": "phbftGrappler000",
  "great weapon fighting": "phbfstGreatWeapo",
  "magic initiate": "phbftMagicInitia",
  "savage attacker": "phbftSavageAttac",
  "skilled": "phbftSkilled0000",
  "two-weapon fighting": "phbfstTwoWeaponF",
};

/** `nomeDoItem` → _id (pacote equipment24). */
export const EQUIPMENT_IDS = {
  "acid": "phbagAcid0000000",
  "activate folding boat": "dmgBoatUtility00",
  "adamantine armor": "dmgAdamantineArm",
  "air ring of elemental command": "dmgAirRingOfElem",
  "alchemist's fire": "phbagAlchemistsF",
  "alchemist's supplies": "phbtulAlchemists",
  "ammunition (varies)": "phbagAmmunitionV",
  "ammunition of slaying": "dmgSlayingAmmuni",
  "ammunition, +1, +2, or +3": "dmgAmmunition12o",
  "amulet": "phbhsyAmuletworn",
  "amulet of health": "dmgAmuletOfHealt",
  "amulet of proof against detection and location": "dmgAmuletOfProof",
  "amulet of the planes": "dmgAmuletOfThePl",
  "animated shield": "dmgAnimatedShiel",
  "antitoxin": "phbagAntitoxin00",
  "apparatus of the crab": "dmgApparatusOfKw",
  "arcane focus (varies)": "phbagArcaneFocus",
  "armor of invulnerability": "dmgArmorOfInvuln",
  "armor of resistance": "dmgArmorOfResist",
  "armor of vulnerability": "dmgArmorOfVulner",
  "armor, +1, +2, or +3": "dmgArmor12or3000",
  "arrow-catching shield": "dmgArrowcatching",
  "arrows": "phbamoArrows0000",
  "assassin's blood": "dmgAssassinsBloo",
  "backpack": "phbagBackpack000",
  "bag of beans": "dmgBagOfBeans000",
  "bag of devouring": "dmgBagOfDevourin",
  "bag of holding": "dmgBagOfHolding0",
  "bagpipes": "phbmusBagpipes00",
  "balance": "dmgDmtBalance000",
  "ball bearings": "phbagBallBearing",
  "barrel": "phbagBarrel00000",
  "basket": "phbagBasket00000",
  "battleaxe": "phbwepBattleaxe0",
  "bead of force": "dmgBeadOfForce00",
  "bead of nourishment": "dmgBeadOfNourish",
  "bedroll": "phbagBedroll0000",
  "bell": "phbagBell0000000",
  "belt of dwarvenkind": "dmgBeltOfDwarven",
  "belt of giant strength": "dmgBeltOfGiantSt",
  "belt of giant strength (cloud)": "dmgcloBeltofGian",
  "belt of giant strength (fire)": "dmgfirBeltofGian",
  "belt of giant strength (frost)": "dmgfroBeltofGian",
  "belt of giant strength (hill)": "dmghilBeltofGian",
  "belt of giant strength (stone)": "dmgstoBeltofGian",
  "belt of giant strength (storm)": "dmgstmBeltofGian",
  "berserker axe": "dmgBerserkerAxe0",
  "blanket": "phbagBlanket0000",
  "block and tackle": "phbagBlockandTac",
  "blowgun": "phbwepBlowgun000",
  "bolts": "phbamoBolts00000",
  "book": "phbagBook0000000",
  "boots of elvenkind": "dmgBootsOfElvenk",
  "boots of levitation": "dmgBootsOfLevita",
  "boots of speed": "dmgBootsOfSpeed0",
  "boots of striding and springing": "dmgBootsOfStridi",
  "boots of the winterlands": "dmgBootsOfTheWin",
  "bottle, glass": "phbagBottleGlass",
  "bowl of commanding water elementals": "dmgBowlOfCommand",
  "bracers of archery": "dmgBracersOfArch",
  "bracers of defense": "dmgBracersOfDefe",
  "brass horn of valhalla": "dmgBrassHornOfVa",
  "brazier of commanding fire elementals": "dmgBrazierOfComm",
  "breastplate": "phbarmBreastplat",
  "brewer's supplies": "phbtulBrewersSup",
  "bronze griffon": "dmgFwpBronzeGrif",
  "bronze horn of valhalla": "dmgBronzeHornOfV",
  "brooch of shielding": "dmgBroochOfShiel",
  "broom of flying": "dmgBroomOfFlying",
  "bucket": "phbagBucket00000",
  "bullets, firearm": "phbamoBulletsFir",
  "bullets, sling": "phbamoBulletsSli",
  "bullseye lantern": "KZUoiZrigDbovEu7",
  "burglar's pack": "phbagBurglarsPac",
  "burnt othur fumes": "dmgBurntOthurFum",
  "calligrapher's supplies": "phbtulCalligraph",
  "caltrops": "phbagCaltrops000",
  "candle": "ts2DfyhdfsR092Td",
  "candle of invocation": "dmgCandleOfInvoc",
  "cape of the mountebank": "dmgCapeOfTheMoun",
  "carpenter's tools": "phbtulCarpenters",
  "carpet of flying": "dmgCarpetOfFlyin",
  "cartographer's tools": "phbtulCartograph",
  "case, crossbow bolt": "phbagCaseCrossbo",
  "case, map or scroll": "phbagCaseMaporSc",
  "censer of controlling air elementals": "dmgCenserOfContr",
  "central pouch": "dmgCentralPouch0",
  "chain": "phbagChain000000",
  "chain mail": "phbarmChainMail0",
  "chain shirt": "phbarmChainShirt",
  "chest": "phbagChest000000",
  "chime of opening": "dmgChimeOfOpenin",
  "circlet of blasting": "dmgCircletOfBlas",
  "clawed gauntlet": "dmgClawedGauntle",
  "climber's kit": "phbagClimbersKit",
  "cloak of arachnida": "dmgCloakOfArachn",
  "cloak of displacement": "dmgCloakOfDispla",
  "cloak of elvenkind": "dmgCloakOfElvenk",
  "cloak of invisibility": "dmgCloakOfInvisi",
  "cloak of protection": "dmgCloakOfProtec",
  "cloak of the bat": "dmgCloakOfTheBat",
  "cloak of the manta ray": "dmgCloakOfTheMan",
  "clothes, fine": "phbagClothesFine",
  "clothes, traveler's": "phbagClothesTrav",
  "club": "phbwepClub000000",
  "cobbler's tools": "phbtulCobblersTo",
  "collapsing roof": "dmgCollapsingRoo",
  "comet": "dmgDmtComet00000",
  "component pouch": "phbagComponentPo",
  "cook's utensils": "phbtulCooksUtens",
  "costume": "phbagCostume0000",
  "crawler mucus": "dmgCarrionCrawle",
  "crowbar": "rvz6gQc3OcOMgIQz",
  "crystal": "phbafcCrystal000",
  "crystal ball": "dmgCrystalBall00",
  "crystal ball of mind reading": "dmgMindReadingCr",
  "crystal ball of telepathy": "dmgTelepathyCrys",
  "crystal ball of true seeing": "dmgTrueSeeingCry",
  "cube of force": "dmgCubeOfForce00",
  "cubic gate": "dmgCubicGate0000",
  "dagger": "phbwepDagger0000",
  "dagger of venom": "dmgDaggerOfVenom",
  "dancing sword": "dmgDancingSword0",
  "dart": "phbwepDart000000",
  "decanter of endless water": "dmgDecanterOfEnd",
  "deck of illusions": "dmgDeckOfIllusio",
  "defender": "dmgDefender00000",
  "demon armor": "dmgDemonArmor000",
  "dice": "phbgstDice000000",
  "dimensional shackles": "dmgDimensionalSh",
  "diplomat's pack": "phbagDiplomatsPa",
  "disguise kit": "phbtulDisguiseKi",
  "donjon": "dmgDmtDonjon0000",
  "dragon orb": "dmgOrbOfDragonki",
  "dragon scale mail": "dmgDragonScaleMa",
  "dragon slayer": "dmgDragonSlayer0",
  "dragonchess": "phbgstDragonches",
  "druidic focus (varies)": "phbagDruidicFocu",
  "drum": "phbmusDrum000000",
  "dulcimer": "phbmusDulcimer00",
  "dungeoneer's pack": "phbagDungeoneers",
  "dust of disappearance": "dmgDustOfDisappe",
  "dust of dryness": "dmgDustOfDryness",
  "dust of sneezing and choking": "dmgDustOfSneezin",
  "dwarven plate": "dmgDwarvenPlate0",
  "dwarven thrower": "dmgDwarvenThrowe",
  "earth ring of elemental command": "dmgEarthRingOfEl",
  "ebony fly": "dmgFwpEbonyFlyRa",
  "efficient quiver": "dmgQuiverOfEhlon",
  "efreeti bottle": "dmgEfreetiBottle",
  "elemental gem": "dmgElementalGem0",
  "elemental gem (blue sapphire)": "dmgBlueElemental",
  "elemental gem (emerald)": "dmgEmeraldElemen",
  "elemental gem (red corundum)": "dmgRedElementalG",
  "elemental gem (yellow diamond)": "dmgYellowElement",
  "elixir of health": "dmgElixirOfHealt",
  "elven chain": "dmgElvenChain000",
  "emblem": "phbhsyEmblemborn",
  "energy bow": "dmgEnergyBow0000",
  "entertainer's pack": "phbagEntertainer",
  "essence of ether": "dmgEssenceOfEthe",
  "euryale": "dmgDmtEuryale000",
  "eversmoking bottle": "dmgEversmokingBo",
  "explorer's pack": "phbagExplorersPa",
  "eyes of charming": "dmgEyesOfCharmin",
  "eyes of minute seeing": "dmgEyesOfMinuteS",
  "eyes of the eagle": "dmgEyesOfTheEagl",
  "falling net": "dmgFallingNet000",
  "fates": "dmgDmtFates00000",
  "feather token": "dmgQuaalsFeather",
  "feather token (anchor)": "dmgAnchorQuaalsF",
  "feather token (bird)": "dmgBirdQuaalsFea",
  "feather token (fan)": "dmgFanQuaalsFeat",
  "feather token (swan boat)": "dmgSwanBoatQuaal",
  "feather token (tree)": "dmgTreeQuaalsFea",
  "feather token (whip)": "dmgWhipQuaalsFea",
  "figurine of wondrous power": "dmgFigurineOfWon",
  "fine clothes": "pjxpIVbJEfOvM240",
  "fire ring of elemental command": "dmgFireRingOfEle",
  "fire-casting statue": "dmgFirecastingSt",
  "flail": "phbwepFlail00000",
  "flame tongue": "dmgFlameTongue00",
  "flames": "dmgDmtFlames0000",
  "flask": "phbagFlask000000",
  "flute": "phbmusFlute00000",
  "folding boat": "dmgFoldingBoat00",
  "fool": "dmgDmtFool000000",
  "forgery kit": "phbtulForgeryKit",
  "frost brand": "dmgFrostBrand000",
  "gauntlets of ogre power": "dmgGauntletsOfOg",
  "gem": "dmgDmtGem0000000",
  "gem of brightness": "dmgGemOfBrightne",
  "gem of seeing": "dmgGemOfSeeing00",
  "giant slayer": "dmgGiantSlayer00",
  "glaive": "phbwepGlaive0000",
  "glamoured studded leather": "dmgGlamouredStud",
  "glassblower's tools": "phbtulGlassblowe",
  "gloves of missile snaring": "dmgGlovesOfMissi",
  "gloves of swimming and climbing": "dmgGlovesOfSwimm",
  "gloves of thievery": "dmgGlovesOfThiev",
  "goggles of night": "dmgGogglesOfNigh",
  "golden lions": "dmgFwpGoldenLion",
  "grappling hook": "phbagGrapplingHo",
  "gray bag of tricks": "dmgBagOfTricks00",
  "greataxe": "phbwepGreataxe00",
  "greatclub": "phbwepGreatclub0",
  "greatsword": "phbwepGreatsword",
  "halberd": "phbwepHalberd000",
  "half plate armor": "phbarmHalfPlateA",
  "hammer of thunderbolts": "dmgHammerOfThund",
  "hand crossbow": "phbwepHandCrossb",
  "handaxe": "phbwepHandaxe000",
  "handy haversack": "dmgHewardsHandyH",
  "hat of disguise": "dmgHatOfDisguise",
  "hat of many spells": "dmgHatOfManySpel",
  "headband of intellect": "dmgHeadbandOfInt",
  "healer's kit": "phbagHealersKit0",
  "heavy crossbow": "phbwepHeavyCross",
  "helm of brilliance": "dmgHelmOfBrillia",
  "helm of comprehending languages": "dmgHelmOfCompreh",
  "helm of telepathy": "dmgHelmOfTelepat",
  "helm of teleportation": "dmgHelmOfTelepor",
  "herbalism kit": "phbtulHerbalismK",
  "hidden pit": "dmgHiddenPit0000",
  "hide armor": "phbarmHideArmor0",
  "holy avenger": "dmgHolyAvenger00",
  "holy symbol (varies)": "phbagHolySymbolV",
  "holy water": "phbagHolyWater00",
  "hooded lantern": "DKYzehYrMUKiFDxt",
  "horn": "phbmusHorn000000",
  "horn of blasting": "dmgHornOfBlastin",
  "horn of valhalla": "dmgHornofValhall",
  "horseshoes of a zephyr": "dmgHorseshoesOfA",
  "horseshoes of speed": "dmgHorseshoesOfS",
  "hunting trap": "phbagHuntingTrap",
  "immovable rod": "dmgImmovableRod0",
  "ink": "vi0j4PYnO596a2L1",
  "ink pen": "uBvsyY44RP4LJLzp",
  "instant fortress": "dmgDaernsInstant",
  "ioun stone": "dmgIounStone0000",
  "ioun stone of absorption": "dmgAbsorptionIou",
  "ioun stone of agility": "dmgAgilityIounSt",
  "ioun stone of awareness": "dmgAwarenessIoun",
  "ioun stone of fortitude": "dmgFortitudeIoun",
  "ioun stone of greater absorption": "dmgGreaterAbsorp",
  "ioun stone of insight": "dmgInsightIounSt",
  "ioun stone of intellect": "dmgIntellectIoun",
  "ioun stone of leadership": "dmgLeadershipIou",
  "ioun stone of mastery": "dmgMasteryIounSt",
  "ioun stone of protection": "dmgProtectionIou",
  "ioun stone of regeneration": "dmgRegnerationIo",
  "ioun stone of reserve": "dmgReserveIounSt",
  "ioun stone of strength": "dmgStrengthIounS",
  "ioun stone of sustenance": "dmgSustenanceIou",
  "iron bands": "dmgIronBandsOfBi",
  "iron flask": "dmgIronFlask0000",
  "iron horn of valhalla": "dmgIronHornOfVal",
  "ivory goats": "dmgFwpIvoryGoats",
  "javelin": "phbwepJavelin000",
  "javelin of lightning": "dmgJavelinOfLigh",
  "jester": "dmgDmtJester0000",
  "jeweler's tools": "phbtulJewelersTo",
  "jug": "phbagJug00000000",
  "key": "dmgDmtKey0000000",
  "knight": "dmgDmtKnight0000",
  "ladder": "phbagLadder00000",
  "lamp": "SMj5QHHkDCdvkx35",
  "lance": "phbwepLance00000",
  "lantern of revealing": "dmgLanternOfReve",
  "lantern, bullseye": "phbagLanternBull",
  "lantern, hooded": "phbagLanternHood",
  "leather armor": "phbarmLeatherArm",
  "leatherworker's tools": "phbtulLeatherwor",
  "left pouch": "dmgLeftPouch0000",
  "light crossbow": "phbwepLightCross",
  "light hammer": "phbwepLightHamme",
  "lock": "phbagLock0000000",
  "long compartment": "dmgLongCompartme",
  "longbow": "phbwepLongbow000",
  "longsword": "phbwepLongsword0",
  "luck blade": "dmgLuckBlade0000",
  "lute": "phbmusLute000000",
  "lyre": "phbmusLyre000000",
  "mace": "phbwepMace000000",
  "mace of disruption": "dmgMaceOfDisrupt",
  "mace of smiting": "dmgMaceOfSmiting",
  "mace of terror": "dmgMaceOfTerror0",
  "magnifying glass": "phbagMagnifyingG",
  "malice": "dmgMalice0000000",
  "manacles": "phbagManacles000",
  "mantle of spell resistance": "dmgMantleOfSpell",
  "manual of bodily health": "dmgManualOfBodil",
  "manual of gainful exercise": "dmgManualOfGainf",
  "manual of golems": "dmgManualOfGolem",
  "manual of quickness of action": "dmgManualOfQuick",
  "map": "phbagMap00000000",
  "map or scroll case": "SKDkrz7KSUIfOnHE",
  "marble elephant": "dmgFwpMarbleElep",
  "marvelous pigments": "dmgNolzursMarvel",
  "mason's tools": "phbtulMasonsTool",
  "maul": "phbwepMaul000000",
  "medallion of thoughts": "dmgMedallionOfTh",
  "midnight tears": "dmgMidnightTears",
  "midsize compartment": "dmgMidsizeCompar",
  "mirror": "SoNpADeVEx2DDZgB",
  "mirror of life trapping": "dmgMirrorOfLifeT",
  "mithral armor": "dmgMithralArmor0",
  "moon": "dmgDmtMoon000000",
  "morningstar": "phbwepMorningsta",
  "musket": "phbwepMusket0000",
  "mysterious deck": "dmgDeckOfManyThi",
  "navigator's tools": "phbtulNavigators",
  "necklace of adaptation": "dmgNecklaceOfAda",
  "necklace of fireballs": "dmgNecklaceOfFir",
  "necklace of prayer beads": "dmgNecklaceOfPra",
  "needles": "phbamoNeedles000",
  "net": "phbagNet00000000",
  "nine lives stealer": "dmgNineLivesStea",
  "oathbow": "dmgOathbow000000",
  "obsidian steed": "dmgFwpObsidianSt",
  "oil": "JpE7eqjwXw95Sai5",
  "oil of etherealness": "dmgOilOfEthereal",
  "oil of sharpness": "dmgOilOfSharpnes",
  "oil of slipperiness": "dmgOilOfSlipperi",
  "oil of taggit": "dmgOilOfTaggit00",
  "onyx dog": "dmgFwpOnyxDogRar",
  "orb": "phbafcOrb0000000",
  "padded armor": "phbarmPaddedArmo",
  "painter's supplies": "phbtulPaintersSu",
  "pale tincture": "dmgPaleTincture0",
  "pan flute": "phbmusPanflute00",
  "paper": "rZATMqE6y9uD3uzz",
  "parchment": "I6wPnS0Z1qcpXjdL",
  "pearl of power": "dmgPearlOfPower0",
  "perfume": "yoRKNd2QddQp1XuX",
  "periapt of health": "dmgPeriaptOfHeal",
  "periapt of proof against poison": "dmgPeriaptOfProo",
  "periapt of wound closure": "dmgPeriaptOfWoun",
  "philter of love": "dmgPhilterOfLove",
  "pike": "phbwepPike000000",
  "pipes of haunting": "dmgPipesOfHaunti",
  "pipes of the sewers": "dmgPipesOfTheSew",
  "pistol": "phbwepPistol0000",
  "plate armor": "phbarmPlateArmor",
  "plate armor of etherealness": "dmgPlateArmorOfE",
  "playing cards": "phbgstPlayingcar",
  "poison, basic": "phbagPoisonBasic",
  "poisoned darts": "dmgPoisonedDarts",
  "poisoned needle": "dmgPoisonedNeedl",
  "poisoner's kit": "phbtulPoisonersK",
  "pole": "phbagPole0000000",
  "portable hole": "dmgPortableHole0",
  "pot, iron": "phbagPotIron0000",
  "potion of animal friendship": "dmgPotionOfAnima",
  "potion of clairvoyance": "dmgPotionOfClair",
  "potion of climbing": "dmgPotionOfClimb",
  "potion of diminution": "dmgPotionOfDimin",
  "potion of flying": "dmgPotionOfFlyin",
  "potion of gaseous form": "dmgPotionOfGaseo",
  "potion of giant strength": "dmgPotionofGiant",
  "potion of giant strength (cloud)": "dmgCloudPotionOf",
  "potion of giant strength (fire)": "dmgFirePotionOfG",
  "potion of giant strength (frost)": "dmgFrostPotionOf",
  "potion of giant strength (hill)": "dmgHillPotionOfG",
  "potion of giant strength (stone)": "dmgStonePotionOf",
  "potion of giant strength (storm)": "dmgStormPotionOf",
  "potion of growth": "dmgPotionOfGrowt",
  "potion of healing": "phbagPotionofHea",
  "potion of healing (greater)": "dmgGreaterPotion",
  "potion of healing (superior)": "dmgSuperiorPotio",
  "potion of healing (supreme)": "dmgSupremePotion",
  "potion of heroism": "dmgPotionOfHeroi",
  "potion of invisibility": "dmgPotionOfInvis",
  "potion of invulnerability": "dmgPotionOfInvul",
  "potion of longevity": "dmgPotionOfLonge",
  "potion of mind reading": "dmgPotionOfMindR",
  "potion of poison": "dmgPotionOfPoiso",
  "potion of resistance": "dmgPotionOfResis",
  "potion of speed": "dmgPotionOfSpeed",
  "potion of vitality": "dmgPotionOfVital",
  "potion of water breathing": "dmgPotionOfWater",
  "potter's tools": "phbtulPottersToo",
  "pouch": "phbagPouch000000",
  "priest's pack": "phbagPriestsPack",
  "purple worm poison": "dmgPurpleWormPoi",
  "puzzle": "dmgDmtPuzzle0000",
  "quarterstaff": "phbwepQuartersta",
  "quarterstaff of the acrobat": "dmgQuarterstaffO",
  "quiver": "phbagQuiver00000",
  "ram, portable": "phbagRamPortable",
  "rapier": "phbwepRapier0000",
  "rations": "llmXULupnKVHUGuE",
  "reliquary": "phbhsyReliquaryh",
  "right pouch": "dmgRightPouch000",
  "ring": "dmgsupRingofResi",
  "ring mail": "phbarmRingMail00",
  "ring of animal influence": "dmgRingOfAnimalI",
  "ring of djinni summoning": "dmgRingOfDjinniS",
  "ring of elemental command": "dmgRingOfElement",
  "ring of evasion": "dmgRingOfEvasion",
  "ring of feather falling": "dmgRingOfFeather",
  "ring of free action": "dmgRingOfFreeAct",
  "ring of invisibility": "dmgRingOfInvisib",
  "ring of jumping": "dmgRingOfJumping",
  "ring of mind shielding": "dmgRingOfMindShi",
  "ring of protection": "dmgRingOfProtect",
  "ring of regeneration": "dmgRingOfRegener",
  "ring of resistance": "dmgRingOfResista",
  "ring of shooting stars": "dmgRingOfShootin",
  "ring of spell storing": "dmgRingOfSpellSt",
  "ring of spell turning": "dmgRingOfSpellTu",
  "ring of swimming": "dmgRingOfSwimmin",
  "ring of telekinesis": "dmgRingOfTelekin",
  "ring of the ram": "dmgRingOfTheRam0",
  "ring of three wishes": "dmgRingOfThreeWi",
  "ring of warmth": "dmgRingOfWarmth0",
  "ring of water walking": "dmgRingOfWaterWa",
  "ring of x-ray vision": "dmgRingOfXrayVis",
  "robe": "jLcAY4Oph8ZEniG2",
  "robe of eyes": "dmgRobeOfEyes000",
  "robe of scintillating colors": "dmgRobeOfScintil",
  "robe of stars": "dmgRobeOfStars00",
  "robe of the archmagi": "dmgRobeOfTheArch",
  "robe of useful items": "dmgRobeOfUsefulI",
  "rod": "phbafcRod0000000",
  "rod of absorption": "dmgRodOfAbsorpti",
  "rod of alertness": "dmgRodOfAlertnes",
  "rod of lordly might": "dmgRodOfLordlyMi",
  "rod of resurrection": "dmgRodOfResurrec",
  "rod of rulership": "dmgRodOfRulershi",
  "rod of security": "dmgRodOfSecurity",
  "rogue": "dmgDmtRogue00000",
  "rolling stone": "dmgRollingStone0",
  "rope": "x8jC9e00t4cUYiKR",
  "rope of climbing": "dmgRopeOfClimbin",
  "rope of entanglement": "dmgRopeOfEntangl",
  "ruin": "dmgDmtRuin000000",
  "rust bag of tricks": "dmgRustBagofTric",
  "sack": "phbagSack0000000",
  "sage": "dmgDmtSage000000",
  "scale mail": "phbarmScaleMail0",
  "scarab of protection": "dmgScarabOfProte",
  "scholar's pack": "phbagScholarsPac",
  "scimitar": "phbwepScimitar00",
  "scimitar of speed": "dmgScimitarOfSpe",
  "scroll": "dmgsupBasicScrol",
  "sending stones": "dmgSendingStones",
  "sentinel shield": "dmgSentinelShiel",
  "serpent venom": "dmgSerpentVenom0",
  "serpentine owl": "dmgFwpSerpentine",
  "shawm": "phbmusShawm00000",
  "shield": "phbarmShield0000",
  "shield of missile attraction": "dmgShieldOfMissi",
  "shield of the cavalier": "dmgShieldOfTheCa",
  "shield, +1, +2, or +3": "dmgShield12or300",
  "short compartment": "dmgShortCompartm",
  "shortbow": "phbwepShortbow00",
  "shortsword": "phbwepShortsword",
  "shovel": "phbagShovel00000",
  "sickle": "phbwepSickle0000",
  "signal whistle": "phbagSignalWhist",
  "silver horn of valhalla": "dmgSilverHornOfV",
  "silver raven": "dmgFwpSilverRave",
  "skull": "dmgDmtSkull00000",
  "sling": "phbwepSling00000",
  "slippers of spider climbing": "dmgSlippersOfSpi",
  "smith's tools": "phbtulSmithsTool",
  "sovereign glue": "dmgSovereignGlue",
  "spear": "phbwepSpear00000",
  "spell scroll": "dmgSpellScroll00",
  "spell scroll, 1st level": "dmgSpellScroll1s",
  "spell scroll, 2nd level": "dmgSpellScroll2n",
  "spell scroll, 3rd level": "dmgSpellScroll3r",
  "spell scroll, 4th level": "dmgSpellScroll4t",
  "spell scroll, 5th level": "dmgSpellScroll5t",
  "spell scroll, 6th level": "dmgSpellScroll6t",
  "spell scroll, 7th level": "dmgSpellScroll7t",
  "spell scroll, 8th level": "dmgSpellScroll8t",
  "spell scroll, 9th level": "dmgSpellScroll9t",
  "spell scroll, cantrip": "phbagCantripScro",
  "spell scroll, level 1": "phbagSpellScroll",
  "spellguard shield": "dmgSpellguardShi",
  "sphere of annihilation": "dmgSphereOfAnnih",
  "spider's sting": "dmgLolthsSting00",
  "spiked pit": "dmgSpikedPit0000",
  "spikes, iron": "phbagSpikesIron0",
  "splint armor": "phbarmSplintArmo",
  "sprig of mistletoe": "phbdfcSprigofmis",
  "spyglass": "phbagSpyglass100",
  "staff": "phbafcStaffalsoa",
  "staff of charming": "dmgStaffOfCharmi",
  "staff of fire": "dmgStaffOfFire00",
  "staff of frost": "dmgStaffOfFrost0",
  "staff of healing": "dmgStaffOfHealin",
  "staff of power": "dmgStaffOfPower0",
  "staff of striking": "dmgStaffOfStriki",
  "staff of swarming insects": "dmgStaffOfSwarmi",
  "staff of the magi": "dmgStaffOfTheMag",
  "staff of the python": "dmgStaffOfThePyt",
  "staff of the woodlands": "dmgStaffOfTheWoo",
  "staff of thunder and lightning": "dmgStaffOfThunde",
  "staff of withering": "dmgStaffOfWither",
  "star": "dmgDmtStar000000",
  "stone of controlling earth elementals": "dmgStoneOfContro",
  "stone of good luck (luckstone)": "dmgStoneOfGoodLu",
  "string": "phbagString00000",
  "studded leather armor": "phbarmStuddedLea",
  "sun": "dmgDmtSun0000000",
  "sun blade": "dmgSunBlade00000",
  "sword of life stealing": "dmgSwordOfLifeSt",
  "sword of sharpness": "dmgSwordOfSharpn",
  "sword of wounding": "dmgSwordOfWoundi",
  "talisman of pure good": "dmgTalismanOfPur",
  "talisman of the sphere": "dmgTalismanOfThe",
  "talisman of ultimate evil": "dmgTalismanOfUlt",
  "talons": "dmgDmtTalons0000",
  "tan bag of tricks": "dmgTanBagofTrick",
  "tent": "phbagTent0000000",
  "thieves' tools": "phbtulThievesToo",
  "three-dragon ante": "phbgstThreedrago",
  "throne": "dmgDmtThrone0000",
  "thunderous greatclub": "dmgThunderousGre",
  "tinderbox": "RqrWyXa9XkriaxTP",
  "tinker's tools": "phbtulTinkersToo",
  "tome of clear thought": "dmgTomeOfClearTh",
  "tome of leadership and influence": "dmgTomeOfLeaders",
  "tome of understanding": "dmgTomeOfUnderst",
  "torch": "gYKSyS7STTresmnS",
  "torpor": "dmgTorpor0000000",
  "trident": "phbwepTrident000",
  "trident of fish command": "dmgTridentOfFish",
  "truth serum": "dmgTruthSerum000",
  "unarmed strike": "dmgUnarmedStrike",
  "universal solvent": "dmgUniversalSolv",
  "vial": "phbagVial0000000",
  "vicious weapon": "dmgViciousWeapon",
  "viol": "phbmusViol000000",
  "void": "dmgDmtVoid000000",
  "vorpal sword": "dmgVorpalSword00",
  "wand": "phbafcWand000000",
  "wand of binding": "dmgWandOfBinding",
  "wand of enemy detection": "dmgWandOfEnemyDe",
  "wand of fear": "dmgWandOfFear000",
  "wand of fireballs": "dmgWandOfFirebal",
  "wand of lightning bolts": "dmgWandOfLightni",
  "wand of magic detection": "dmgWandOfMagicDe",
  "wand of magic missiles": "dmgWandOfMagicMi",
  "wand of paralysis": "dmgWandOfParalys",
  "wand of polymorph": "dmgWandOfPolymor",
  "wand of secrets": "dmgWandOfSecrets",
  "wand of the war mage, +1, +2, or +3": "dmg1WandOfTheWar",
  "wand of web": "dmgWandOfWeb0000",
  "wand of wonder": "dmgWandOfWonder0",
  "war pick": "phbwepWarPick000",
  "warhammer": "phbwepWarhammer0",
  "water (pint)": "67ScUFYRuMU0J2Wt",
  "water ring of elemental command": "dmgWaterRingOfEl",
  "water, fresh (pint)": "dmgspWaterfresh0",
  "water, salt (pint)": "dmgspWatersalt00",
  "waterskin": "X5XgogJLLydoKdrJ",
  "weapon of warning": "dmgWeaponOfWarni",
  "weapon, +1, +2, or +3": "dmgWeapon12or300",
  "weaver's tools": "phbtulWeaversToo",
  "well of many worlds": "dmgWellOfManyWor",
  "whip": "phbwepWhip000000",
  "wind fan": "dmgWindFan000000",
  "winged boots": "dmgWingedBoots00",
  "wings of flying": "dmgWingsOfFlying",
  "woodcarver's tools": "phbtulWoodcarver",
  "wooden staff": "phbdfcWoodenstaf",
  "wyvern poison": "dmgWyvernPoison0",
  "yew wand": "phbdfcYewwand000",
};
