// =============================================================================
// sourceNamesData - GERADO por `npm run gen:sources`. NÃO EDITE À MÃO.
// =============================================================================
// Abreviação de fonte -> nome por extenso, extraído de Parser.SOURCE_JSON_TO_FULL
// (5etools, MIT). Só rótulos de fonte; nenhum conteúdo de jogo é redistribuído.
// Consumido por engine/sourceNames.js. 180 fontes.
// -----------------------------------------------------------------------------

/** @type {Readonly<Record<string, string>>} */
export const SOURCE_NAMES = {
  "AAG": "Astral Adventurer's Guide",
  "AATM": "Adventure Atlas: The Mortuary",
  "ABH": "Astarion's Book of Hungers",
  "AI": "Acquisitions Incorporated",
  "AitFR": "Adventures in the Forgotten Realms",
  "AitFR-AVT": "Adventures in the Forgotten Realms: A Verdant Tomb",
  "AitFR-DN": "Adventures in the Forgotten Realms: Deepest Night",
  "AitFR-FCD": "Adventures in the Forgotten Realms: From Cyan Depths",
  "AitFR-ISF": "Adventures in the Forgotten Realms: In Scarlet Flames",
  "AitFR-THP": "Adventures in the Forgotten Realms: The Hidden Page",
  "AL": "Adventurers' League",
  "AWM": "Adventure with Muk",
  "AZfyT": "A Zib for your Thoughts",
  "BAM": "Boo's Astral Menagerie",
  "BGDIA": "Baldur's Gate: Descent Into Avernus",
  "BGG": "Bigby Presents: Glory of the Giants",
  "BMT": "The Book of Many Things",
  "BQDD": "Borderlands Quest: Dagger Danger!",
  "BQGT": "Borderlands Quest: Goblin Trouble",
  "CaBoMP": "Crochet: A Book of Many Patterns",
  "CM": "Candlekeep Mysteries",
  "CoA": "Chains of Asmodeus",
  "CoS": "Curse of Strahd",
  "CRCotN": "Critical Role: Call of the Netherdeep",
  "DC": "Divine Contention",
  "DD": "Dangerous Designs",
  "DIP": "Dragon of Icespire Peak",
  "DitLCoT": "Descent into the Lost Caverns of Tsojcanth",
  "DMG": "Dungeon Master's Guide (2014)",
  "DMTCRG": "The Deck of Many Things: Card Reference Guide",
  "DoD": "Domains of Delight",
  "DoSI": "Dragons of Stormwreck Isle",
  "DrDe": "Dragon Delves",
  "DrDe-ACfaS": "A Copper for a Song",
  "DrDe-BD": "Baker's Doesn't",
  "DrDe-BtS": "Before the Storm",
  "DrDe-DaS": "Death at Sunset",
  "DrDe-DotSC": "Dragons of the Sandstone City",
  "DrDe-FWtVC": "For Whom the Void Calls",
  "DrDe-SD": "Shivering Death",
  "DrDe-TDoN": "The Dragon of Najkir",
  "DrDe-TFV": "The Forbidden Vale",
  "DrDe-TWoO": "The Will of Orcus",
  "DSotDQ": "Dragonlance: Shadow of the Dragon Queen",
  "EEPC": "Elemental Evil Player's Companion",
  "EET": "Elemental Evil: Trinkets",
  "EFA": "Eberron: Forge of the Artificer",
  "EFR": "Eberron: Forgotten Relics",
  "EGW": "Explorer's Guide to Wildemount",
  "ERLW": "Eberron: Rising from the Last War",
  "ESK": "Essentials Kit",
  "FFotR": "Fated Flight of the Recluse",
  "FRAiF": "Forgotten Realms: Adventures in Faerûn",
  "FRHoF": "Forgotten Realms: Heroes of Faerûn",
  "FS": "Frozen Sick",
  "FTD": "Fizban's Treasury of Dragons",
  "GGR": "Guildmasters' Guide to Ravnica",
  "GoS": "Ghosts of Saltmarsh",
  "GotSF": "Giants of the Star Forge",
  "HAT-LMI": "Honor Among Thieves: Legendary Magic Items",
  "HAT-TG": "Honor Among Thieves: Thieves' Gallery",
  "HBTD": "Hold Back The Dead",
  "HF": "Heroes' Feast",
  "HFDoMM": "Heroes' Feast: The Deck of Many Morsels",
  "HFFotM": "Heroes' Feast: Flavors of the Multiverse",
  "HFStCM": "Heroes' Feast: Saving the Children's Menu",
  "HftT": "Hunt for the Thessalhydra",
  "HoL": "The House of Lament",
  "HotB": "Heroes of the Borderlands",
  "HotDQ": "Hoard of the Dragon Queen",
  "IDRotF": "Icewind Dale: Rime of the Frostmaiden",
  "IMR": "Infernal Machine Rebuild",
  "JttRC": "Journeys through the Radiant Citadel",
  "KftGV": "Keys from the Golden Vault",
  "KKW": "Krenko's Way",
  "LFL": "Lorwyn: First Light",
  "LK": "Lightning Keep",
  "LLK": "Lost Laboratory of Kwalish",
  "LMoP": "Lost Mine of Phandelver",
  "LoX": "Light of Xaryxis",
  "LR": "Locathah Rising",
  "LRDT": "Red Dragon's Tale: A LEGO Adventure",
  "MaBJoV": "Minsc and Boo's Journal of Villainy",
  "MCV1SC": "Monstrous Compendium Volume 1: Spelljammer Creatures",
  "MCV2DC": "Monstrous Compendium Volume 2: Dragonlance Creatures",
  "MCV3MC": "Monstrous Compendium Volume 3: Minecraft Creatures",
  "MCV4EC": "Monstrous Compendium Volume 4: Eldraine Creatures",
  "MFF": "Mordenkainen's Fiendish Folio",
  "MGELFT": "Muk's Guide To Everything He Learned From Tasha",
  "MisMV1": "Misplaced Monsters: Volume 1",
  "MM": "Monster Manual (2014)",
  "MOT": "Mythic Odysseys of Theros",
  "MPMM": "Mordenkainen Presents: Monsters of the Multiverse",
  "MPP": "Morte's Planar Parade",
  "MTF": "Mordenkainen's Tome of Foes",
  "NF": "Netheril's Fall",
  "NRH": "NERDS Restoring Harmony",
  "NRH-ASS": "NERDS Restoring Harmony: A Sticky Situation",
  "NRH-AT": "NERDS Restoring Harmony: Adventure Together",
  "NRH-AVitW": "NERDS Restoring Harmony: A Voice in the Wilderness",
  "NRH-AWoL": "NERDS Restoring Harmony: A Web of Lies",
  "NRH-CoI": "NERDS Restoring Harmony: Circus of Illusions",
  "NRH-TCMC": "NERDS Restoring Harmony: The Candy Mountain Caper",
  "NRH-TLT": "NERDS Restoring Harmony: The Lost Tomb",
  "OGA": "One Grung Above",
  "OotA": "Out of the Abyss",
  "OoW": "The Orrery of the Wanderer",
  "PaBTSO": "Phandelver and Below: The Shattered Obelisk",
  "PaF": "Puncheons and Flagons",
  "PAitM": "Planescape: Adventures in the Multiverse",
  "PHB": "Player's Handbook (2014)",
  "PiP": "Peril in Pinebrook",
  "PotA": "Princes of the Apocalypse",
  "PSA": "Plane Shift: Amonkhet",
  "PSD": "Plane Shift: Dominaria",
  "PSI": "Plane Shift: Innistrad",
  "PSK": "Plane Shift: Kaladesh",
  "PSX": "Plane Shift: Ixalan",
  "PSZ": "Plane Shift: Zendikar",
  "QftIS": "Quests from the Infinite Staircase",
  "RHW": "Ravenloft: The Horrors Within",
  "RMBRE": "The Lost Dungeon of Rickedness: Big Rick Energy",
  "RMR": "Dungeons & Dragons vs. Rick and Morty: Basic Rules",
  "RoT": "The Rise of Tiamat",
  "RoTOS": "The Rise of Tiamat Online Supplement",
  "RtG": "Return to Glory",
  "SAC": "Sage Advice Compendium (5e/2014)",
  "SADS": "Sapphire Anniversary Dice Set",
  "SAiS": "Spelljammer: Adventures in Space",
  "SatO": "Sigil and the Outlands",
  "SCAG": "Sword Coast Adventurer's Guide",
  "SCC": "Strixhaven: A Curriculum of Chaos",
  "SCC-ARiR": "A Reckoning in Ruins",
  "SCC-CK": "Campus Kerfuffle",
  "SCC-HfMT": "Hunt for Mage Tower",
  "SCC-TMM": "The Magister's Masquerade",
  "ScoEE": "Scions of Elemental Evil",
  "Screen": "Dungeon Master's Screen",
  "ScreenDungeonKit": "Dungeon Master's Screen: Dungeon Kit",
  "ScreenSpelljammer": "Dungeon Master's Screen: Spelljammer",
  "ScreenWildernessKit": "Dungeon Master's Screen: Wilderness Kit",
  "SDW": "Sleeping Dragon's Wake",
  "SjA": "Spelljammer Academy",
  "SKT": "Storm King's Thunder",
  "SLW": "Storm Lord's Wrath",
  "TCE": "Tasha's Cauldron of Everything",
  "TD": "Tarot Deck",
  "TftYP": "Tales from the Yawning Portal",
  "TftYP-AtG": "Tales from the Yawning Portal: Against the Giants",
  "TftYP-DiT": "Tales from the Yawning Portal: Dead in Thay",
  "TftYP-TFoF": "Tales from the Yawning Portal: The Forge of Fury",
  "TftYP-THSoT": "Tales from the Yawning Portal: The Hidden Shrine of Tamoachan",
  "TftYP-ToH": "Tales from the Yawning Portal: Tomb of Horrors",
  "TftYP-TSC": "Tales from the Yawning Portal: The Sunless Citadel",
  "TftYP-WPM": "Tales from the Yawning Portal: White Plume Mountain",
  "TLK": "The Lost Kenku",
  "ToA": "Tomb of Annihilation",
  "ToD": "Tyranny of Dragons",
  "ToFW": "Turn of Fortune's Wheel",
  "ToR": "Tide of Retribution",
  "TTP": "The Tortle Package",
  "UATheMysticClass": "Unearthed Arcana: The Mystic Class",
  "US": "Unwelcome Spirits",
  "UtHftLH": "Uni and the Hunt for the Lost Horn",
  "VD": "Vecna Dossier",
  "VEoR": "Vecna: Eve of Ruin",
  "VGM": "Volo's Guide to Monsters",
  "VNotEE": "Vecna: Nest of the Eldritch Eye",
  "VRGR": "Van Richten's Guide to Ravenloft",
  "WBtW": "The Wild Beyond the Witchlight",
  "WDH": "Waterdeep: Dragon Heist",
  "WDMM": "Waterdeep: Dungeon of the Mad Mage",
  "WttHC": "Stranger Things: Welcome to the Hellfire Club",
  "XDMG": "Dungeon Master's Guide (2024)",
  "XGE": "Xanathar's Guide to Everything",
  "XMM": "Monster Manual (2025)",
  "XMtS": "X Marks the Spot",
  "XPHB": "Player's Handbook (2024)",
  "XSAC": "Sage Advice Compendium (2025)",
  "XScreen": "Dungeon Master's Screen (2024)",
};
